let aprovaCatalog={items:[],sources:[],loaded:false};
async function loadAprovaCatalog(){
 try{
  const [c,s]=await Promise.all([fetch('data/catalog.json?ts='+Date.now()),fetch('data/sources.json?ts='+Date.now())]);
  const cj=await c.json(),sj=await s.json(); aprovaCatalog.items=cj.items||[]; aprovaCatalog.sources=sj.sources||[]; aprovaCatalog.loaded=true;
  enrichTargetList(); if(typeof syncOfficialExamDate==='function'&&syncOfficialExamDate())uRenderAll(); renderCatalog();
 }catch(e){console.warn('Catálogo indisponível',e); renderCatalog(true);}
}
function norm(s){return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function enrichTargetList(){const dl=document.getElementById('popularTargets'); if(!dl)return; const existing=new Set([...dl.options].map(o=>o.value)); aprovaCatalog.items.slice(0,150).forEach(x=>{if(!existing.has(x.title)){const o=document.createElement('option');o.value=x.title;dl.appendChild(o);}});}
function selectCatalogItem(id){const x=aprovaCatalog.items.find(i=>i.id===id);if(!x)return; u.profile=u.profile||{};u.profile.target=x.title;u.profile.banca=x.banca;u.profile.catalogId=x.id;if(x.exam_date){u.profile.examDate=x.exam_date;universalExam=new Date(x.exam_date+'T13:00:00-03:00');}usave();uRenderAll();document.querySelector('[data-tab="hoje"]')?.click();}
function renderCatalog(failed=false){const el=document.getElementById('catalogo');if(!el)return;if(failed){el.innerHTML='<div class="card"><h2>Catálogo</h2><p>Não foi possível carregar o catálogo agora. Tente novamente em instantes.</p></div>';return;}
 const bancas=[...new Set(aprovaCatalog.items.map(x=>x.banca))].sort();
 el.innerHTML=`<div class="card"><div class="catalog-head"><div><h2>Catálogo de provas e concursos</h2><p class="muted">Pesquise por órgão, cargo, prova ou banca. A plataforma usa a fonte oficial para manter o alvo organizado.</p></div><div class="kpi">${aprovaCatalog.items.length}<small>certames indexados</small></div></div><div class="catalog-tools"><input id="catalogSearch" type="search" placeholder="Ex.: Polícia Civil, DATAPREV, FGV, TRT..." oninput="filterCatalog()"><select id="catalogBanca" onchange="filterCatalog()"><option value="">Todas as bancas</option>${bancas.map(b=>`<option>${b}</option>`).join('')}</select></div><div class="source-strip">${aprovaCatalog.sources.length} fontes oficiais cadastradas • atualização automática ativa nas fontes compatíveis</div><div id="catalogList"></div></div>`;filterCatalog();}
function filterCatalog(){const q=norm(document.getElementById('catalogSearch')?.value),b=document.getElementById('catalogBanca')?.value||'';const list=aprovaCatalog.items.filter(x=>(!b||x.banca===b)&&(!q||norm([x.title,x.banca,x.status,...(x.tags||[])].join(' ')).includes(q))).slice(0,100);const el=document.getElementById('catalogList');if(!el)return;el.innerHTML=list.length?list.map(x=>`<article class="catalog-card"><div><span class="pill">${x.banca}</span><h3>${x.title}</h3><p class="muted">${x.status} • ${x.category||'Concurso'}</p></div><div class="catalog-actions"><button class="btn good" onclick="selectCatalogItem('${x.id}')">Estudar este</button><a class="btn secondary linkbtn" href="${x.source_url}" target="_blank" rel="noopener">Fonte oficial ↗</a></div></article>`).join(''):'<p class="muted">Nenhum resultado encontrado. Você ainda pode digitar manualmente sua prova na tela inicial.</p>';}
loadAprovaCatalog();
