/* Aprova Mastery — aprendizado acelerado para OAB e concursos */
const MASTER_KEY='aprova-mastery-v1';
let mastery=JSON.parse(localStorage.getItem(MASTER_KEY)||'{}');
mastery.oab=mastery.oab||{module:0,stage:0,answer:{}};
mastery.contest=mastery.contest||{};
const BASE_U_RENDER_SCHEDULE=window.uRenderSchedule;
const BASE_U_RENDER_SIM=window.uRenderSim;
function msave(){localStorage.setItem(MASTER_KEY,JSON.stringify(mastery));}
function isOabMastery(){return u?.profile?.track==='oab2';}
function escM(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

const OAB_MODULES=[
 {title:'ADPF — norma pré-CF e subsidiariedade',tag:'ADPF',hook:'Norma anterior à Constituição + controle concentrado no STF = pense em ADPF e confirme a subsidiariedade.',law:[['CF art. 102, §1º','Prevê a ADPF e a competência do STF.'],['Lei 9.882/99, art. 1º','Objeto da ADPF e controvérsia sobre normas inclusive anteriores à Constituição.'],['Lei 9.882/99, art. 4º, §1º','Não cabe ADPF se houver outro meio eficaz de sanar a lesividade.'],['CF art. 103','Legitimados do controle concentrado.']],branches:[['Gatilho','norma pré-CF/88'],['Órgão','STF'],['Lei','9.882/99'],['Pegadinha','subsidiariedade'],['Resposta','conclusão + regra + artigo + aplicação']],casePage:'official/pages/oab-46-p1.webp',caseCaption:'46º EOU — caso de controle concentrado com norma anterior à CF/88.',pieceTitle:'ADPF — modelo preenchido para memorizar',piece:`Excelentíssimo Senhor Ministro Presidente do Supremo Tribunal Federal.\n\nPARTIDO POLÍTICO ALFA, com representação no Congresso Nacional, por seu advogado, vem propor ARGUIÇÃO DE DESCUMPRIMENTO DE PRECEITO FUNDAMENTAL, com fundamento no art. 102, §1º, e art. 103, VIII, da Constituição Federal, e na Lei 9.882/99, em face de norma estadual anterior à Constituição de 1988.\n\nI — CABIMENTO\nA ADPF é cabível porque a controvérsia envolve ato normativo anterior à Constituição e lesão a preceito fundamental. Não existe outro meio eficaz para sanar a lesividade, estando atendida a subsidiariedade do art. 4º, §1º, da Lei 9.882/99.\n\nII — FUNDAMENTAÇÃO\nA norma impugnada é incompatível com a ordem constitucional vigente e viola o preceito fundamental indicado no caso, devendo ser afastada pelo Supremo Tribunal Federal.\n\nIII — PEDIDOS\nRequer a concessão da medida cautelar, a requisição de informações, as manifestações institucionais cabíveis e, ao final, a procedência da ADPF para afastar a lesão ao preceito fundamental.\n\nTermos em que, pede deferimento.\nLocal e data.\nAdvogado(a)\nOAB nº ____.` ,qa:[['Qual é o gatilho mais forte neste módulo?','Norma anterior à CF/88 submetida a controle concentrado no STF, observada a subsidiariedade.'],['Qual artigo constitucional prevê a ADPF?','Art. 102, §1º, da Constituição Federal.'],['Onde está a subsidiariedade?','Art. 4º, §1º, da Lei 9.882/99.']]},
 {title:'Mandado de Segurança + Ação Popular',tag:'MS/AP',hook:'Ato concreto de autoridade + direito líquido e certo + prova pronta = MS. Cidadão + ato lesivo ao patrimônio/moralidade/meio ambiente = Ação Popular.',law:[['CF art. 5º, LXIX','Base constitucional do MS individual.'],['Lei 12.016/09, arts. 1º, 6º e 23','Cabimento, inicial e prazo decadencial.'],['CF art. 5º, LXXIII','Base constitucional da Ação Popular.'],['Lei 4.717/65','Disciplina a Ação Popular.']],branches:[['MS','direito líquido e certo'],['AP','cidadão + lesividade'],['Prova','pré-constituída no MS'],['Prazo MS','120 dias'],['FGV','identifique o ato concreto']],casePage:'official/pages/oab-45-p1.webp',caseCaption:'45º EOU — Mandado de Segurança em caso de ato concreto e competência constitucional.',pieceTitle:'Mandado de Segurança — modelo preenchido',piece:`Excelentíssimo Senhor Doutor Juiz de Direito da Vara da Fazenda Pública da Comarca de Alfa.\n\nJOÃO DA SILVA, brasileiro, comerciante, por seu advogado, com fundamento no art. 5º, LXIX, da Constituição Federal e na Lei 12.016/09, impetra MANDADO DE SEGURANÇA contra ato do SECRETÁRIO MUNICIPAL DE FISCALIZAÇÃO.\n\nI — CABIMENTO\nO ato administrativo impugnado viola direito líquido e certo demonstrável por prova pré-constituída, não se tratando de hipótese de habeas corpus ou habeas data.\n\nII — DIREITO\nA Administração Pública está submetida à Constituição e à legalidade. A norma municipal utilizada como fundamento do ato invadiu competência legislativa constitucionalmente reservada à União, razão pela qual o ato concreto é incompatível com a Constituição.\n\nIII — LIMINAR\nDiante da relevância dos fundamentos e do risco de dano decorrente da manutenção do ato, requer a suspensão imediata de seus efeitos.\n\nIV — PEDIDOS\nRequer a notificação da autoridade coatora, a ciência à pessoa jurídica interessada, a oitiva do Ministério Público e, ao final, a concessão definitiva da segurança.\n\nTermos em que, pede deferimento.\nLocal e data.\nAdvogado(a)\nOAB nº ____.` ,qa:[['Quando pensar em Mandado de Segurança?','Quando houver ato ou omissão de autoridade, direito líquido e certo, prova pré-constituída e não for caso de HC ou HD.'],['Qual prazo merece atenção no MS?','120 dias da ciência do ato impugnado.'],['Qual o gatilho da Ação Popular?','Cidadão buscando anular ato lesivo ao patrimônio público, moralidade, meio ambiente ou patrimônio histórico-cultural.']]},
 {title:'Mandado de Injunção + Habeas Data',tag:'MI/HD',hook:'Direito constitucional travado por falta de regulamentação = MI. Dados pessoais em banco público = Habeas Data.',law:[['CF art. 5º, LXXI','Previsão constitucional do MI.'],['Lei 13.300/16, arts. 2º e 3º','Cabimento e legitimidade.'],['CF art. 5º, LXXII','Previsão do Habeas Data.'],['Lei 9.507/97','Disciplina o Habeas Data.']],branches:[['MI','omissão normativa'],['Concreto','direito inviabilizado'],['HD','dados pessoais'],['Diferença','MI ≠ ADO'],['FGV','identifique titular + órgão omisso']],casePage:'official/pages/oab-42-p5.webp',caseCaption:'42º EOU — questão sobre Mandado de Injunção e ADO.',pieceTitle:'Mandado de Injunção — modelo preenchido',piece:`Excelentíssimo Senhor Ministro Presidente do Supremo Tribunal Federal.\n\nCOOPERATIVA DE GARIMPEIROS ALFA, pessoa jurídica titular da prerrogativa constitucional inviabilizada, por seu advogado, vem impetrar MANDADO DE INJUNÇÃO, com fundamento no art. 5º, LXXI, da Constituição Federal e na Lei 13.300/16, em face da omissão do CONGRESSO NACIONAL.\n\nI — CABIMENTO\nA ausência de norma regulamentadora impede o exercício concreto da prerrogativa assegurada pela Constituição, caracterizando a hipótese prevista no art. 2º da Lei 13.300/16.\n\nII — COMPETÊNCIA\nCompete originariamente ao Supremo Tribunal Federal processar e julgar o mandado de injunção quando a elaboração da norma regulamentadora é atribuição do Congresso Nacional, nos termos do art. 102, I, q, da Constituição Federal.\n\nIII — OMISSÃO INCONSTITUCIONAL\nO Congresso Nacional possui o dever constitucional de editar a norma necessária e permanece omisso, tornando inviável o exercício do direito da impetrante.\n\nIV — PEDIDOS\nRequer a notificação do órgão impetrado, a oitiva do Ministério Público e, ao final, o reconhecimento da mora legislativa, com a adoção das providências necessárias para viabilizar o exercício do direito constitucional.\n\nTermos em que, pede deferimento.\nLocal e data.\nAdvogado(a)\nOAB nº ____.` ,qa:[['Qual é o gatilho do MI?','Omissão normativa que torna inviável o exercício de direito, liberdade ou prerrogativa constitucional.'],['MI e ADO são iguais?','Não. O MI protege situação concreta do titular; a ADO realiza controle objetivo da omissão.'],['Qual o núcleo do Habeas Data?','Conhecer, retificar ou complementar dados pessoais do próprio impetrante em registros públicos ou de caráter público.']]},
 {title:'ADI, ADC, ADO e ADPF',tag:'Controle',hook:'Pergunte primeiro qual é o problema: norma inconstitucional, norma a confirmar, omissão ou preceito fundamental.',law:[['CF art. 102, I, a','Competência do STF para ADI e ADC.'],['CF art. 103','Legitimados.'],['Lei 9.868/99','ADI, ADC e ADO.'],['Lei 9.882/99','ADPF.']],branches:[['ADI','lei federal/estadual pós-CF'],['ADC','norma federal a confirmar'],['ADO','omissão'],['ADPF','preceito fundamental'],['Primeiro passo','defina objeto + legitimado']],casePage:'official/pages/oab-45-p6.webp',caseCaption:'45º EOU — questão de controle concentrado.',pieceTitle:'ADI — modelo preenchido',piece:`Excelentíssimo Senhor Ministro Presidente do Supremo Tribunal Federal.\n\nGOVERNADOR DO ESTADO ALFA, por seu advogado, com fundamento nos arts. 102, I, a, e 103, V, da Constituição Federal e na Lei 9.868/99, propõe AÇÃO DIRETA DE INCONSTITUCIONALIDADE em face da Lei Estadual nº 100/2026.\n\nI — LEGITIMIDADE E CABIMENTO\nO requerente integra o rol do art. 103 da Constituição Federal. A norma estadual, posterior à Constituição, contém ofensa direta ao texto constitucional.\n\nII — INCONSTITUCIONALIDADE\nA lei apresenta vício formal e material porque disciplina matéria constitucionalmente reservada a outro ente e viola o parâmetro constitucional aplicável.\n\nIII — CAUTELAR\nA manutenção da norma produz efeitos imediatos e potencialmente lesivos, razão pela qual se requer a concessão de medida cautelar.\n\nIV — PEDIDOS\nRequer informações, as manifestações institucionais cabíveis e, ao final, a declaração de inconstitucionalidade da norma impugnada.\n\nTermos em que, pede deferimento.\nLocal e data.\nAdvogado(a)\nOAB nº ____.` ,qa:[['Qual é o objeto típico da ADI no STF?','Lei ou ato normativo federal ou estadual posterior à Constituição, impugnado em tese.'],['Qual ação busca confirmar a constitucionalidade?','ADC, tendo como objeto lei ou ato normativo federal.'],['Qual ação combate omissão inconstitucional em controle objetivo?','ADO.']]},
 {title:'Controle de constitucionalidade',tag:'Difuso/Concentrado',hook:'Caso concreto + questão incidental = difuso. Norma em tese + ação própria = concentrado.',law:[['CF art. 97','Reserva de plenário.'],['CF art. 102, III','Recurso Extraordinário.'],['CF art. 52, X','Competência do Senado.'],['CF arts. 102 e 103','Controle concentrado.']],branches:[['Difuso','caso concreto'],['Concentrado','norma em tese'],['Tribunal','reserva de plenário'],['STF','RE ou ações abstratas'],['FGV','efeitos + competência']],casePage:'official/pages/oab-43-p5.webp',caseCaption:'43º EOU — questão sobre ADI, ADPF e subsidiariedade.',pieceTitle:'Tópico de inconstitucionalidade incidental',piece:`DA INCONSTITUCIONALIDADE INCIDENTAL\n\nA Constituição ocupa posição superior no ordenamento jurídico e vincula toda a legislação infraconstitucional. No caso concreto, a aplicação da norma estadual conduz a resultado incompatível com a Constituição Federal, pois invade competência legislativa reservada à União.\n\nPor se tratar de controvérsia surgida incidentalmente em demanda concreta, requer-se o reconhecimento da incompatibilidade constitucional e o afastamento da norma na solução do caso. Caso a declaração seja realizada por tribunal, deve ser observada a cláusula de reserva de plenário prevista no art. 97 da Constituição Federal.` ,qa:[['Qual o gatilho do controle difuso?','Questão constitucional surgida incidentalmente em um caso concreto.'],['Qual artigo traz a reserva de plenário?','Art. 97 da Constituição Federal.'],['O que diferencia o concentrado?','A norma é discutida em tese por meio de ação própria de controle abstrato.']]},
 {title:'Recurso Extraordinário + Reclamação',tag:'RE/Rcl',hook:'Já existe decisão judicial com questão constitucional? Pense em RE. Ato afronta competência/decisão vinculante? Teste Reclamação.',law:[['CF art. 102, III','Hipóteses do RE.'],['CPC art. 1.029','Interposição dos recursos excepcionais.'],['CPC art. 1.035','Repercussão geral.'],['CPC art. 988','Hipóteses de Reclamação.']],branches:[['RE','decisão + questão constitucional'],['Rcl','autoridade/competência'],['RE','repercussão geral'],['Rcl','aderência ao paradigma'],['FGV','não confunda ação e recurso']],casePage:'official/pages/oab-42-p1.webp',caseCaption:'42º EOU — peça de Reclamação.',pieceTitle:'Reclamação — modelo preenchido',piece:`Excelentíssimo Senhor Ministro Presidente do Supremo Tribunal Federal.\n\nJOÃO DA SILVA, advogado e credor de honorários alimentares, por seu advogado, vem propor RECLAMAÇÃO, com fundamento no art. 988 do CPC e no art. 103-A, §3º, da Constituição Federal, em face de ato do PRESIDENTE DO TRIBUNAL DE JUSTIÇA DO ESTADO ALFA.\n\nI — CABIMENTO\nO ato reclamado deixou de observar enunciado de súmula vinculante aplicável ao caso, enquadrando-se na hipótese legal de Reclamação.\n\nII — ADERÊNCIA AO PARADIGMA\nA situação concreta reproduz a hipótese jurídica protegida pelo precedente vinculante, de modo que o ato reclamado deve ser ajustado.\n\nIII — PEDIDOS\nRequer a concessão da medida urgente, se cabível, informações da autoridade reclamada e, ao final, a procedência da Reclamação para cassar o ato incompatível com o paradigma vinculante.\n\nTermos em que, pede deferimento.\nLocal e data.\nAdvogado(a)\nOAB nº ____.` ,qa:[['Quando pensar em RE?','Quando já houver decisão de única ou última instância e a controvérsia se enquadrar no art. 102, III, da CF.'],['Qual requisito importante deve aparecer no RE?','A repercussão geral, nos termos do CPC.'],['Qual artigo central da Reclamação?','Art. 988 do CPC.']]},
 {title:'Direitos fundamentais',tag:'Art. 5º',hook:'Identifique o direito atingido, encontre o inciso específico e responda com conclusão + regra + artigo + aplicação.',law:[['CF art. 5º','Direitos e garantias fundamentais.'],['CF arts. 12 e 13','Nacionalidade.'],['CF arts. 14 a 16','Direitos políticos.'],['CF art. 60, §4º','Cláusulas pétreas.']],branches:[['Direito','qual foi atingido?'],['Inciso','cite o específico'],['Aplicação','ligue ao fato'],['Conclusão','sim/não'],['FGV','não basta citar art. 5º']],casePage:'official/pages/oab-46-p3.webp',caseCaption:'46º EOU — questão discursiva de direitos e regras constitucionais.',pieceTitle:'Modelo de fundamentação de direito fundamental',piece:`DA VIOLAÇÃO AO DIREITO FUNDAMENTAL\n\nA Constituição Federal assegura a liberdade de expressão e veda a censura prévia, protegendo a manifestação do pensamento e a comunicação. No caso, o ato estatal impede previamente a divulgação de manifestação lícita sem base constitucional adequada.\n\nA restrição é incompatível com a Constituição, razão pela qual deve ser afastada, preservando-se o exercício do direito fundamental nos limites constitucionalmente previstos.` ,qa:[['Como começar uma discursiva de direito fundamental?','Comece pela conclusão direta: sim ou não; depois explique a regra, cite o inciso exato e aplique ao fato.'],['Citar apenas “art. 5º” costuma bastar?','Não. O espelho costuma separar a tese jurídica do dispositivo específico.'],['Qual artigo protege as cláusulas pétreas?','Art. 60, §4º, da Constituição Federal.']]},
 {title:'Federação, competências e processo legislativo',tag:'Competências',hook:'Pergunte: qual ente? qual matéria? executar ou legislar? Depois vá ao bloco constitucional correto.',law:[['CF arts. 21 e 23','Competências materiais.'],['CF arts. 22 e 24','Competências legislativas.'],['CF art. 30','Competência municipal.'],['CF arts. 59 a 69','Processo legislativo.']],branches:[['Quem?','União/Estado/Município'],['O quê?','matéria'],['Tipo','material ou legislativa'],['Vício','competência/iniciativa'],['Simetria','ancore no artigo modelo']],casePage:'official/pages/oab-44-p5.webp',caseCaption:'44º EOU — competências, simetria e controle.',pieceTitle:'Fundamentação — inconstitucionalidade formal por competência',piece:`DA INCONSTITUCIONALIDADE FORMAL POR INVASÃO DE COMPETÊNCIA\n\nA Constituição Federal distribui competências entre os entes federativos. A matéria em discussão encontra-se submetida à competência legislativa privativa da União, nos termos do dispositivo constitucional aplicável.\n\nEntretanto, o Estado Alfa editou lei disciplinando diretamente essa matéria, embora não possua competência constitucional para fazê-lo. Há, portanto, inconstitucionalidade formal orgânica por invasão da competência constitucionalmente atribuída à União.` ,qa:[['Como diferenciar art. 21 de art. 22?','Art. 21 reúne competências materiais da União; art. 22 reúne competências legislativas privativas.'],['Onde está o interesse local do Município?','Art. 30, I, da Constituição Federal.'],['Como usar o princípio da simetria?','Como regra geral, sempre ancorado no dispositivo constitucional específico que funciona como modelo.']]},
 {title:'Simulado guiado',tag:'Simulado',hook:'Triagem → esqueleto → Vade → peça → 4 questões → revisão pelo espelho.',law:[['Checklist','Competência, legitimidade, cabimento, fundamentos e pedidos.'],['Tempo','Reserve bloco final para revisar.'],['Espelho','Corrija item por item.'],['Erro','Transforme perda de ponto em regra de revisão.']],branches:[['15 min','triagem'],['Peça','estrutura antes de redigir'],['Questões','resposta direta'],['Revisão','espelho'],['Erro','vira flashcard']],casePage:'official/pages/oab-46-p1.webp',caseCaption:'46º EOU — use o caderno completo como simulado.',pieceTitle:'Checklist de peça antes de entregar',piece:`ENDEREÇAMENTO CORRETO\nQUALIFICAÇÃO E LEGITIMIDADE\nNOME DA PEÇA E FUNDAMENTO DE CABIMENTO\nFATOS ESSENCIAIS\nFUNDAMENTAÇÃO GERAL\nFUNDAMENTAÇÃO ESPECÍFICA COM ARTIGO EXATO\nLIMINAR OU TUTELA, QUANDO CABÍVEL\nPEDIDOS COMPLETOS E COERENTES\nFECHAMENTO\nREVISÃO FINAL SEM DADOS INVENTADOS`,qa:[['O que descobrir antes de escrever?','Quem pede, contra quem, qual ato, qual objetivo, qual órgão competente e qual instrumento resolve a situação.'],['Como corrigir o simulado?','Compare item por item com o espelho e classifique cada perda em conteúdo, estrutura, fundamento ou tempo.'],['Qual erro deve ser evitado?','Começar a redigir antes de definir competência, cabimento, fundamentos e pedidos.']]},
 {title:'Revisão final — reconhecimento em segundos',tag:'Revisão',hook:'Na véspera, reconheça gatilhos, localize artigos-âncora e repita estruturas já treinadas.',law:[['MS','ato concreto + direito líquido e certo'],['MI','omissão normativa concreta'],['ADPF','norma pré-CF / preceito fundamental'],['ADI','lei federal/estadual pós-CF em tese']],branches:[['MS','ato concreto'],['MI','direito travado'],['ADPF','norma antiga'],['ADI','controle abstrato'],['Meta','reconhecer em segundos']],casePage:'official/pages/oab-46-p1.webp',caseCaption:'46º EOU — revisão de reconhecimento de peça e espelho.',pieceTitle:'Mapa universal de peça',piece:`1. PARA QUEM? — competência e endereçamento.\n2. QUEM PEDE E CONTRA QUEM? — legitimidade.\n3. POR QUE ESTA PEÇA? — cabimento.\n4. O QUE ACONTECEU? — fatos essenciais.\n5. QUAL REGRA GERAL? — eixo constitucional.\n6. QUAL ARTIGO RESOLVE? — fundamento específico.\n7. PRECISA DE URGÊNCIA? — liminar ou tutela.\n8. O QUE QUERO DO JULGADOR? — pedidos.\n9. O QUE FALTA? — fechamento e revisão.`,qa:[['Ato de autoridade + direito líquido e certo + prova pronta?','Mandado de Segurança.'],['Omissão normativa que impede direito constitucional concreto?','Mandado de Injunção.'],['Norma anterior à CF/88 em controle concentrado no STF?','ADPF, observada a subsidiariedade.']]}
];

const BANCA_METHODS={
 'fgv':{name:'FGV',tip:'Leia o caso inteiro antes das alternativas. A banca combina interpretação, conceitos próximos e aplicação prática. Nas jurídicas, regra + aplicação costuma ser mais segura do que decorar frase isolada.'},
 'cebraspe':{name:'Cebraspe',tip:'Julgue cada assertiva palavra por palavra. Termos absolutos, exceções e pequenas trocas de competência mudam o item inteiro.'},
 'aocp':{name:'Instituto AOCP',tip:'Dê peso à literalidade da norma e aos conceitos centrais. Em Português e Informática, diferenças pequenas entre termos são comuns.'},
 'idecan':{name:'IDECAN',tip:'Treine literalidade, legislação específica e questões objetivas diretas. Atenção a detalhes de competência, prazo, exceção e norma local.'},
 'fcc':{name:'FCC',tip:'Em Português, leia com profundidade o texto e a sintaxe. Nas jurídicas, compare cuidadosamente conceitos e dispositivos.'},
 'vunesp':{name:'Vunesp',tip:'Questões geralmente objetivas, mas com alternativas próximas. Domine a regra-base e as exceções mais cobradas.'},
 'quadrix':{name:'Quadrix',tip:'Combine leitura literal da legislação com atenção a conceitos e exceções. Evite responder por “sensação” quando houver palavra-chave normativa.'},
 'default':{name:'sua banca',tip:'Identifique o padrão da banca: literalidade, caso prático, certo/errado ou interpretação. Resolva questões e transforme cada erro em uma regra curta.'}
};
function bancaMethod(){const b=String(u?.profile?.banca||'').toLowerCase();return Object.entries(BANCA_METHODS).find(([k])=>k!=='default'&&b.includes(k))?.[1]||BANCA_METHODS.default;}

function oabCurrent(){return OAB_MODULES[Math.max(0,Math.min(OAB_MODULES.length-1,Number(mastery.oab.module)||0))];}
function setOabModule(i){i=Math.max(0,Math.min(OAB_MODULES.length-1,i));if(i>0&&!u.trial?.paid){const pw=document.getElementById('paywall');if(pw)pw.hidden=false;return;}mastery.oab.module=i;mastery.oab.stage=0;mastery.oab.answer={};msave();renderMasterAll();window.scrollTo({top:0,behavior:'smooth'});}
function finishOabModule(){if(!u.trial?.paid){u.trial.firstStageCompleted=true;usave();const pw=document.getElementById('paywall');if(pw)pw.hidden=false;return;}if(mastery.oab.module<OAB_MODULES.length-1)setOabModule(mastery.oab.module+1);}
function setOabStage(s){mastery.oab.stage=Math.max(0,Math.min(8,s));msave();renderMasterAll();window.scrollTo({top:0,behavior:'smooth'});}
function oabNav(){const s=mastery.oab.stage;return `<div class="master-nav"><button class="btn secondary" ${s<=0?'disabled':''} onclick="setOabStage(${s-1})">← Voltar</button><span>${s+1}/9</span><button class="btn good" ${s>=8?'disabled':''} onclick="setOabStage(${s+1})">Continuar →</button></div>`;}
function oabMap(m){return `<div class="brain-map"><div class="brain-center"><small>MAPA MENTAL</small><b>${escM(m.tag)}</b></div>${m.branches.map((b,i)=>`<div class="brain-branch b${i+1}"><span>${i+1}</span><b>${escM(b[0])}</b><small>${escM(b[1])}</small></div>`).join('')}</div>`;}
function oabStageHtml(){const m=oabCurrent(),s=mastery.oab.stage;
 if(s===0)return `<div class="do-now">APRENDIZADO ACELERADO • ETAPA 1</div><h2>${m.title}</h2><div class="master-lesson"><div class="sticker">🧠</div><div><b>Entenda em uma frase</b><p>${m.hook}</p></div></div><p class="muted">Não decore a peça inteira primeiro. Aprenda o gatilho, localize a base legal e só depois copie a estrutura.</p>`;
 if(s===1)return `<div class="do-now">ETAPA 2 • LEI DENTRO DO SISTEMA</div><h2>Leia só o que precisa agora</h2><div class="law-card-grid">${m.law.map((x,i)=>`<div class="law-study-card"><span>${i+1}</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}</div><div class="callout"><b>Regra de prova:</b> explique o conteúdo da norma e depois cite o artigo. Só jogar o número do dispositivo costuma deixar pontos na mesa.</div>`;
 if(s===2)return `<div class="do-now">ETAPA 3 • ASSOCIAÇÃO VISUAL</div><h2>Mapa mental ligado por gatilhos</h2>${oabMap(m)}<p class="muted center">Leia o centro e tente reconstruir os cinco ramos sem olhar.</p>`;
 if(s===3)return `<div class="do-now">ETAPA 4 • CASO OAB/FGV</div><h2>Veja o padrão real da prova</h2><p>${m.caseCaption}</p><figure class="master-source-page"><img src="${m.casePage}" alt="Página oficial FGV/OAB usada no estudo" loading="lazy"></figure><p class="muted">A fonte fica dentro do Aprova para você estudar sem sair da plataforma.</p>`;
 if(s===4)return `<div class="do-now">ETAPA 5 • PEÇA PRONTA</div><h2>${m.pieceTitle}</h2><p class="muted">Copie uma vez. Depois feche e tente reescrever a ordem dos tópicos de memória.</p><div class="copy-model"><pre>${escM(m.piece)}</pre></div><div class="master-actions"><button class="btn good" onclick="copyMasterPiece()">Copiar peça</button><button class="btn secondary" onclick="openMasterPiece()">Tela cheia</button></div>`;
 if(s===5)return `<div class="do-now">ETAPA 6 • COMO ESCREVER</div><h2>Estrutura que você vai repetir na prova</h2><div class="writing-road"><div><span>1</span><b>Endereçamento</b><small>órgão concreto competente</small></div><div><span>2</span><b>Legitimidade</b><small>quem pede e contra quem</small></div><div><span>3</span><b>Cabimento</b><small>fato + requisito da peça</small></div><div><span>4</span><b>Fundamentos</b><small>geral → específico → aplicação</small></div><div><span>5</span><b>Pedidos</b><small>cada tese gera consequência</small></div></div><div class="success"><b>Memorize a ordem, não os nomes do caso.</b> O enunciado muda; a arquitetura da resposta se repete.</div>`;
 if(s===6)return `<div class="do-now">ETAPA 7 • QUESTÕES + RESPOSTAS</div><h2>Treine a forma de escrever</h2>${m.qa.map((q,i)=>`<div class="qa-copy-card"><h3>${i+1}. ${q[0]}</h3><div class="qa-answer"><b>Resposta-modelo:</b><p>${q[1]}</p></div><button class="btn secondary" onclick="copyOabQa(${i})">Copiar</button></div>`).join('')}`;
 if(s===7)return `<div class="do-now">ETAPA 8 • MEMÓRIA ATIVA</div><h2>Feche o texto e responda mentalmente</h2>${m.qa.map((q,i)=>`<details class="flash"><summary>${i+1}. ${q[0]}</summary><p><b>${q[1]}</b></p></details>`).join('')}<div class="callout"><b>Teste final:</b> explique o tema em voz alta em 60 segundos. Se travar, volte ao mapa mental.</div>`;
 return `<div class="donehero"><div class="checkbig">✓</div><h2>Tópico concluído</h2><p>Agora revise com imagem + áudio + recuperação ativa.</p>${oabMap(m)}<div class="master-finish-actions"><button class="btn good" onclick="generateUniversalPDF()">🎨 Baixar mapa mental colorido</button><button class="btn secondary" onclick="speakStudySummary()">🎧 Ouvir voz feminina natural</button><button class="btn secondary" onclick="downloadMasterAudio()">↓ Baixar áudio</button>${mastery.oab.module<OAB_MODULES.length-1?`<button class="btn good" onclick="finishOabModule()">${u.trial?.paid?'Próximo tópico →':'Liberar plano completo →'}</button>`:''}</div></div>`;
}
function copyMasterPiece(){navigator.clipboard?.writeText(oabCurrent().piece).then(()=>alert('Peça copiada. Agora tente reescrever a estrutura sem olhar.'));}
function copyOabQa(i){const q=oabCurrent().qa?.[i];if(!q)return;navigator.clipboard?.writeText(`Pergunta: ${q[0]}\nResposta: ${q[1]}`).then(()=>alert('Pergunta e resposta copiadas.'));}
function ensureMasterModal(){if(document.getElementById('masterModal'))return;const el=document.createElement('div');el.id='masterModal';el.className='law-reader-modal';el.hidden=true;el.innerHTML=`<div class="law-reader-backdrop" onclick="closeMasterModal()"></div><section class="law-reader-sheet master-sheet"><div class="law-reader-head"><div><span class="pill">DENTRO DO APROVA</span><h2 id="masterModalTitle"></h2></div><button class="law-reader-close" onclick="closeMasterModal()">×</button></div><div id="masterModalBody"></div><div class="law-reader-footer"><button class="btn good" onclick="closeMasterModal()">Voltar ao estudo</button></div></section>`;document.body.appendChild(el);}
function openMasterPiece(){ensureMasterModal();const m=oabCurrent(),el=document.getElementById('masterModal');document.getElementById('masterModalTitle').textContent=m.pieceTitle;document.getElementById('masterModalBody').innerHTML=`<div class="copy-model fullscreen"><pre>${escM(m.piece)}</pre></div><button class="btn good full" onclick="copyMasterPiece()">Copiar peça</button>`;el.hidden=false;document.body.classList.add('modal-open');}
function closeMasterModal(){const el=document.getElementById('masterModal');if(el)el.hidden=true;document.body.classList.remove('modal-open');}

function contestState(){const d=ensureDay();if(!Number.isInteger(d.masterStage))d.masterStage=0;d.masterAnswers=d.masterAnswers||{};return d;}
function setContestStage(s){const d=contestState();d.masterStage=Math.max(0,Math.min(7,s));aesave();renderMasterAll();window.scrollTo({top:0,behavior:'smooth'});}
function masterAnswer(qidx,i){const d=contestState();d.masterAnswers[qidx]=i;aesave();renderMasterAll();}
function contestCanNext(){const d=contestState();if(d.masterStage===2&&d.masterAnswers[0]===undefined)return false;if(d.masterStage===4&&d.masterAnswers[1]===undefined)return false;return d.masterStage<7;}
function contestNav(){const d=contestState(),s=d.masterStage;return `<div class="master-nav"><button class="btn secondary" ${s<=0?'disabled':''} onclick="setContestStage(${s-1})">← Voltar</button><span>${s+1}/8</span><button class="btn good" ${contestCanNext()?'':'disabled'} onclick="setContestStage(${s+1})">Continuar →</button></div>`;}
function contestMap(sub){const bm=bancaMethod();const arr=[['REGRA',sub.keywords?.[0]||'conceito'],['BANCA',bm.name],['PEGADINHA',sub.keywords?.[1]||'exceção'],['QUESTÃO',sub.questions?.[0]?.q?.slice(0,38)||'aplicação'],['REVISÃO','24h • 3d • 7d']];return `<div class="brain-map"><div class="brain-center"><small>MAPA MENTAL</small><b>${sub.name}</b></div>${arr.map((b,i)=>`<div class="brain-branch b${i+1}"><span>${i+1}</span><b>${escM(b[0])}</b><small>${escM(b[1])}</small></div>`).join('')}</div>`;}
function contestStageHtml(){const d=contestState(),sub=currentSubject(),s=d.masterStage,bm=bancaMethod();
 if(s===0)return `${startSubjectChooser()}<div class="do-now">AULA EXPRESSA • ETAPA 1</div><h2>${sub.icon} ${sub.name} — entenda antes de decorar</h2><div class="master-lesson"><div class="sticker">💡</div><div><b>Em linguagem simples</b><p>${sub.summary}</p></div></div><p><b>Palavras-âncora:</b> ${(sub.keywords||[]).join(' • ')}</p>`;
 if(s===1)return `<div class="do-now">ETAPA 2 • COMO A BANCA COBRA</div><h2>${bm.name}: o que observar</h2><div class="banca-card"><div class="sticker">🎯</div><p>${bm.tip}</p></div><div class="writing-road"><div><span>1</span><b>Leia</b><small>descubra o comando</small></div><div><span>2</span><b>Regra</b><small>qual conceito resolve?</small></div><div><span>3</span><b>Exceção</b><small>há “salvo”, “exceto”?</small></div><div><span>4</span><b>Marque</b><small>só depois de eliminar</small></div></div>`;
 if(s===2){const q=sub.questions[0],sel=d.masterAnswers[0];return `<div class="do-now">ETAPA 3 • QUESTÃO 1</div><h2>${q.q}</h2><div class="choice-grid">${q.choices.map((c,i)=>`<button class="choice ${sel===i?'selected':''}" onclick="masterAnswer(0,${i})">${c}</button>`).join('')}</div>`;}
 if(s===3){const q=sub.questions[0],sel=d.masterAnswers[0],ok=sel===q.ok;return `<div class="do-now">ETAPA 4 • CORREÇÃO IMEDIATA</div><h2>${ok?'✅ Acertou':'❌ Corrija agora'}</h2><div class="answer-feedback ${ok?'feedback-ok':'feedback-bad'}"><b>Resposta:</b> ${q.choices[q.ok]}<br><br>${q.why}</div><div class="callout"><b>Transforme em regra:</b> explique com suas palavras por que a alternativa correta está certa e por que a escolhida estaria errada.</div>`;}
 if(s===4){const q=sub.questions[1],sel=d.masterAnswers[1];return `<div class="do-now">ETAPA 5 • QUESTÃO 2</div><h2>${q.q}</h2><div class="choice-grid">${q.choices.map((c,i)=>`<button class="choice ${sel===i?'selected':''}" onclick="masterAnswer(1,${i})">${c}</button>`).join('')}</div>`;}
 if(s===5){const q=sub.questions[1],sel=d.masterAnswers[1],ok=sel===q.ok;return `<div class="do-now">ETAPA 6 • CORREÇÃO + PADRÃO</div><h2>${ok?'✅ Acertou':'❌ Ajuste o raciocínio'}</h2><div class="answer-feedback ${ok?'feedback-ok':'feedback-bad'}"><b>Resposta:</b> ${q.choices[q.ok]}<br><br>${q.why}</div><p><b>Padrão da banca:</b> ${bm.tip}</p>`;}
 if(s===6)return `<div class="do-now">ETAPA 7 • MAPA MENTAL + FLASHCARDS</div><h2>Transforme texto em associação</h2>${contestMap(sub)}<div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash"><small>FIGURINHA ${i+1}</small><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div>`;
 return `<div class="donehero"><div class="checkbig">✓</div><h2>${sub.name} concluído</h2><p>Feche com revisão visual e auditiva. O erro volta antes; o acerto fácil ganha intervalo maior.</p>${contestMap(sub)}<div class="master-finish-actions"><button class="btn good" onclick="generateUniversalPDF()">🎨 Mapa mental colorido</button><button class="btn secondary" onclick="speakStudySummary()">🎧 Ouvir voz feminina natural</button><button class="btn secondary" onclick="downloadMasterAudio()">↓ Baixar áudio</button><button class="btn good" onclick="completeMasterSubject()">Próxima matéria →</button></div></div>`;
}
function completeMasterSubject(){const d=contestState(),sub=currentSubject();const a=d.masterAnswers||{};[0,1].forEach(qidx=>{if(a[qidx]!==undefined){const q=sub.questions[qidx];updatePerf(a[qidx]===q.ok);}});d.masterStage=0;d.masterAnswers={};aesave();nextSubject();}

let masteryAudio=null;
function masterAudioPath(){if(isOabMastery()){const idx=Math.max(0,Math.min(9,mastery.oab.module));const dates=['2026-10-06','2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11','2026-10-12','2026-10-13','2026-10-14','2026-10-17'];return `audio/oab/${dates[idx]}.mp3`;}return `audio/subjects/${currentSubjectKey()}.mp3`;}
window.speakStudySummary=function(){try{if(masteryAudio){masteryAudio.pause();masteryAudio=null;}masteryAudio=new Audio(masterAudioPath());masteryAudio.play().catch(()=>alert('Toque novamente no botão de áudio para iniciar a reprodução.'));}catch(e){alert('Não foi possível iniciar o áudio agora.');}};
window.stopStudyAudio=function(){if(masteryAudio){masteryAudio.pause();masteryAudio.currentTime=0;}};
window.downloadMasterAudio=function(){const a=document.createElement('a');a.href=masterAudioPath();a.download=isOabMastery()?`aprova-oab-${oabCurrent().tag}.mp3`:`aprova-${currentSubjectKey()}.mp3`;document.body.appendChild(a);a.click();a.remove();};

function drawSticker(doc,x,y,label,color){doc.setFillColor(...color);doc.circle(x,y,7,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(6.5);doc.text(label,x,y+2,{align:'center'});}
window.generateUniversalPDF=function(){
 if(!(window.jspdf&&window.jspdf.jsPDF))return alert('Gerador carregando. Tente novamente em instantes.');
 const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),W=297,H=210,cx=148.5,cy=98;
 const colors=[[31,111,235],[23,135,77],[226,151,40],[137,83,180],[22,151,171],[203,74,74]];
 const wrap=(txt,w)=>doc.splitTextToSize(String(txt||''),w);
 const title=isOabMastery()?oabCurrent().title:currentSubject().name;
 const branches=isOabMastery()?oabCurrent().branches:[['REGRA',currentSubject().summary],['BANCA',bancaMethod().name+' — '+bancaMethod().tip],['QUESTÃO 1',currentSubject().questions[0].why],['QUESTÃO 2',currentSubject().questions[1].why],['FLASHCARD',currentSubject().flash[0][0]+' — '+currentSubject().flash[0][1]],['REVISÃO','24 horas • 3 dias • 7 dias']];
 doc.setFillColor(244,247,251);doc.rect(0,0,W,H,'F');doc.setTextColor(15,39,71);doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('APROVA • MAPA MENTAL VISUAL',14,14);doc.setFontSize(9);doc.setTextColor(100,116,139);doc.text(targetName(),14,21);
 const pos=[[10,34,83,43],[204,34,83,43],[10,125,83,45],[204,125,83,45],[104,156,89,39],[104,28,89,39]];
 branches.slice(0,6).forEach((b,i)=>{const [x,y,w,h]=pos[i],c=colors[i];doc.setDrawColor(...c);doc.setLineWidth(1.2);doc.line(cx,cy,x+w/2,y+h/2);doc.setFillColor(255,255,255);doc.roundedRect(x,y,w,h,5,5,'F');doc.setDrawColor(...c);doc.roundedRect(x,y,w,h,5,5,'S');drawSticker(doc,x+9,y+9,String(i+1),c);doc.setTextColor(20,38,59);doc.setFont('helvetica','bold');doc.setFontSize(9.5);doc.text(String(b[0]).slice(0,30),x+18,y+8);doc.setFont('helvetica','normal');doc.setTextColor(77,94,113);doc.setFontSize(7.3);doc.text(wrap(b[1],w-8).slice(0,5),x+4,y+15);});
 doc.setFillColor(15,39,71);doc.roundedRect(cx-38,cy-19,76,38,8,8,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('TEMA CENTRAL',cx,cy-6,{align:'center'});doc.setFontSize(11);doc.text(wrap(title,66).slice(0,3),cx,cy+2,{align:'center'});
 doc.setFillColor(255,245,204);doc.setDrawColor(225,174,46);doc.roundedRect(14,183,80,15,5,5,'FD');doc.setTextColor(105,75,0);doc.setFontSize(8);doc.text('FIGURINHA: explique sem olhar em 60 s',54,192.5,{align:'center'});
 doc.setFillColor(231,247,238);doc.setDrawColor(23,135,77);doc.roundedRect(203,183,80,15,5,5,'FD');doc.setTextColor(23,95,58);doc.text('REVISÃO: erro volta antes • acerto espaça',243,192.5,{align:'center'});
 // second page: colorful cards
 doc.addPage('a4','portrait');doc.setFillColor(247,249,252);doc.rect(0,0,210,297,'F');doc.setTextColor(15,39,71);doc.setFontSize(18);doc.text('Cards de revisão',14,17);doc.setFontSize(9);doc.setTextColor(100,116,139);doc.text(title,14,24);let y=32;
 branches.slice(0,6).forEach((b,i)=>{const c=colors[i],lines=wrap(b[1],170),h=Math.max(28,17+lines.length*4.4);if(y+h>282){doc.addPage('a4','portrait');doc.setFillColor(247,249,252);doc.rect(0,0,210,297,'F');y=18;}doc.setFillColor(255,255,255);doc.setDrawColor(...c);doc.roundedRect(14,y,182,h,5,5,'FD');doc.setFillColor(...c);doc.roundedRect(14,y,182,10,5,5,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text(`${i+1} • ${b[0]}`,19,y+6.8);doc.setTextColor(35,50,68);doc.setFont('helvetica','normal');doc.setFontSize(8.2);doc.text(lines,19,y+17);y+=h+7;});
 doc.save(`aprova-mapa-mental-${isOabMastery()?'oab':currentSubjectKey()}.pdf`);
};

function renderOabMasteryToday(){const m=oabCurrent();return `<div class="master-head"><div><span class="pill">MODO OAB • APRENDIZADO ACELERADO</span><h2>${mastery.oab.module+1}/${OAB_MODULES.length} • ${m.title}</h2><p class="muted">Estudo → lei → mapa mental → caso OAB → peça pronta → escrita → questões → memória → resumo.</p></div><div class="kpi">${mastery.oab.stage+1}<small>etapa de 9</small></div></div><div class="oab-module-strip">${OAB_MODULES.map((x,i)=>`<button class="module-chip ${i===mastery.oab.module?'active':''} ${i>0&&!u.trial?.paid?'locked':''}" onclick="setOabModule(${i})">${i>0&&!u.trial?.paid?'🔒 ':''}${i+1}. ${x.tag}</button>`).join('')}</div><div class="card master-main">${oabStageHtml()}${oabNav()}</div>`;}
function renderContestMasteryToday(){const d=contestState(),sub=currentSubject();return `<div class="master-head"><div><span class="pill">MODO CONCURSO • APRENDIZADO ACELERADO</span><h2>${u.profile.hours||2}h/dia • ${sub.name}</h2><p class="muted">O sistema escolhe a prioridade pelo cargo, banca e seus erros. Você aprende por explicação, questões, mapa mental, áudio e revisão.</p></div><div class="kpi">${d.index+1}/${d.queue.length}<small>bloco atual</small></div></div><div class="guide-layout"><div class="card master-main">${contestStageHtml()}${contestNav()}</div><aside class="card guide-side"><h3>Fila inteligente de hoje</h3>${d.queue.map((k,i)=>{const x=SUBJECTS[k];return `<div class="queue-item ${i===d.index?'queue-active':''} ${i<d.index?'queue-done':''}"><span class="queue-dot" style="background:${x.color}"></span><span><b>${x.name}</b><small>${x.minutes} min</small></span>${i<d.index?'✓':i===d.index?'AGORA':''}</div>`}).join('')}<hr><h3>Método da banca</h3><p class="muted">${bancaMethod().tip}</p></aside></div>`;}

function renderMasterToday(){document.getElementById('hoje').innerHTML=isOabMastery()?renderOabMasteryToday():renderContestMasteryToday();}
function renderMasterContent(){const el=document.getElementById('pecas');if(!el)return;if(isOabMastery()){el.innerHTML=`<div class="card"><span class="pill">PEÇAS E GATILHOS</span><h2>Mapa completo de reconhecimento</h2><div class="history-grid">${OAB_MODULES.map((m,i)=>`<button class="master-topic-card" onclick="setOabModule(${i});document.querySelector('[data-tab=hoje]')?.click()"><b>${m.tag}</b><span>${m.title}</span><small>${m.hook}</small></button>`).join('')}</div></div>`;}else{const sorted=Object.keys(weightsForUser()).filter(k=>SUBJECTS[k]);el.innerHTML=`<div class="card"><span class="pill">MAPA DO EDITAL</span><h2>O que o sistema vai dominar com você</h2><p class="muted">Cada matéria passa pelo mesmo ciclo: explicação → padrão da banca → 2 questões → correção → mapa mental → áudio → revisão.</p><div class="history-grid">${sorted.map(k=>`<div class="master-topic-card static"><b>${SUBJECTS[k].icon} ${SUBJECTS[k].name}</b><span>${SUBJECTS[k].summary}</span><small>Palavras-âncora: ${SUBJECTS[k].keywords.join(' • ')}</small></div>`).join('')}</div></div>`;}}
function renderMasterMaterial(){const el=document.getElementById('vade');if(!el)return;if(isOabMastery()){const m=oabCurrent();el.innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">LEI DENTRO DO APROVA</span><h2>${m.title}</h2><div class="law-card-grid">${m.law.map((x,i)=>`<div class="law-study-card"><span>${i+1}</span><div><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}</div></div><div class="card span-4"><h3>Como localizar</h3><p>Assunto → bloco constitucional → artigo → inciso → aplicação ao fato. O objetivo é chegar ao fundamento em segundos.</p></div></div>`;}else{const sub=currentSubject();el.innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">FONTE CERTA NA HORA CERTA</span><h2>${sub.name}</h2><p>${sub.summary}</p><div class="law-card-grid">${sub.keywords.map((k,i)=>`<div class="law-study-card"><span>${i+1}</span><div><b>${k}</b><p>Revise o conceito, a regra, a exceção e um exemplo de cobrança.</p></div></div>`).join('')}</div></div><div class="card span-4"><h3>${bancaMethod().name}</h3><p>${bancaMethod().tip}</p></div></div>`;}}
function renderMasterQuestions(){const el=document.getElementById('questoes');if(!el)return;if(isOabMastery()){const m=oabCurrent();el.innerHTML=`<div class="card"><span class="pill">RESPOSTA NO FORMATO DO ESPELHO</span><h2>Questões do tópico</h2>${m.qa.map((q,i)=>`<div class="qa-copy-card"><h3>${i+1}. ${q[0]}</h3><div class="qa-answer"><b>Resposta-modelo:</b><p>${q[1]}</p></div></div>`).join('')}</div>`;}else{const sub=currentSubject();el.innerHTML=`<div class="card"><span class="pill">TREINO GUIADO</span><h2>${sub.name}</h2>${sub.questions.map((q,i)=>`<div class="qa-copy-card"><h3>${i+1}. ${q.q}</h3><div class="qa-answer"><b>Resposta correta:</b><p>${q.choices[q.ok]}</p><p>${q.why}</p></div></div>`).join('')}</div>`;}}
function renderMasterReview(){const el=document.getElementById('revisao');if(!el)return;const audio=masterAudioPath();if(isOabMastery()){const m=oabCurrent();el.innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">REVISÃO MULTISSENSORIAL</span><h2>${m.title}</h2>${oabMap(m)}<div class="audio-summary-card"><b>🎧 Voz feminina natural</b><audio controls preload="none" src="${audio}"></audio><a class="btn secondary full" href="${audio}" download>Baixar áudio</a></div></div><div class="card span-4"><h3>Feche o ciclo</h3><button class="btn good full" onclick="generateUniversalPDF()">🎨 Mapa mental colorido</button><button class="btn secondary full smallgap" onclick="speakStudySummary()">▶ Ouvir agora</button><p class="muted">Imagem + voz + teste de memória + repetição espaçada.</p></div></div>`;}else{const sub=currentSubject();el.innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">REVISÃO MULTISSENSORIAL</span><h2>${sub.name}</h2>${contestMap(sub)}<div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash"><small>FIGURINHA ${i+1}</small><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div></div><div class="card span-4"><h3>Áudio natural</h3><audio controls preload="none" src="${audio}" style="width:100%"></audio><a class="btn secondary full smallgap" href="${audio}" download>Baixar áudio</a><button class="btn good full smallgap" onclick="generateUniversalPDF()">🎨 Mapa mental colorido</button></div></div>`;}}

const MASTER_SUPPORT_ENDPOINT='https://oab-support-production.up.railway.app';
function ensureMasterSupport(){if(document.getElementById('masterSupport'))return;const el=document.createElement('div');el.id='masterSupport';el.innerHTML=`<button class="support-fab" onclick="openMasterSupport()">💬 <span>Ajuda</span></button><section class="support-panel" hidden><div class="support-head"><div><span class="pill">ATENDIMENTO</span><h3>Encontrou uma falha?</h3></div><button class="support-close" onclick="closeMasterSupport()">×</button></div><p class="support-intro">Explique o problema. O sistema tenta uma correção segura na hora e registra um protocolo técnico.</p><div class="support-quick"><button onclick="quickMasterSupport('Botão não funciona')">Botão</button><button onclick="quickMasterSupport('Tela travou')">Tela travou</button><button onclick="quickMasterSupport('Áudio não funciona')">Áudio</button><button onclick="quickMasterSupport('Conteúdo não carregou')">Conteúdo</button></div><textarea id="masterSupportText" rows="4" placeholder="Descreva o que aconteceu..."></textarea><button class="btn good support-send" onclick="sendMasterSupport()">Diagnosticar</button><div id="masterSupportReply" class="support-reply"></div></section>`;document.body.appendChild(el);}
function openMasterSupport(){document.querySelector('#masterSupport .support-panel').hidden=false;}
function closeMasterSupport(){document.querySelector('#masterSupport .support-panel').hidden=true;}
function quickMasterSupport(t){openMasterSupport();document.getElementById('masterSupportText').value=t;}
async function sendMasterSupport(){const text=document.getElementById('masterSupportText').value.trim(),r=document.getElementById('masterSupportReply');if(!text)return;r.textContent='Analisando…';let ticket='';try{const res=await fetch(MASTER_SUPPORT_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context:{app:'aprova',track:u.profile.track,target:u.profile.target,screen:`${innerWidth}x${innerHeight}`}})});const j=await res.json();ticket=j.ticket||'';}catch{}try{if(/trav|carreg|conteúdo/i.test(text)){if('caches'in window){for(const k of await caches.keys())await caches.delete(k);}renderMasterAll();}if(/áudio|audio/i.test(text)){stopStudyAudio();}if(/botão|botao/i.test(text)){renderMasterAll();}}catch{}r.innerHTML=`<b>Correção segura executada.</b>${ticket?`<br><small>Protocolo: ${escM(ticket)}</small>`:''}`;}


function renderMasterSchedule(){
 if(isOabMastery()){
  const done=Number(mastery.oab.module)||0;
  document.getElementById('cronograma').innerHTML=`<div class="card"><span class="pill">PLANO INTENSIVO OAB</span><h2>10 tópicos para dominar a prova</h2><p class="muted">A sequência segue reconhecimento da peça, base legal, caso real, escrita, questões e revisão. Você pode abrir qualquer tópico.</p>${OAB_MODULES.map((m,i)=>`<button class="day ${i===done?'auto-today':''}" style="width:100%;text-align:left;border:0;cursor:pointer" onclick="setOabModule(${i});document.querySelector('[data-tab=hoje]')?.click()"><div class="date">${String(i+1).padStart(2,'0')}</div><div><b>${m.title}</b><div class="muted">${m.hook}</div></div><span class="module-count">${i<done?'✓':i===done?'AGORA':''}</span></button>`).join('')}</div>`;
  return;
 }
 const left=udays(),weights=weightsForUser(),sorted=Object.entries(weights).filter(([k])=>SUBJECTS[k]).sort((a,b)=>b[1]-a[1]),perf=ae.performance||{},max=sorted[0]?.[1]||1;
 document.getElementById('cronograma').innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">PLANO ADAPTATIVO</span><h2>${left===null?'Calendário aguardando data':`${left} dias até a prova`}</h2><p class="muted">A prioridade muda conforme cargo, banca e seus acertos. Erro aumenta frequência; domínio consistente libera espaço para outras matérias.</p>${sorted.map(([k,v],i)=>{const s=SUBJECTS[k],p=perf[k],rate=p?.total?Math.round(p.correct/p.total*100):null;return `<div class="priority-row"><span class="queue-dot" style="background:${s.color}"></span><b>${s.name}</b><div class="priority-bar"><i style="width:${Math.round(v/max*100)}%;background:${s.color}"></i></div><span>${rate===null?(i<3?'alta':i<6?'média':'apoio'):`${rate}%`}</span></div>`}).join('')}</div><div class="card span-4"><span class="pill">RADAR DE DOMÍNIO</span><h3>${bancaMethod().name}</h3><p>${bancaMethod().tip}</p><hr><h3>Regra do motor</h3><p><b>Errou:</b> volta mais cedo.<br><b>Ficou em dúvida:</b> revisão curta.<br><b>Acertou fácil:</b> intervalo maior.</p><div class="callout"><b>Meta:</b> chegar à prova reconhecendo padrões, não relendo teoria inteira.</div></div></div>`;
}
mastery.sim=mastery.sim||{answers:{}};
function answerMasterSim(i,a){mastery.sim.answers=mastery.sim.answers||{};mastery.sim.answers[i]=a;msave();renderMasterSim();}
function resetMasterSim(){mastery.sim={answers:{}};msave();renderMasterSim();}
function renderMasterSim(){
 if(isOabMastery()){
  document.getElementById('simulados').innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">SIMULADO OAB 2ª FASE</span><h2>Treino de 5 horas</h2><p>15 min de triagem → 2h15 para a peça → 2h para as quatro questões → 30 min de revisão/margem.</p><div class="timer">05:00:00</div><div class="callout"><b>Antes de escrever:</b> competência → legitimidade → cabimento → fundamentos → pedidos.</div><button class="btn good" onclick="setOabModule(8);document.querySelector('[data-tab=hoje]')?.click()">Abrir Simulado Guiado →</button></div><div class="card span-4"><h3>Correção inteligente</h3><p>Compare a peça e cada questão com o espelho. Toda perda vira regra curta, flashcard e revisão.</p><button class="btn secondary full" onclick="generateUniversalPDF()">Gerar mapa mental da revisão</button></div></div>`;
  return;
 }
 const sub=currentSubject(),ans=mastery.sim.answers||{},answered=Object.keys(ans).length,correct=sub.questions.reduce((n,q,i)=>n+(ans[i]===q.ok?1:0),0);
 document.getElementById('simulados').innerHTML=`<div class="grid"><div class="card span-8"><span class="pill">SIMULADO RÁPIDO DO CICLO</span><h2>${sub.icon} ${sub.name}</h2><p class="muted">Duas questões cronometráveis para testar o bloco atual sem consultar. Ao terminar, transforme o erro em revisão.</p>${sub.questions.map((q,i)=>`<div class="qbox"><h3>${i+1}. ${q.q}</h3><div class="choice-grid">${q.choices.map((c,a)=>`<button class="choice ${ans[i]===a?'selected':''}" onclick="answerMasterSim(${i},${a})">${c}</button>`).join('')}</div>${ans[i]!==undefined?`<div class="answer-feedback ${ans[i]===q.ok?'feedback-ok':'feedback-bad'}"><b>${ans[i]===q.ok?'Correto':'Corrija'}:</b> ${q.choices[q.ok]}<br>${q.why}</div>`:''}</div>`).join('')}</div><div class="card span-4"><span class="pill">PLACAR</span><div class="score-ring">${answered?Math.round(correct/answered*100):0}<small>%</small></div><p><b>${correct}</b> acerto(s) em <b>${answered}</b> respondida(s).</p><p class="muted">Quando errar, volte à regra e ao mapa mental antes de repetir.</p><button class="btn secondary full" onclick="resetMasterSim()">Refazer simulado</button><button class="btn good full smallgap" onclick="generateUniversalPDF()">Mapa mental da correção</button></div></div>`;
}
function setMasterNavLabels(){const buttons=[...document.querySelectorAll('.tabs button')];const by=n=>buttons.find(b=>b.dataset.tab===n);if(isOabMastery()){if(by('pecas'))by('pecas').textContent='Peças';if(by('vade'))by('vade').textContent='Vade / Leis';if(by('questoes'))by('questoes').textContent='Espelho / Questões';}else{if(by('pecas'))by('pecas').textContent='Conteúdo';if(by('vade'))by('vade').textContent='Material';if(by('questoes'))by('questoes').textContent='Questões';}}
function renderMasterAll(){setMasterNavLabels();renderMasterToday();renderMasterSchedule();renderMasterContent();renderMasterMaterial();renderMasterQuestions();renderMasterSim();renderMasterReview();uRenderErrors();uCountdown();const p=document.getElementById('progressText');if(p)p.textContent=isOabMastery()?`OAB: tópico ${mastery.oab.module+1}/${OAB_MODULES.length} • etapa ${mastery.oab.stage+1}/9`:`Hoje: bloco ${contestState().index+1}/${contestState().queue.length} • etapa ${contestState().masterStage+1}/8`;}
window.uRenderAll=renderMasterAll;
window.uRenderToday=renderMasterToday;
window.uRenderSchedule=renderMasterSchedule;
window.uRenderSim=renderMasterSim;
window.uRenderContent=renderMasterContent;
window.uRenderMaterial=renderMasterMaterial;
window.uRenderQuestions=renderMasterQuestions;
window.uRenderReview=renderMasterReview;
ensureMasterSupport();
renderMasterAll();
