/* Aprova — motor adaptativo de estudo guiado */
const APROVA_ENGINE_KEY='aprova-guided-engine-v2';
let ae=JSON.parse(localStorage.getItem(APROVA_ENGINE_KEY)||'{}');
ae.day=ae.day||{}; ae.performance=ae.performance||{}; ae.notes=ae.notes||[];
function aesave(){localStorage.setItem(APROVA_ENGINE_KEY,JSON.stringify(ae));}

const SUBJECTS={
 portugues:{name:'Português',color:'#FFE082',icon:'🟡',minutes:25,summary:'Leia primeiro buscando sentido. Depois observe coesão, pontuação e relações sintáticas. A banca costuma testar a diferença entre alternativas muito parecidas.',keywords:['interpretação','pontuação','sentido','sintaxe','coesão'],questions:[
  {q:'Em “Os candidatos que estudam com constância evoluem”, o termo “que” introduz:',choices:['oração subordinada adjetiva','oração subordinada substantiva','oração coordenada','oração reduzida'],ok:0,why:'“Que” retoma “candidatos” e a oração caracteriza esse substantivo: é subordinada adjetiva.'},
  {q:'Em uma oração adjetiva, o uso de vírgulas pode mudar principalmente:',choices:['o alcance restritivo ou explicativo','o tempo verbal','o sujeito para objeto','a voz ativa para passiva'],ok:0,why:'Com vírgulas, a oração tende a ser explicativa; sem elas, pode ser restritiva. Isso altera o sentido.'}
 ],flash:[['O que observar primeiro em Português?','O sentido do texto antes de aplicar a regra.'],['Vírgula em oração adjetiva pode alterar o quê?','O alcance: restritiva x explicativa.']]},
 constitucional:{name:'Direito Constitucional',color:'#90CAF9',icon:'🔵',minutes:25,summary:'Priorize direitos fundamentais, organização do Estado, poderes, administração pública e controle de constitucionalidade. Sempre ligue a regra ao texto constitucional.',keywords:['direitos','constituição','controle','poderes','artigo'],questions:[
  {q:'Quais princípios estão expressos no caput do art. 37 da Constituição?',choices:['Legalidade, impessoalidade, moralidade, publicidade e eficiência','Legalidade, razoabilidade, proporcionalidade, publicidade e eficiência','Moralidade, autotutela, segurança jurídica, publicidade e eficiência','Legalidade, supremacia, motivação, publicidade e eficiência'],ok:0,why:'O art. 37, caput, traz os princípios conhecidos pelo mnemônico LIMPE.'},
  {q:'O mandado de segurança protege, em regra:',choices:['direito líquido e certo não amparado por HC ou HD','qualquer direito sem prova pré-constituída','somente liberdade de locomoção','apenas dados pessoais'],ok:0,why:'O MS exige direito líquido e certo e prova pré-constituída, quando não couber HC ou HD.'}
 ],flash:[['O que significa LIMPE?','Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.'],['Núcleo do mandado de segurança?','Direito líquido e certo + prova pré-constituída.']]},
 administrativo:{name:'Direito Administrativo',color:'#A5D6A7',icon:'🟢',minutes:25,summary:'Concentre-se em atos, poderes, agentes públicos, responsabilidade do Estado, licitações e princípios. Compare conceitos próximos para evitar pegadinhas.',keywords:['atos','poderes','agentes','responsabilidade','licitações'],questions:[
  {q:'A responsabilidade civil do Estado por dano causado por agente público, nessa qualidade, é em regra:',choices:['objetiva, com regresso em caso de dolo ou culpa','subjetiva e sem regresso','objetiva sem excludentes','sempre solidária com o agente'],ok:0,why:'O art. 37, §6º, prevê responsabilidade objetiva do Estado e regresso contra o agente em caso de dolo ou culpa.'},
  {q:'A anulação de um ato administrativo decorre de:',choices:['ilegalidade','mera inconveniência','mudança política','mérito administrativo válido'],ok:0,why:'Anulação corrige ilegalidade. Revogação recai sobre ato válido por conveniência e oportunidade.'}
 ],flash:[['Anulação x revogação?','Anulação: ilegalidade. Revogação: conveniência e oportunidade.'],['Art. 37 §6º: regra?','Responsabilidade objetiva do Estado; regresso com dolo ou culpa.']]},
 penal:{name:'Direito Penal',color:'#EF9A9A',icon:'🔴',minutes:25,summary:'Identifique conduta, elemento subjetivo, resultado e nexo. Depois aplique teoria do crime, concurso de pessoas e regras de pena ao caso.',keywords:['dolo','culpa','crime','tipicidade','pena'],questions:[
  {q:'Crime doloso ocorre quando o agente:',choices:['quer o resultado ou assume o risco de produzi-lo','age sempre sem previsão','não podia prever o resultado','atua apenas com negligência'],ok:0,why:'Dolo envolve vontade do resultado ou assunção do risco de produzi-lo.'},
  {q:'A tentativa exige, em regra:',choices:['início da execução e não consumação por circunstâncias alheias à vontade','mera cogitação','preparação sem execução','resultado consumado'],ok:0,why:'A tentativa pressupõe início de execução e interrupção da consumação por circunstâncias alheias à vontade do agente.'}
 ],flash:[['Dolo: duas formas básicas?','Querer o resultado ou assumir o risco.'],['Tentativa exige o quê?','Início da execução + não consumação por circunstâncias alheias.']]},
 processopenal:{name:'Processo Penal',color:'#CE93D8',icon:'🟣',minutes:25,summary:'Priorize inquérito, ação penal, provas, prisões, competência, procedimentos e nulidades. Procure sempre quem pratica o ato e em qual fase.',keywords:['inquérito','prova','prisão','competência','ação'],questions:[
  {q:'No sistema acusatório, a função de acusar é separada da função de:',choices:['julgar','legislar','defender somente','administrar'],ok:0,why:'A separação entre acusação e julgamento é elemento central do sistema acusatório.'},
  {q:'A cadeia de custódia busca principalmente:',choices:['preservar a rastreabilidade do vestígio','substituir a perícia','dispensar documentação','eliminar contraditório'],ok:0,why:'A cadeia de custódia documenta e preserva o caminho do vestígio.'}
 ],flash:[['Finalidade da cadeia de custódia?','Preservar e documentar a rastreabilidade do vestígio.'],['Sistema acusatório separa quais funções?','Acusar e julgar.']]},
 informatica:{name:'Informática',color:'#80CBC4',icon:'🟦',minutes:25,summary:'Foque em segurança, internet, sistemas operacionais, suítes e redes. A banca costuma trocar conceitos próximos para induzir erro.',keywords:['segurança','rede','sistema','internet','autenticação'],questions:[
  {q:'Qual medida reduz o impacto do comprometimento de uma senha?',choices:['autenticação multifator','reutilização da senha','desativar atualizações','compartilhar credenciais'],ok:0,why:'MFA exige um fator adicional e reduz o risco de uma senha isolada comprometida.'},
  {q:'Phishing é normalmente uma tentativa de:',choices:['enganar o usuário para obter dados ou induzir ação maliciosa','aumentar velocidade da rede','criptografar backup legítimo','atualizar o sistema'],ok:0,why:'Phishing explora engenharia social para roubar informações ou induzir cliques/ações.'}
 ],flash:[['MFA serve para quê?','Adicionar fatores de autenticação e reduzir risco de senha comprometida.'],['Phishing explora principalmente o quê?','Engenharia social.']]},
 raciocinio:{name:'Raciocínio Lógico',color:'#FFCC80',icon:'🟠',minutes:25,summary:'Transforme o enunciado em estrutura: proposições, relações, proporções ou contagem. Resolva em etapas e confira antes de marcar.',keywords:['proposição','lógica','proporção','condição','resultado'],questions:[
  {q:'A negação de “Todos os candidatos foram aprovados” é:',choices:['Pelo menos um candidato não foi aprovado','Nenhum candidato foi aprovado','Todos foram reprovados','Alguns foram aprovados'],ok:0,why:'A negação de “todo A é B” é “existe ao menos um A que não é B”.'},
  {q:'Se P é verdadeira e Q é falsa, P ∧ Q é:',choices:['falsa','verdadeira','indeterminada','equivalente a P'],ok:0,why:'A conjunção só é verdadeira quando as duas proposições são verdadeiras.'}
 ],flash:[['Negação de “todos”?','Existe pelo menos um que não.'],['Quando P ∧ Q é verdadeira?','Somente quando P e Q são verdadeiras.']]},
 direitoshumanos:{name:'Direitos Humanos',color:'#F8BBD0',icon:'🌸',minutes:25,summary:'Associe princípios, tratados, sistemas de proteção e direitos fundamentais. Desconfie de afirmações absolutas e de competências trocadas.',keywords:['direitos','tratados','proteção','dignidade','sistema'],questions:[
  {q:'A dignidade da pessoa humana é, na Constituição brasileira:',choices:['fundamento da República','objetivo apenas internacional','direito sem proteção estatal','regra restrita ao processo penal'],ok:0,why:'A dignidade da pessoa humana é fundamento da República, no art. 1º, III.'},
  {q:'Direitos humanos são normalmente compreendidos como:',choices:['universais e interdependentes','restritos a nacionais','aplicáveis só em guerra','exclusivos de tratados regionais'],ok:0,why:'Universalidade e interdependência são características centrais dos direitos humanos.'}
 ],flash:[['Dignidade da pessoa humana na CF?','Fundamento da República — art. 1º, III.'],['Duas características dos direitos humanos?','Universalidade e interdependência.']]},
 legislacao:{name:'Legislação Específica',color:'#B0BEC5',icon:'⚪',minutes:25,summary:'Lei específica costuma ser cobrada na literalidade. Priorize competências, prazos, requisitos, proibições e exceções previstas no edital.',keywords:['prazo','competência','requisito','proibição','exceção'],questions:[
  {q:'Ao estudar legislação específica, qual estratégia tende a ser mais eficiente?',choices:['mapear competências, prazos, requisitos e exceções','decorar a lei inteira sem questões','ignorar palavras de exceção','usar apenas resumos'],ok:0,why:'Bancas exploram detalhes literais, especialmente competências, prazos, requisitos, vedações e exceções.'},
  {q:'Se a questão traz “salvo”, “exceto” ou “ressalvada”, você deve:',choices:['tratar a exceção como ponto crítico','ignorar o termo','considerar sempre a regra geral','pular a questão'],ok:0,why:'Palavras de exceção costumam inverter a regra e são pontos frequentes de pegadinha.'}
 ],flash:[['Quatro alvos da lei seca?','Competências, prazos, requisitos e exceções.'],['Palavras de alerta?','Salvo, exceto, ressalvada, somente, poderá, deverá.']]},
 atualidades:{name:'Atualidades',color:'#FFF59D',icon:'📰',minutes:25,summary:'Conecte fato, contexto, causa, consequência e instituição envolvida. Evite decorar manchetes isoladas.',keywords:['evento','causa','consequência','instituição','contexto'],questions:[
  {q:'Qual é a melhor forma de revisar atualidades?',choices:['ligar fato, contexto, causa e consequência','decorar apenas datas','memorizar manchetes','ler apenas opinião'],ok:0,why:'Questões de atualidades exigem compreensão contextual.'},
  {q:'Uma notícia ganha confiabilidade quando:',choices:['tem fonte identificável e verificável','circula muito em redes sociais','tem título chamativo','não apresenta data'],ok:0,why:'Confiabilidade depende de origem verificável, contexto, data e confirmação.'}
 ],flash:[['Como memorizar atualidades?','Fato + contexto + causa + consequência.'],['O que aumenta a confiabilidade?','Fonte identificável e verificável.']]}
};

const PROFILES={
 police:{portugues:18,penal:18,processopenal:18,constitucional:12,administrativo:10,direitoshumanos:9,informatica:7,raciocinio:5,legislacao:14},
 tribunal:{portugues:20,constitucional:15,administrativo:15,raciocinio:10,informatica:10,legislacao:15,direitoshumanos:5},
 fiscal:{portugues:10,constitucional:10,administrativo:10,raciocinio:18,informatica:8,legislacao:20,atualidades:4},
 health:{portugues:8,raciocinio:6,informatica:5,legislacao:18,constitucional:5,administrativo:5,atualidades:8},
 education:{portugues:20,raciocinio:15,atualidades:10,legislacao:15,informatica:8,constitucional:5},
 legal:{constitucional:18,administrativo:15,portugues:12,legislacao:15,direitoshumanos:10,penal:10,processopenal:10},
 general:{portugues:18,constitucional:12,administrativo:12,raciocinio:12,informatica:10,legislacao:14,atualidades:8,direitoshumanos:6}
};

function inferKind(){const t=(u?.profile?.target||'').toLowerCase();if(/pol[ií]cia|investigador|escriv|delegad|guarda|agente/.test(t))return'police';if(/tribunal|trt|tre|trf|judici/.test(t))return'tribunal';if(/sefaz|fiscal|receita|auditor|controladoria|tce|cgu/.test(t))return'fiscal';if(/ebserh|sa[uú]de|enferm|medic|resid[eê]ncia/.test(t))return'health';if(/professor|educa|enem|vestibular/.test(t))return'education';if(/oab|magistr|promotor|defensor|procurador|enam|enac/.test(t))return'legal';return'general';}
function bancaBias(weights){const b=(u?.profile?.banca||'').toLowerCase(),w={...weights};if(b.includes('fgv')){w.portugues=(w.portugues||0)+5;w.constitucional=(w.constitucional||0)+2;}if(b.includes('cebraspe')){w.legislacao=(w.legislacao||0)+3;w.constitucional=(w.constitucional||0)+2;}if(b.includes('aocp')){w.portugues=(w.portugues||0)+3;w.informatica=(w.informatica||0)+2;}if(b.includes('quadrix')){w.portugues=(w.portugues||0)+2;w.legislacao=(w.legislacao||0)+3;}return w;}
function performanceBias(weights){const w={...weights};Object.keys(w).forEach(k=>{const p=ae.performance[k];if(!p)return;const rate=p.total?p.correct/p.total:1;if(rate<.5)w[k]+=8;else if(rate<.7)w[k]+=4;else if(rate>.9)w[k]=Math.max(1,w[k]-2);});return w;}
function weightsForUser(){return performanceBias(bancaBias(PROFILES[inferKind()]||PROFILES.general));}
function dailyBlocks(){const hours=Number(u?.profile?.hours||2);return Math.max(1,Math.floor(hours*60/25));}
function weightedQueue(){const w=weightsForUser(),entries=Object.entries(w).filter(([k,v])=>SUBJECTS[k]&&v>0),scores={};entries.forEach(([k])=>scores[k]=0);const n=dailyBlocks(),out=[],total=entries.reduce((s,x)=>s+x[1],0);for(let i=0;i<n;i++){entries.forEach(([k,v])=>scores[k]+=v);entries.sort((a,b)=>scores[b[0]]-scores[a[0]]);const k=entries[0][0];out.push(k);scores[k]-=total;}return out;}
function engineDayKey(){return typeof localDateKey==='function'?localDateKey():new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());}
function ensureDay(){const today=engineDayKey();if(ae.day.date!==today||!Array.isArray(ae.day.queue)){ae.day={date:today,queue:weightedQueue(),index:0,stage:0,maxStageIndex:0,answer:null,learned:'',learnedScore:null,startedAt:Date.now(),startChosen:false,startSubjectKey:'',sessionStats:{correct:0,total:0,streak:0,bestStreak:0},sessionSeen:{}};aesave();}const seq=[0,1,3,4,5,6,7,8,9,10],idx=Math.max(0,seq.indexOf(ae.day.stage||0));if(!Number.isInteger(ae.day.maxStageIndex))ae.day.maxStageIndex=idx;else ae.day.maxStageIndex=Math.max(ae.day.maxStageIndex,idx);ae.day.answers=ae.day.answers||{};ae.day.results=ae.day.results||{};ae.day.sessionStats=ae.day.sessionStats||{correct:0,total:0,streak:0,bestStreak:0};ae.day.sessionSeen=ae.day.sessionSeen||{};return ae.day;}
function currentSubjectKey(){const d=ensureDay();return d.queue[Math.min(d.index,d.queue.length-1)]||'portugues';}
function currentSubject(){return SUBJECTS[currentSubjectKey()]||SUBJECTS.portugues;}
function startChoiceKeys(){const d=ensureDay();return [...new Set(d.queue.slice(d.index))].filter(k=>SUBJECTS[k]);}
window.chooseStartSubject=function(k){const d=ensureDay();if(d.index!==0||Number(d.stage||0)!==0||!SUBJECTS[k])return;const pos=d.queue.indexOf(k,d.index);if(pos<0)return;const picked=d.queue.splice(pos,1)[0];d.queue.splice(d.index,0,picked);d.startChosen=true;d.startSubjectKey=picked;aesave();uRenderAll();};
function startSubjectChooser(){const d=ensureDay();if(d.index!==0||Number(d.stage||0)!==0)return'';const keys=startChoiceKeys(),active=currentSubjectKey();return `<div class="start-picker"><div class="start-picker-title"><span>1</span><div><b>Por qual matéria você quer começar?</b><small>O sistema definiu o conteúdo do dia. Você escolhe apenas a primeira matéria.</small></div></div><div class="start-choice-grid">${keys.map((k,i)=>{const x=SUBJECTS[k],selected=k===active;return `<button class="start-choice ${selected?'selected':''}" onclick="chooseStartSubject('${k}')"><span class="queue-dot" style="background:${x.color}"></span><span><b>${x.name}</b><small>${x.minutes} min${!d.startChosen&&i===0?' • recomendado':''}</small></span>${selected?'<strong>COMEÇAR</strong>':''}</button>`}).join('')}</div></div>`;}
function updatePerf(ok){const k=currentSubjectKey(),p=ae.performance[k]||{correct:0,total:0};p.total++;if(ok)p.correct++;ae.performance[k]=p;aesave();}
const LEGAL_Q_META={
 constitucional:[
  {basis:'Constituição Federal, art. 37, caput.',simple:'O caput do art. 37 traz expressamente Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência — o mnemônico LIMPE.',bank:'A banca costuma trocar um princípio expresso por um implícito, como razoabilidade, proporcionalidade, autotutela ou segurança jurídica.',trap:'Se aparecer “princípios expressos no caput”, procure exatamente LIMPE.'},
  {basis:'Constituição Federal, art. 5º, LXIX; Lei 12.016/2009, art. 1º.',simple:'O Mandado de Segurança protege direito líquido e certo, demonstrável de plano, quando não for hipótese de habeas corpus ou habeas data.',bank:'A banca costuma misturar MS com HC, HD ou situações que exigem produção de prova.',trap:'MS = direito líquido e certo + prova pré-constituída + ato de autoridade.'}
 ],
 administrativo:[
  {basis:'Constituição Federal, art. 37, § 6º.',simple:'A pessoa jurídica responde objetivamente pelo dano causado por seu agente nessa qualidade. O regresso contra o agente depende de dolo ou culpa.',bank:'A pegadinha é afirmar que a responsabilidade do Estado é subjetiva ou que o regresso independe de culpa/dolo.',trap:'Estado: objetiva. Agente no regresso: dolo ou culpa.'},
  {basis:'Lei 9.784/1999, art. 53; STF, Súmula 473.',simple:'Anulação combate ilegalidade. Revogação atinge ato válido por conveniência e oportunidade.',bank:'É comum inverter anulação e revogação ou dizer que ato ilegal é apenas inconveniente.',trap:'Ilegalidade = anula. Mérito válido = pode revogar.'}
 ],
 penal:[
  {basis:'Código Penal, art. 18, I.',simple:'Há dolo quando o agente quer o resultado ou assume o risco de produzi-lo.',bank:'A banca contrapõe dolo direto, dolo eventual e culpa, alterando vontade, previsão e aceitação do risco.',trap:'Quis ou assumiu o risco = dolo.'},
  {basis:'Código Penal, art. 14, II.',simple:'Tentativa exige início da execução e não consumação por circunstâncias alheias à vontade do agente.',bank:'A banca tenta confundir tentativa com cogitação, atos preparatórios ou desistência voluntária.',trap:'Começou a executar + não consumou por fator externo = tentativa.'}
 ],
 processopenal:[
  {basis:'Código de Processo Penal, art. 3º-A.',simple:'O processo penal tem estrutura acusatória: acusar e julgar são funções separadas.',bank:'A banca testa iniciativa probatória do juiz, separação de funções e limites do sistema acusatório.',trap:'Quem acusa não é quem julga.'},
  {basis:'Código de Processo Penal, arts. 158-A a 158-F, especialmente art. 158-A.',simple:'A cadeia de custódia documenta e preserva a história cronológica do vestígio desde o reconhecimento até o descarte.',bank:'A banca troca rastreabilidade por substituição da perícia, dispensa de documentação ou eliminação do contraditório.',trap:'Cadeia de custódia = rastreabilidade do vestígio.'}
 ],
 direitoshumanos:[
  {basis:'Constituição Federal, art. 1º, III.',simple:'A dignidade da pessoa humana é fundamento da República Federativa do Brasil.',bank:'A banca tenta deslocar a dignidade para objetivo, princípio setorial ou direito restrito a uma área.',trap:'Dignidade = fundamento da República.'},
  {basis:'Declaração Universal dos Direitos Humanos, arts. 1º e 2º; Declaração e Programa de Ação de Viena (1993), item 5.',simple:'Os direitos humanos são universais, indivisíveis, interdependentes e inter-relacionados.',bank:'Desconfie de alternativas que restrinjam direitos humanos a nacionalidade, guerra, região ou tratado específico.',trap:'Universalidade + interdependência são características centrais.'}
 ]
};
function isLegalSubjectKey(k=currentSubjectKey()){return ['constitucional','administrativo','penal','processopenal','direitoshumanos','legislacao'].includes(k);}
function legalQuestionMeta(k,idx){if(k==='legislacao')return {basis:'Use a lei específica indicada no edital. O artigo depende da norma cobrada na questão.',simple:'Em legislação específica, identifique competência, prazo, requisito, proibição e exceção diretamente no texto legal aplicável.',bank:'A banca costuma explorar palavras como “salvo”, “exceto”, “ressalvada”, “poderá” e “deverá”.',trap:'Não invente artigo: confirme sempre na lei específica do edital.'};return LEGAL_Q_META[k]?.[idx]||null;}
function recordQuestionPerformance(source,qidx,ok){const d=ensureDay(),key=`${d.index}:${currentSubjectKey()}:${source}:${qidx}`;if(d.sessionSeen[key])return false;d.sessionSeen[key]=1;updatePerf(ok);const st=d.sessionStats||(d.sessionStats={correct:0,total:0,streak:0,bestStreak:0});st.total++;if(ok){st.correct++;st.streak++;st.bestStreak=Math.max(st.bestStreak||0,st.streak);}else st.streak=0;aesave();return true;}
function performanceSnapshot(){const d=ensureDay(),k=currentSubjectKey(),p=ae.performance[k]||{correct:0,total:0},st=d.sessionStats||{correct:0,total:0,streak:0,bestStreak:0};return {subject:p.total?Math.round(p.correct/p.total*100):0,today:st.total?Math.round(st.correct/st.total*100):0,streak:st.streak||0,best:st.bestStreak||0,correct:p.correct,total:p.total};}
function encouragementText(ok,snap){if(!ok)return snap.today>=70?'Você está mantendo um bom aproveitamento. Corrija esta agora e siga o ritmo.':'Esse erro virou revisão imediatamente — é exatamente assim que o sistema fortalece sua memória.';if(snap.streak>=4)return `🔥 ${snap.streak} acertos seguidos! Você entrou em ritmo forte.`;if(snap.subject>=80)return '🚀 Excelente. Seu domínio desta matéria já está em nível alto nesta sessão.';if(snap.subject>=60)return '👏 Muito bom. Você está consolidando o assunto — continue a sequência.';return '🎉 Parabéns! Mais um acerto registrado. Continue enquanto a memória está ativa.';}
function buildQuestionFeedback(sub,idx,ok,compact=false){const q=sub.questions[idx],snap=performanceSnapshot(),k=currentSubjectKey(),legal=isLegalSubjectKey(k),meta=legalQuestionMeta(k,idx),heading=ok?'🎉 Parabéns! Você acertou.':'❌ Resposta incorreta — vamos fixar a correta.';const stats=`<div class="performance-strip"><div><strong>${snap.subject}%</strong><span>${sub.name}</span></div><div><strong>${snap.today}%</strong><span>hoje</span></div><div><strong>${snap.streak}</strong><span>sequência</span></div></div><div class="accuracy-bar"><i style="width:${snap.today}%"></i></div>`;let detail=`<div class="answer-feedback ${ok?'feedback-ok':'feedback-bad'}"><b>${ok?'Por que está certa':'Resposta correta'}:</b> ${ok?q.why:`${q.choices[q.ok]}<br><br>${q.why}`}</div>`;if(legal&&meta){detail+=`<div class="legal-feedback-grid"><div class="legal-box"><span>⚖️ FUNDAMENTO</span><b>${meta.basis}</b></div><div class="legal-box"><span>🧠 EM LINGUAGEM SIMPLES</span><p>${meta.simple}</p></div><div class="legal-box"><span>🎯 COMO A BANCA COBRA</span><p>${meta.bank}</p></div><div class="legal-box"><span>⚠️ PEGADINHA / GATILHO</span><p>${meta.trap}</p></div></div>`;}else{detail+=`<div class="nonlegal-feedback-grid"><div class="memory-tip"><span>🧠 COMO PENSAR</span><p>${q.why}</p></div><div class="memory-tip"><span>💡 GATILHO DE MEMÓRIA</span><p>${sub.flash?.[idx]?.[1]||sub.keywords?.slice(0,3).join(' • ')||'Explique a regra com suas próprias palavras antes de seguir.'}</p></div></div>`;}return `<div class="instant-result ${ok?'instant-ok':'instant-bad'}"><h3>${heading}</h3><p class="motivation-line">${encouragementText(ok,snap)}</p>${stats}${compact?'':detail}${compact&&ok?`<div class="mini-explain">${q.why}</div>`:compact&&!ok?detail:''}</div>`;}
window.buildQuestionFeedback=buildQuestionFeedback;
window.recordQuestionPerformance=recordQuestionPerformance;
const ENGINE_STAGES=[0,1,3,4,5,6,7,8,9,10];
function engineStageIndex(stage){const i=ENGINE_STAGES.indexOf(stage);return i<0?0:i;}
function markEngineStageReached(stage){const d=ensureDay(),i=engineStageIndex(stage);d.maxStageIndex=Math.max(Number(d.maxStageIndex||0),i);}
function syncEngineAnswer(d,stage){if(stage===1)d.answer=d.answers?.[0]??null;else if(stage===4)d.answer=d.answers?.[1]??null;}
function setEngineStage(s){const d=ensureDay();d.stage=s;syncEngineAnswer(d,s);markEngineStageReached(s);aesave();uRenderToday();}
function answerEngine(i){const d=ensureDay(),qidx=d.stage===4?1:0,q=currentSubject().questions[qidx];d.results=d.results||{};if(d.results[qidx])return;d.answer=i;d.answers=d.answers||{};d.answers[qidx]=i;const ok=i===q.ok;recordQuestionPerformance('engine',qidx,ok);d.results[qidx]={ok,qidx,chosen:i};d.lastResult=d.results[qidx];aesave();uRenderToday();}
function finalizeQuestion(qidx){const d=ensureDay(),chosen=d.answers?.[qidx]??d.answer;if(chosen===null||chosen===undefined)return;d.stage=qidx===0?3:5;markEngineStageReached(d.stage);aesave();uRenderToday();}
function gradeLearned(){const d=ensureDay(),sub=currentSubject(),txt=(document.getElementById('learnedText')?.value||'').trim();if(txt.length<12)return alert('Escreva pelo menos uma frase com suas palavras.');const low=txt.toLowerCase(),hits=sub.keywords.filter(k=>low.includes(k.split(' ')[0]));const score=Math.min(100,35+hits.length*13+(txt.length>80?12:0));d.learned=txt;d.learnedScore=score;ae.notes.unshift({date:new Date().toLocaleDateString('pt-BR'),subject:sub.name,text:txt,score});d.stage=7;markEngineStageReached(7);aesave();uRenderToday();}
function analyticsLeadIdentity(){return {name:u.profile?.name||'',email:u.profile?.email||'',phone:u.profile?.phone||'',marketing_consent:!!u.profile?.marketingConsent};}
function midTrialOffer(){return '';}
function nextSubject(){const d=ensureDay();if(d.index===0&&!u.trial?.paid){const firstComplete=!u.trial.firstStageCompleted;u.trial.firstStageCompleted=true;usave();if(firstComplete){if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('FreeStageComplete',{content_name:'Aprova - primeira etapa gratuita'});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('free_stage_complete',analyticsLeadIdentity());}if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('paywall_view',analyticsLeadIdentity());const pw=document.getElementById('paywall');if(pw)pw.hidden=false;return;}d.index++;d.stage=0;d.maxStageIndex=0;d.answer=null;d.answers={};d.results={};d.learned='';d.learnedScore=null;aesave();uRenderAll();window.scrollTo({top:0,behavior:'smooth'});}
function restartTodayPlan(){ae.day={};aesave();ensureDay();uRenderAll();}

window.startFreeTrial=function(){
 const params=new URLSearchParams(location.search);
 const requested=params.get('track');
 const allowed=new Set(['concurso','oab2','oab1','magistratura','saude','educacao','certificacao','outro']);
 const old=u.profile||{};
 const track=allowed.has(requested)?requested:(old.track||'concurso');
 const firstPreview=!u.trial?.previewStartedAt;
 u.profile={...old,track,target:old.target||trackLabels[track],area:track==='oab2'?'constitucional':(old.area||'geral'),hours:Number(old.hours||2),name:old.name||'',email:old.email||'',phone:old.phone||'',marketingConsent:!!old.marketingConsent,banca:old.banca||''};
 u.sessionLoggedOut=false;u.trial.startedAt=u.trial.startedAt||Date.now();u.trial.previewStartedAt=u.trial.previewStartedAt||Date.now();u.trial.mode='first-stage';
 if(firstPreview){u.trial.firstStageCompleted=false;u.trial.leadCaptured=!!old.phone;ae.day={};if(typeof mastery!=='undefined'&&mastery?.oab)mastery.oab.stage=0;if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('StartTrialPreview',{content_name:'Aprova - inicio do teste',content_category:track});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_preview_start',{track,target:u.profile.target});}
 usave();aesave();const gate=document.getElementById('trialGate');if(gate)gate.hidden=true;uRenderAll();if(typeof renderMasterAll==='function')renderMasterAll();const welcome=document.getElementById('trialWelcome');if(welcome)welcome.hidden=false;window.scrollTo({top:0,behavior:'smooth'});
};
window.continueTrialWelcome=function(){const welcome=document.getElementById('trialWelcome');if(welcome)welcome.hidden=true;if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_welcome_continue',{track:u.profile?.track||'',target:u.profile?.target||''});window.scrollTo({top:0,behavior:'smooth'});};

window.requireTrialLeadCapture=function(flow,nextStage){
 if(u.trial?.paid||u.trial?.leadCaptured)return false;
 u.trial.pendingLeadFlow=flow||'contest';u.trial.pendingLeadStage=Number(nextStage)||3;usave();
 const gate=document.getElementById('leadGate');if(!gate)return false;
 const p=document.getElementById('leadPhone');if(p)p.value=(u.profile?.phone||'').replace(/^\+55/,'');
 gate.hidden=false;
 if(!u.trial.leadGateTracked){u.trial.leadGateTracked=true;usave();if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('LeadGateView',{content_name:'Aprova - tres etapas concluidas'});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('lead_gate_view',{track:u.profile?.track||'',target:u.profile?.target||'',after_steps:3});}
 return true;
};
window.closeTrialLead=function(){const gate=document.getElementById('leadGate');if(gate)gate.hidden=true;};
window.captureTrialLead=function(){
 const phoneRaw=(document.getElementById('leadPhone')?.value||'').trim(),digits=phoneRaw.replace(/\D/g,''),national=digits.replace(/^55(?=\d{10,11}$)/,''),phone='+55'+national;
 if(national.length<10||national.length>11)return alert('Informe um WhatsApp válido com DDD.');
 u.profile={...(u.profile||{}),phone,email:u.profile?.email||'',hours:Number(u.profile?.hours||2),marketingConsent:false};u.trial.leadCaptured=true;u.trial.leadCapturedAt=u.trial.leadCapturedAt||Date.now();
 const flow=u.trial.pendingLeadFlow||'contest',next=Number(u.trial.pendingLeadStage)||3;delete u.trial.pendingLeadFlow;delete u.trial.pendingLeadStage;
 if(!u.trial.leadEventTracked){u.trial.leadEventTracked=true;if(typeof window.aprovaTrack==='function'){window.aprovaTrack('Lead',{content_name:'Aprova - WhatsApp apos 3 etapas',content_category:u.profile?.track||''});window.aprovaTrack('CompleteRegistration',{content_name:'Aprova - teste continuado',content_category:u.profile?.track||'',status:true});}if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_lead',{...analyticsLeadIdentity(),track:u.profile?.track||'',target:u.profile?.target||'',after_steps:3});}
 usave();const gate=document.getElementById('leadGate');if(gate)gate.hidden=true;
 if(flow==='oab'&&typeof setOabStage==='function')setOabStage(next);else if(flow==='contest'&&typeof setContestStage==='function')setContestStage(next);else if(typeof setEngineStage==='function')setEngineStage(next);
};

function summaryStep(sub){return `<div class="do-now">BLOCO ${ensureDay().index+1} DE ${ensureDay().queue.length} • ${sub.icon} ${sub.name}</div><h2>Resumo de 30 segundos</h2><div class="micro-summary" style="border-left-color:${sub.color}">${sub.summary}</div><p class="muted">Leia uma vez. O objetivo agora é usar a informação numa questão.</p><button class="btn good nextbtn" onclick="setEngineStage(1)">Ir para a questão →</button>`;}
function questionStep(sub,idx){const d=ensureDay(),q=sub.questions[idx],selected=d.answers?.[idx]??d.answer,result=d.results?.[idx];return `<div class="do-now">QUESTÃO ${idx+1} DE 2 • ${sub.name}</div><h2>${q.q}</h2><div class="choice-grid">${q.choices.map((c,i)=>`<button class="choice ${selected===i?'selected':''} ${result?(i===q.ok?'choice-correct':selected===i?'choice-wrong':'choice-locked'):''}" ${result?'disabled':''} onclick="answerEngine(${i})">${c}</button>`).join('')}</div>${result?buildQuestionFeedback(sub,idx,result.ok,true):''}${result?`<button class="btn good nextbtn" onclick="finalizeQuestion(${idx})">Continuar →</button>`:'<p class="muted center">Toque em uma alternativa para receber a correção imediatamente.</p>'}`;}
function feedbackStep(sub,idx,next){const d=ensureDay(),result=d.results?.[idx]||d.lastResult,ok=!!result?.ok,offer=idx===0?midTrialOffer(d,next):'';return `<div class="do-now">CORREÇÃO + FIXAÇÃO</div>${buildQuestionFeedback(sub,idx,ok,false)}<p class="muted">A correção imediata evita consolidar uma resposta errada e transforma o erro em pista de memória.</p>${offer||`<button class="btn good nextbtn" onclick="setEngineStage(${next})">${idx===0?'Próxima questão':'Continuar'} →</button>`}`;}
function htmlEsc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function learnedStep(sub){const d=ensureDay();return `<div class="do-now">RECUPERAÇÃO ATIVA • ${sub.name}</div><h2>Escreva o que você aprendeu</h2><p class="muted">Sem copiar. Explique como se estivesse ensinando alguém em 2 ou 3 frases.</p><textarea id="learnedText" rows="5" placeholder="Hoje eu aprendi que...">${htmlEsc(d.learned||'')}</textarea><button class="btn good nextbtn" onclick="gradeLearned()">Corrigir meu entendimento →</button>`;}
function learnedFeedback(sub){const d=ensureDay(),score=d.learnedScore||0,missing=sub.keywords.filter(k=>!d.learned.toLowerCase().includes(k.split(' ')[0])).slice(0,3);return `<div class="do-now">CORREÇÃO DO QUE VOCÊ APRENDEU</div><h2>${score>=75?'✅ Boa explicação':score>=55?'🟡 Está no caminho':'🔁 Reforce antes de seguir'}</h2><div class="score-ring">${score}<small>/100</small></div><p><b>Sua explicação:</b> ${d.learned}</p>${missing.length?`<div class="callout"><b>Para ficar mais completa, revise:</b> ${missing.join(', ')}.</div>`:'<div class="callout"><b>Você cobriu os pontos-chave deste bloco.</b></div>'}<button class="btn good nextbtn" onclick="setEngineStage(8)">Fazer perguntas de memória →</button>`;}
function recallStep(sub){return `<div class="do-now">PERGUNTAS DE MEMÓRIA</div><h2>Responda mentalmente antes de abrir</h2>${sub.flash.map((f,i)=>`<details class="flash recall-card"><summary>${i+1}. ${f[0]}</summary><p><b>${f[1]}</b></p></details>`).join('')}<button class="btn good nextbtn" onclick="setEngineStage(9)">Gerar flashcards →</button>`;}
function coloredFlashStep(sub){return `<div class="do-now">FLASHCARDS COLORIDOS</div><h2>Fixação visual</h2><div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash" style="background:${i%2?sub.color:'#FFF59D'}"><small>${sub.icon} ${sub.name}</small><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div><p class="muted">As cores criam pistas visuais para facilitar a recuperação depois.</p><button class="btn good nextbtn" onclick="setEngineStage(10)">Finalizar matéria →</button>`;}
function finishStep(sub){const d=ensureDay(),done=d.index+1>=d.queue.length;return `<div class="donehero"><div class="checkbig">✓</div><h2>${sub.name} concluído</h2><p>${d.index===0&&!u.trial?.paid?'Sua primeira etapa gratuita foi concluída.':'A próxima matéria já foi escolhida automaticamente.'}</p><div class="finish-actions"><button class="btn secondary" onclick="speakStudySummary()">🔊 Ouvir resumo</button><button class="btn secondary" onclick="generateUniversalPDF()">📄 Gerar PDF</button>${done?'<button class="btn good" onclick="restartTodayPlan()">Recalcular novo ciclo</button>':'<button class="btn good" onclick="nextSubject()">Continuar para a próxima matéria →</button>'}</div></div>`;}
function engineCanAdvance(){const d=ensureDay(),s=d.stage||0;if(s===1)return d.answers?.[0]!==undefined;if(s===4)return d.answers?.[1]!==undefined;return true;}
function engineNav(){const d=ensureDay(),idx=engineStageIndex(d.stage||0),prev=idx>0,final=idx===ENGINE_STAGES.length-1,nextOk=engineCanAdvance();return `<div class="stage-nav"><button class="stage-arrow" ${prev?'onclick="enginePrevStage()"':'disabled'} aria-label="Voltar para a etapa anterior">← <span>Etapa anterior</span></button><div class="stage-position">${idx+1}/${ENGINE_STAGES.length}</div><button class="stage-arrow stage-arrow-next" ${nextOk?'onclick="engineNextStage()"':'disabled'} aria-label="Seguir para a próxima etapa"><span>${final?'Próxima matéria':'Próxima etapa'}</span> →</button></div>`;}
window.enginePrevStage=function(){const d=ensureDay(),idx=engineStageIndex(d.stage||0);if(idx<=0)return;d.stage=ENGINE_STAGES[idx-1];syncEngineAnswer(d,d.stage);aesave();uRenderToday();window.scrollTo({top:0,behavior:'smooth'});};
window.engineNextStage=function(){const d=ensureDay(),s=d.stage||0;if(s===0)return setEngineStage(1);if(s===1)return finalizeQuestion(0);if(s===3)return setEngineStage(4);if(s===4)return finalizeQuestion(1);if(s===5)return setEngineStage(6);if(s===6)return gradeLearned();if(s===7)return setEngineStage(8);if(s===8)return setEngineStage(9);if(s===9)return setEngineStage(10);return nextSubject();};
window.logoutAprova=function(){if(!confirm('Deseja sair? Seu progresso continuará salvo neste aparelho.'))return;if('speechSynthesis'in window)speechSynthesis.cancel();u.sessionLoggedOut=true;usave();const pw=document.getElementById('paywall');if(pw)pw.hidden=true;const lg=document.getElementById('leadGate');if(lg)lg.hidden=true;const gate=document.getElementById('trialGate');if(gate)gate.hidden=false;window.scrollTo({top:0,behavior:'smooth'});};
function guidedEngineStep(){const d=ensureDay(),sub=currentSubject(),s=d.stage||0;let body;if(s===0)body=summaryStep(sub);else if(s===1)body=questionStep(sub,0);else if(s===3)body=feedbackStep(sub,0,4);else if(s===4)body=questionStep(sub,1);else if(s===5)body=feedbackStep(sub,1,6);else if(s===6)body=learnedStep(sub);else if(s===7)body=learnedFeedback(sub);else if(s===8)body=recallStep(sub);else if(s===9)body=coloredFlashStep(sub);else body=finishStep(sub);return body+engineNav();}

window.speakStudySummary=function(){const sub=currentSubject(),notes=ae.notes.slice(0,4).map(n=>`${n.subject}: ${n.text}`).join('. '),txt=`Resumo de revisão. ${sub.name}. ${sub.summary}. ${sub.flash.map(f=>f[0]+': '+f[1]).join('. ')}. ${notes?'Suas anotações recentes: '+notes:''}`;if(!('speechSynthesis'in window))return alert('Seu navegador não oferece leitura em voz alta.');speechSynthesis.cancel();const ut=new SpeechSynthesisUtterance(txt);ut.lang='pt-BR';ut.rate=.95;speechSynthesis.speak(ut);};
window.stopStudyAudio=function(){if('speechSynthesis'in window)speechSynthesis.cancel();};

window.uRenderToday=function(){const d=ensureDay(),sub=currentSubject();document.getElementById('hoje').innerHTML=`<div class="study-day-head"><div><span class="pill">PLANO AUTOMÁTICO DE HOJE</span><h2>${u.profile.hours||2}h/dia • ${d.queue.length} blocos programados</h2><p class="muted">Banca: <b>${u.profile.banca||'perfil do cargo'}</b> • o sistema escolhe as matérias e você pode escolher por qual começar.</p></div><div class="kpi">${d.index+1}/${d.queue.length}<small>bloco atual</small></div></div><div class="guide-layout"><div class="card guide-main">${startSubjectChooser()}${guidedEngineStep()}</div><aside class="card guide-side"><h3>Matérias de hoje</h3>${d.queue.map((k,i)=>{const x=SUBJECTS[k];return `<div class="queue-item ${i===d.index?'queue-active':''} ${i<d.index?'queue-done':''}"><span class="queue-dot" style="background:${x.color}"></span><span><b>${x.name}</b><small>${x.minutes} min</small></span>${i<d.index?'✓':i===d.index?'AGORA':''}</div>`}).join('')}<hr><p class="muted">Você escolhe a primeira matéria. Depois, o sistema continua a sequência e adapta os próximos ciclos conforme seus erros e acertos.</p><button class="btn secondary full" onclick="speakStudySummary()">🔊 Ouvir revisão</button></aside></div>`;};

window.uRenderSchedule=function(){const left=udays(),w=weightsForUser(),sorted=Object.entries(w).filter(([k])=>SUBJECTS[k]).sort((a,b)=>b[1]-a[1]);const blocks=dailyBlocks();document.getElementById('cronograma').innerHTML=`<div class="card"><div class="auto-calendar-head"><div><h2>Seu calendário automático</h2><p class="muted">${u.profile.hours||2}h por dia • ${blocks} blocos/dia • recalculado conforme desempenho e dias restantes.</p></div><div class="kpi">${left}<small>dias até a prova</small></div></div><h3>Prioridade atual das matérias</h3>${sorted.map(([k,v],i)=>{const s=SUBJECTS[k],mx=sorted[0][1];return `<div class="priority-row"><span class="queue-dot" style="background:${s.color}"></span><b>${s.name}</b><div class="priority-bar"><i style="width:${Math.round(v/mx*100)}%;background:${s.color}"></i></div><span>${i<3?'alta':i<6?'média':'apoio'}</span></div>`}).join('')}<div class="calendar-note">A ordem não é fixa: erros aumentam a frequência da matéria; alto desempenho libera espaço para outras disciplinas.</div></div>`;};

window.uRenderQuestions=function(){const sub=currentSubject(),p=ae.performance;document.getElementById('questoes').innerHTML=`<div class="card"><h2>Questões guiadas pela prioridade</h2><p>Você não precisa escolher um filtro. O sistema entrega a próxima questão conforme cargo, banca e desempenho.</p><div class="qbox"><span class="pill">AGORA</span><h3>${sub.icon} ${sub.name}</h3><p>${sub.summary}</p><button class="btn good" onclick="document.querySelector('[data-tab=&quot;hoje&quot;]')?.click()">Continuar estudo guiado →</button></div><h3>Seu desempenho</h3>${Object.keys(p).length?Object.entries(p).map(([k,x])=>`<div class="priority-row"><span class="queue-dot" style="background:${SUBJECTS[k]?.color||'#ddd'}"></span><b>${SUBJECTS[k]?.name||k}</b><span>${x.correct}/${x.total} acertos</span></div>`).join(''):'<p class="muted">Resolva as primeiras questões para o sistema começar a se adaptar.</p>'}</div>`;};

window.uRenderReview=function(){const notes=ae.notes.slice(0,8),sub=currentSubject();document.getElementById('revisao').innerHTML=`<div class="grid"><div class="card span-8"><h2>Revisão inteligente</h2><p class="muted">Suas próprias explicações viram material de revisão.</p>${notes.length?notes.map(n=>`<div class="note-line"><b>${n.subject}</b> <span class="pill">${n.score}/100</span><br>${n.text}</div>`).join(''):'<div class="callout">Conclua um bloco para criar sua primeira revisão.</div>'}<h3 style="margin-top:18px">Flashcards coloridos do bloco atual</h3><div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash" style="background:${i%2?sub.color:'#FFF59D'}"><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div></div><div class="card span-4"><h3>Leve a revisão com você</h3><button class="btn good full" onclick="generateUniversalPDF()">📄 Gerar resumo em PDF</button><button class="btn secondary full smallgap" onclick="speakStudySummary()">🔊 Ouvir resumo</button><button class="text-btn full" onclick="stopStudyAudio()">Parar áudio</button></div></div>`;};

window.generateUniversalPDF=function(){if(!(window.jspdf&&window.jspdf.jsPDF))return alert('Gerador carregando. Tente novamente em instantes.');const {jsPDF}=window.jspdf,doc=new jsPDF(),d=ensureDay();let y=16;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Resumo de revisão — Aprova',14,y);y+=9;doc.setFontSize(11);doc.text(`${u.profile.target||'Minha prova'} | ${u.profile.hours||2}h/dia`,14,y);y+=10;const used=[...new Set(d.queue.slice(0,Math.min(d.index+1,d.queue.length)))];used.forEach(k=>{const s=SUBJECTS[k];if(y>250){doc.addPage();y=16;}doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(s.name,15,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);const lines=doc.splitTextToSize(s.summary,178);doc.text(lines,15,y);y+=lines.length*4+4;s.flash.forEach(f=>{doc.setFont('helvetica','bold');doc.text('• '+f[0],15,y);y+=4;doc.setFont('helvetica','normal');const a=doc.splitTextToSize(f[1],174);doc.text(a,19,y);y+=a.length*4+3;});});if(ae.notes.length){if(y>230){doc.addPage();y=16;}doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('O que eu aprendi',14,y);y+=7;ae.notes.slice(0,6).forEach(n=>{const t=doc.splitTextToSize(`${n.subject}: ${n.text}`,180);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(t,15,y);y+=t.length*4+4;});}doc.save('aprova-resumo-revisao.pdf');};

const oldSelectCatalogItem=window.selectCatalogItem;
window.selectCatalogItem=function(id){const x=window.aprovaCatalog?.items?.find(i=>i.id===id);if(!x)return oldSelectCatalogItem&&oldSelectCatalogItem(id);u.profile=u.profile||{};u.profile.target=x.title;u.profile.banca=x.banca;u.profile.catalogId=x.id;if(x.exam_date){u.profile.examDate=x.exam_date;universalExam=new Date(x.exam_date+'T13:00:00-03:00');}if(!u.profile.hours)u.profile.hours=2;ae.day={};usave();aesave();uRenderAll();document.querySelector('[data-tab="hoje"]')?.click();};

window.uRenderAll=function(){universalExam=u.profile.examDate?new Date(u.profile.examDate+'T13:00:00-03:00'):null;const title=document.getElementById('areaTitle'),eye=document.getElementById('examEyebrow');if(title)title.textContent=u.profile.target||'Sua próxima aprovação';if(eye)eye.textContent=`${u.profile.banca||trackLabels[u.profile.track]||'PLANO INTELIGENTE'} • ESTUDO GUIADO`;uRenderToday();uRenderSchedule();uRenderContent();uRenderMaterial();uRenderQuestions();uRenderSim();uRenderReview();uRenderErrors();uCountdown();const p=document.getElementById('progressText');if(p){const d=ensureDay();p.textContent=`Hoje: ${Math.min(d.index+1,d.queue.length)}/${d.queue.length} blocos`;}};
if(u?.profile?.name){ensureDay();uRenderAll();}
