/* Aprova — motor adaptativo de estudo guiado */
const APROVA_ENGINE_KEY='aprova-guided-engine-v2';
let ae=JSON.parse(localStorage.getItem(APROVA_ENGINE_KEY)||'{}');
ae.day=ae.day||{}; ae.performance=ae.performance||{}; ae.notes=ae.notes||[];
function aesave(){localStorage.setItem(APROVA_ENGINE_KEY,JSON.stringify(ae));}

const SUBJECTS={
 portugues:{name:'Português',color:'#FFE082',icon:'🟡',minutes:25,summary:'Leia primeiro buscando sentido. Depois observe coesão, pontuação e relações sintáticas. A banca costuma testar a diferença entre alternativas muito parecidas.',keywords:['interpretação','pontuação','sentido','sintaxe','coesão'],questions:[
  {q:'Em “Os candidatos que estudam com constância evoluem”, o termo “que” introduz:',choices:['oração subordinada adjetiva','oração subordinada substantiva','oração coordenada','oração reduzida'],ok:0,why:'“Que” retoma “candidatos” e a oração caracteriza esse substantivo: é subordinada adjetiva.'},
  {q:'Em uma oração adjetiva, o uso de vírgulas pode mudar principalmente:',choices:['o alcance restritivo ou explicativo','o tempo verbal','o sujeito para objeto','a voz ativa para passiva'],ok:0,why:'Com vírgulas, a oração tende a ser explicativa; sem elas, pode ser restritiva. Isso altera o sentido.'}
 ],flash:[['O que observar primeiro em Português?','O sentido do texto antes de aplicar a regra.'],['Vírgula em oração adjetiva pode alterar o quê?','O alcance: restritiva x explicativa.']]},
 constitucional:{name:'Direito Constitucional',color:'#90CAF9',icon:'🔵',minutes:25,summary:'Priorize direitos fundamentais, organização do Estado, poderes, administração pública e controle de constitucionalidade. Sempre ligue a regra ao texto constitucional.',keywords:['direitos','constituição','controle','poderes','artigo'],questions:[
  {q:'Quais princípios estão expressos no caput do art. 37 da Constituição?',choices:['Legalidade, impessoalidade, moralidade, publicidade e eficiência','Legalidade, razoabilidade, proporcionalidade, publicidade e eficiência','Moralidade, autotutela, segurança jurídica, publicidade e eficiência','Legalidade, supremacia, motivação, publicidade e eficiência'],ok:0,why:'O art. 37, caput, traz os princípios conhecidos pelo mnemônico LIMPE.'},
  {q:'O mandado de segurança protege, em regra:',choices:['direito líquido e certo não amparado por HC ou HD','qualquer direito sem prova pré-constituída','somente liberdade de locomoção','apenas dados pessoais'],ok:0,why:'O MS exige direito líquido e certo e prova pré-constituída, quando não couber HC ou HD.'}
 ],flash:[['O que significa LIMPE?','Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.'],['Núcleo do mandado de segurança?','Direito líquido e certo + prova pré-constituída.']]},
 administrativo:{name:'Direito Administrativo',color:'#A5D6A7',icon:'🟢',minutes:25,summary:'Concentre-se em atos, poderes, agentes públicos, responsabilidade do Estado, licitações e princípios. Compare conceitos próximos para evitar pegadinhas.',keywords:['atos','poderes','agentes','responsabilidade','licitações'],questions:[
  {q:'A responsabilidade civil do Estado por dano causado por agente público, nessa qualidade, é em regra:',choices:['objetiva, com regresso em caso de dolo ou culpa','subjetiva e sem regresso','objetiva sem excludentes','sempre solidária com o agente'],ok:0,why:'O art. 37, §6º, prevê responsabilidade objetiva do Estado e regresso contra o agente em caso de dolo ou culpa.'},
  {q:'A anulação de um ato administrativo decorre de:',choices:['ilegalidade','mera inconveniência','mudança política','mérito administrativo válido'],ok:0,why:'Anulação corrige ilegalidade. Revogação recai sobre ato válido por conveniência e oportunidade.'}
 ],flash:[['Anulação x revogação?','Anulação: ilegalidade. Revogação: conveniência e oportunidade.'],['Art. 37 §6º: regra?','Responsabilidade objetiva do Estado; regresso com dolo ou culpa.']]},
 penal:{name:'Direito Penal',color:'#EF9A9A',icon:'🔴',minutes:25,summary:'Identifique conduta, elemento subjetivo, resultado e nexo. Depois aplique teoria do crime, concurso de pessoas e regras de pena ao caso.',keywords:['dolo','culpa','crime','tipicidade','pena'],questions:[
  {q:'Crime doloso ocorre quando o agente:',choices:['quer o resultado ou assume o risco de produzi-lo','age sempre sem previsão','não podia prever o resultado','atua apenas com negligência'],ok:0,why:'Dolo envolve vontade do resultado ou assunção do risco de produzi-lo.'},
  {q:'A tentativa exige, em regra:',choices:['início da execução e não consumação por circunstâncias alheias à vontade','mera cogitação','preparação sem execução','resultado consumado'],ok:0,why:'A tentativa pressupõe início de execução e interrupção da consumação por circunstâncias alheias à vontade do agente.'}
 ],flash:[['Dolo: duas formas básicas?','Querer o resultado ou assumir o risco.'],['Tentativa exige o quê?','Início da execução + não consumação por circunstâncias alheias.']]},
 processopenal:{name:'Processo Penal',color:'#CE93D8',icon:'🟣',minutes:25,summary:'Priorize inquérito, ação penal, provas, prisões, competência, procedimentos e nulidades. Procure sempre quem pratica o ato e em qual fase.',keywords:['inquérito','prova','prisão','competência','ação'],questions:[
  {q:'No sistema acusatório, a função de acusar é separada da função de:',choices:['julgar','legislar','defender somente','administrar'],ok:0,why:'A separação entre acusação e julgamento é elemento central do sistema acusatório.'},
  {q:'A cadeia de custódia busca principalmente:',choices:['preservar a rastreabilidade do vestígio','substituir a perícia','dispensar documentação','eliminar contraditório'],ok:0,why:'A cadeia de custódia documenta e preserva o caminho do vestígio.'}
 ],flash:[['Finalidade da cadeia de custódia?','Preservar e documentar a rastreabilidade do vestígio.'],['Sistema acusatório separa quais funções?','Acusar e julgar.']]},
 informatica:{name:'Informática',color:'#80CBC4',icon:'🟦',minutes:25,summary:'Foque em segurança, internet, sistemas operacionais, suítes e redes. A banca costuma trocar conceitos próximos para induzir erro.',keywords:['segurança','rede','sistema','internet','autenticação'],questions:[
  {q:'Qual medida reduz o impacto do comprometimento de uma senha?',choices:['autenticação multifator','reutilização da senha','desativar atualizações','compartilhar credenciais'],ok:0,why:'MFA exige um fator adicional e reduz o risco de uma senha isolada comprometida.'},
  {q:'Phishing é normalmente uma tentativa de:',choices:['enganar o usuário para obter dados ou induzir ação maliciosa','aumentar velocidade da rede','criptografar backup legítimo','atualizar o sistema'],ok:0,why:'Phishing explora engenharia social para roubar informações ou induzir cliques/ações.'}
 ],flash:[['MFA serve para quê?','Adicionar fatores de autenticação e reduzir risco de senha comprometida.'],['Phishing explora principalmente o quê?','Engenharia social.']]},
 raciocinio:{name:'Raciocínio Lógico',color:'#FFCC80',icon:'🟠',minutes:25,summary:'Transforme o enunciado em estrutura: proposições, relações, proporções ou contagem. Resolva em etapas e confira antes de marcar.',keywords:['proposição','lógica','proporção','condição','resultado'],questions:[
  {q:'A negação de “Todos os candidatos foram aprovados” é:',choices:['Pelo menos um candidato não foi aprovado','Nenhum candidato foi aprovado','Todos foram reprovados','Alguns foram aprovados'],ok:0,why:'A negação de “todo A é B” é “existe ao menos um A que não é B”.'},
  {q:'Se P é verdadeira e Q é falsa, P ∧ Q é:',choices:['falsa','verdadeira','indeterminada','equivalente a P'],ok:0,why:'A conjunção só é verdadeira quando as duas proposições são verdadeiras.'}
 ],flash:[['Negação de “todos”?','Existe pelo menos um que não.'],['Quando P ∧ Q é verdadeira?','Somente quando P e Q são verdadeiras.']]},
 direitoshumanos:{name:'Direitos Humanos',color:'#F8BBD0',icon:'🌸',minutes:25,summary:'Associe princípios, tratados, sistemas de proteção e direitos fundamentais. Desconfie de afirmações absolutas e de competências trocadas.',keywords:['direitos','tratados','proteção','dignidade','sistema'],questions:[
  {q:'A dignidade da pessoa humana é, na Constituição brasileira:',choices:['fundamento da República','objetivo apenas internacional','direito sem proteção estatal','regra restrita ao processo penal'],ok:0,why:'A dignidade da pessoa humana é fundamento da República, no art. 1º, III.'},
  {q:'Direitos humanos são normalmente compreendidos como:',choices:['universais e interdependentes','restritos a nacionais','aplicáveis só em guerra','exclusivos de tratados regionais'],ok:0,why:'Universalidade e interdependência são características centrais dos direitos humanos.'}
 ],flash:[['Dignidade da pessoa humana na CF?','Fundamento da República — art. 1º, III.'],['Duas características dos direitos humanos?','Universalidade e interdependência.']]},
 legislacao:{name:'Legislação Específica',color:'#B0BEC5',icon:'⚪',minutes:25,summary:'Lei específica costuma ser cobrada na literalidade. Priorize competências, prazos, requisitos, proibições e exceções previstas no edital.',keywords:['prazo','competência','requisito','proibição','exceção'],questions:[
  {q:'Ao estudar legislação específica, qual estratégia tende a ser mais eficiente?',choices:['mapear competências, prazos, requisitos e exceções','decorar a lei inteira sem questões','ignorar palavras de exceção','usar apenas resumos'],ok:0,why:'Bancas exploram detalhes literais, especialmente competências, prazos, requisitos, vedações e exceções.'},
  {q:'Se a questão traz “salvo”, “exceto” ou “ressalvada”, você deve:',choices:['tratar a exceção como ponto crítico','ignorar o termo','considerar sempre a regra geral','pular a questão'],ok:0,why:'Palavras de exceção costumam inverter a regra e são pontos frequentes de pegadinha.'}
 ],flash:[['Quatro alvos da lei seca?','Competências, prazos, requisitos e exceções.'],['Palavras de alerta?','Salvo, exceto, ressalvada, somente, poderá, deverá.']]},
 atualidades:{name:'Atualidades',color:'#FFF59D',icon:'📰',minutes:25,summary:'Conecte fato, contexto, causa, consequência e instituição envolvida. Evite decorar manchetes isoladas.',keywords:['evento','causa','consequência','instituição','contexto'],questions:[
  {q:'Qual é a melhor forma de revisar atualidades?',choices:['ligar fato, contexto, causa e consequência','decorar apenas datas','memorizar manchetes','ler apenas opinião'],ok:0,why:'Questões de atualidades exigem compreensão contextual.'},
  {q:'Uma notícia ganha confiabilidade quando:',choices:['tem fonte identificável e verificável','circula muito em redes sociais','tem título chamativo','não apresenta data'],ok:0,why:'Confiabilidade depende de origem verificável, contexto, data e confirmação.'}
 ],flash:[['Como memorizar atualidades?','Fato + contexto + causa + consequência.'],['O que aumenta a confiabilidade?','Fonte identificável e verificável.']]}
  ,constitucionalcivil:{name:'Noções de Direito Constitucional e Direito Civil',color:'#90CAF9',icon:'🔵',minutes:25,summary:'Integre os fundamentos constitucionais cobrados no edital às noções civis exigidas para a atuação pública.',keywords:['constituição','direitos','civil','pessoa','responsabilidade'],questions:[{q:'A dignidade da pessoa humana é, na Constituição Federal:',choices:['fundamento da República','objetivo apenas econômico','competência municipal','regra transitória'],ok:0,why:'A dignidade da pessoa humana é fundamento da República, prevista no art. 1º, III, da CF.'},{q:'A personalidade civil da pessoa começa, em regra:',choices:['com o nascimento com vida','com a maioridade','com o casamento','com o registro eleitoral'],ok:0,why:'O Código Civil dispõe que a personalidade civil começa com o nascimento com vida, resguardados desde a concepção os direitos do nascituro.'}],flash:[['Dignidade da pessoa humana?','Fundamento da República.'],['Personalidade civil?','Começa, em regra, com o nascimento com vida.']]},
 penalprocessual:{name:'Noções de Direito Penal e Direito Processual Penal',color:'#EF9A9A',icon:'🔴',minutes:25,summary:'Associe tipicidade, dolo, culpa, tentativa e crimes frequentes às regras processuais de investigação, prova e prisão.',keywords:['crime','dolo','prova','prisão','processo'],questions:[{q:'A tentativa exige, em regra:',choices:['início da execução e não consumação por circunstâncias alheias à vontade','mera cogitação','resultado consumado','apenas intenção'],ok:0,why:'A tentativa pressupõe início da execução e não consumação por circunstâncias alheias à vontade do agente.'},{q:'A cadeia de custódia busca preservar principalmente:',choices:['a rastreabilidade do vestígio','a competência territorial','o segredo absoluto','a iniciativa da ação penal'],ok:0,why:'A cadeia de custódia documenta e preserva o percurso do vestígio.'}],flash:[['Tentativa?','Execução iniciada + não consumação por circunstância alheia.'],['Cadeia de custódia?','Rastreabilidade do vestígio.']]},
 administracaopoliticas:{name:'Noções de Administração e Políticas Públicas',color:'#A5D6A7',icon:'🟢',minutes:25,summary:'Estude princípios administrativos, organização pública, planejamento, políticas públicas, eficiência e prestação de serviços.',keywords:['administração','políticas públicas','planejamento','eficiência','serviço público'],questions:[{q:'O princípio da eficiência exige da Administração Pública:',choices:['busca de melhores resultados com adequada utilização de recursos','atuação sem controle','sigilo como regra absoluta','dispensa de legalidade'],ok:0,why:'Eficiência orienta a Administração à melhor entrega possível, sem afastar os demais princípios.'},{q:'Uma política pública normalmente parte de:',choices:['identificação de problema público e definição de objetivos','decisão sem diagnóstico','ausência de avaliação','mera escolha privada'],ok:0,why:'Políticas públicas articulam diagnóstico, objetivos, implementação e avaliação.'}],flash:[['Eficiência?','Melhor resultado com adequada utilização de recursos.'],['Política pública começa por quê?','Problema público + objetivo.']]},
 atuacao:{name:'Conhecimentos na Área de Atuação',color:'#80CBC4',icon:'🛡️',minutes:25,summary:'Conteúdo diretamente ligado às atribuições da Guarda Civil Municipal, atuação preventiva, proteção de bens, serviços, instalações e cooperação com outros órgãos.',keywords:['guarda municipal','prevenção','proteção','atuação','cooperação'],questions:[{q:'A atuação da Guarda Civil Municipal possui forte caráter:',choices:['preventivo e de proteção municipal','exclusivamente judiciário','legislativo','tributário'],ok:0,why:'A atuação da guarda municipal está ligada à proteção municipal e à prevenção, nos limites legais.'},{q:'Na atuação integrada, a cooperação entre órgãos busca:',choices:['melhorar prevenção e resposta dentro das competências legais','eliminar competências','substituir o Judiciário','dispensar planejamento'],ok:0,why:'A cooperação deve respeitar competências e melhorar a atuação coordenada.'}],flash:[['Eixo da atuação da GCM?','Prevenção e proteção municipal.'],['Integração?','Cooperação com respeito às competências legais.']]},
 legislacaoguarda:{name:'Legislação',color:'#CE93D8',icon:'📜',minutes:25,summary:'Treine a literalidade das normas indicadas no edital da Guarda Civil Municipal, com foco em competências, deveres, requisitos, exceções e prazos.',keywords:['lei','competência','dever','requisito','exceção'],questions:[{q:'Ao estudar legislação para prova objetiva, qual detalhe merece atenção especial?',choices:['competências, prazos, requisitos e exceções','somente títulos','apenas opiniões','apenas datas históricas'],ok:0,why:'Bancas transformam competências, prazos, requisitos e exceções em pegadinhas frequentes.'},{q:'Se a lei diz “poderá” e a alternativa troca por “deverá”, o correto é:',choices:['revisar a literalidade porque o sentido jurídico pode mudar','tratar como sinônimos','ignorar a troca','marcar sem conferir'],ok:0,why:'A troca de modalizador pode alterar faculdade em obrigação.'}],flash:[['Lei seca: o que marcar?','Competências, prazos, requisitos e exceções.'],['Poderá ≠ deverá?','Sim; pode mudar completamente o comando.']]},
 pedagogia:{name:'Conhecimentos Pedagógicos',color:'#FFCC80',icon:'🟠',minutes:25,summary:'Estude fundamentos da educação, didática, currículo, avaliação, inclusão e organização do trabalho pedagógico sempre ligados ao cargo escolhido.',keywords:['didática','currículo','avaliação','inclusão','aprendizagem'],questions:[
  {q:'Na avaliação formativa, o principal objetivo é:',choices:['acompanhar a aprendizagem e orientar intervenções pedagógicas','apenas classificar ao final','substituir o planejamento','eliminar a devolutiva ao aluno'],ok:0,why:'A avaliação formativa acompanha o processo e orienta ajustes no ensino e na aprendizagem.'},
  {q:'Um currículo inclusivo deve:',choices:['considerar diferenças e remover barreiras à aprendizagem','aplicar uma única estratégia a todos','ignorar necessidades específicas','separar avaliação de aprendizagem'],ok:0,why:'Inclusão exige acesso, participação e aprendizagem, com remoção de barreiras e estratégias adequadas.'}
 ],flash:[['Avaliação formativa serve para quê?','Acompanhar e melhorar o processo de aprendizagem.'],['Ideia central da inclusão?','Remover barreiras para garantir participação e aprendizagem.']]},
 especificos:{name:'Conhecimentos Específicos',color:'#B39DDB',icon:'🟣',minutes:25,summary:'Este bloco é vinculado à área/cargo escolhido e deve seguir o conteúdo específico do edital correspondente.',keywords:['conteúdo específico','cargo','edital','aplicação','especialidade'],questions:[
  {q:'No Aprova, o bloco de conhecimentos específicos deve ser definido por:',choices:['cargo/área e edital selecionados','uma lista genérica igual para todos','apenas pela banca','somente pela escolaridade'],ok:0,why:'O conteúdo específico depende do cargo/área e do edital selecionado.'},
  {q:'Ao trocar de cargo dentro do mesmo concurso, o que deve mudar?',choices:['conteúdo específico e, quando previsto, distribuição das disciplinas','apenas a cor da tela','somente o nome do concurso','nada'],ok:0,why:'O cargo pode alterar conteúdo específico, pesos, questões e até etapas da seleção.'}
 ],flash:[['O específico depende de quê?','Do cargo/área e do edital.'],['Trocar cargo pode mudar o quê?','Conteúdo, pesos, questões e etapas.']]},
 igualdade:{name:'Igualdade Racial e de Gênero',color:'#F48FB1',icon:'🤝',minutes:25,summary:'Revise igualdade material, combate à discriminação e os diplomas indicados no edital, distinguindo regra, finalidade e proteção específica.',keywords:['igualdade','discriminação','gênero','raça','proteção'],questions:[{q:'Igualdade material busca:',choices:['reduzir desigualdades reais por medidas juridicamente adequadas','tratar situações diferentes sempre de modo idêntico','eliminar proteção antidiscriminatória','substituir a legalidade'],ok:0,why:'A igualdade material admite tratamento juridicamente diferenciado quando necessário para enfrentar desigualdades reais.'},{q:'Em questão sobre discriminação, o primeiro passo é:',choices:['identificar a conduta, o grupo protegido e a norma aplicável','marcar pela palavra mais longa','ignorar exceções legais','presumir que toda distinção é ilícita'],ok:0,why:'A análise correta depende da conduta, do contexto e da proteção normativa indicada.'}],flash:[['Igualdade formal x material?','Formal: mesma regra; material: enfrenta desigualdades reais.'],['Como ler questão antidiscriminatória?','Conduta + grupo protegido + norma aplicável.']]},
 medicinalegal:{name:'Medicina Legal',color:'#B2DFDB',icon:'🩺',minutes:25,summary:'Organize conceitos por área: traumatologia, tanatologia, identificação e perícias. Em prova, detalhe técnico e terminologia correta fazem diferença.',keywords:['perícia','lesão','morte','identificação','vestígio'],questions:[{q:'A medicina legal auxilia o Direito principalmente por meio de:',choices:['conhecimentos médico-biológicos aplicados à prova e à perícia','criação de tipos penais','edição de sentenças','substituição do processo'],ok:0,why:'A medicina legal aplica conhecimentos médicos e biológicos a questões de interesse jurídico e pericial.'},{q:'Em questão de lesões, é essencial diferenciar:',choices:['mecanismo produtor, aspecto da lesão e consequência médico-legal','apenas o nome do perito','somente o local do fato','apenas a idade da vítima'],ok:0,why:'Bancas cobram a relação entre instrumento/mecanismo, características da lesão e classificação médico-legal.'}],flash:[['Medicina legal conecta quais áreas?','Conhecimento médico-biológico e aplicação jurídica/pericial.'],['Lesão: três eixos úteis?','Mecanismo + aspecto + consequência médico-legal.']]},
 legislacaogeral:{name:'Legislação Geral',color:'#D1C4E9',icon:'📘',minutes:25,summary:'Estude exatamente os diplomas gerais e estaduais listados no edital. Marque competências, deveres, impedimentos, prazos e exceções.',keywords:['lei','competência','dever','prazo','exceção'],questions:[{q:'Na leitura de legislação geral, qual conjunto merece marcação prioritária?',choices:['competências, prazos, requisitos e exceções','somente títulos','apenas nomes de autoridades','somente datas históricas'],ok:0,why:'Esses elementos são alvos recorrentes de questões de literalidade.'},{q:'A troca de “poderá” por “deverá” em alternativa deve ser:',choices:['conferida na literalidade porque pode alterar a natureza do comando','ignorada','tratada sempre como sinônimo','considerada irrelevante'],ok:0,why:'Modalizadores normativos podem transformar faculdade em obrigação.'}],flash:[['Lei seca: quatro alvos?','Competência, prazo, requisito e exceção.'],['Poderá x deverá?','Pode mudar faculdade em obrigação.']]},
 legislacaopenal:{name:'Legislação Penal e Processual Extravagante',color:'#EF9A9A',icon:'⚖️',minutes:25,summary:'Foque nas leis especiais expressamente previstas no edital, relacionando tipo penal, procedimento, competência, causa de aumento, prazo e exceção.',keywords:['lei especial','crime','procedimento','competência','exceção'],questions:[{q:'Ao estudar lei penal especial, o método mais seguro é:',choices:['ligar hipótese, requisito, consequência e exceção ao texto legal','memorizar apenas o nome da lei','ignorar procedimentos','usar somente resumo sem conferir norma'],ok:0,why:'A banca costuma alterar um requisito, uma exceção ou uma consequência prevista na lei especial.'},{q:'Quando duas alternativas diferem por um prazo legal, você deve:',choices:['conferir o dispositivo aplicável','escolher sempre o maior prazo','escolher sempre o menor prazo','ignorar a diferença'],ok:0,why:'Prazos em legislação especial são cobrança literal frequente.'}],flash:[['Lei especial: mapa curto?','Hipótese + requisito + consequência + exceção.'],['Prazo divergente?','Conferir o dispositivo.']]},
 estatistica:{name:'Estatística',color:'#FFCC80',icon:'📊',minutes:25,summary:'Transforme o enunciado em dados: população/amostra, variável, medida ou probabilidade. Calcule em etapas e confira unidade e interpretação.',keywords:['média','mediana','probabilidade','amostra','variância'],questions:[{q:'A mediana de uma lista ordenada representa:',choices:['o valor central ou a média dos dois centrais','sempre o maior valor','a soma de todos os valores','a frequência absoluta total'],ok:0,why:'A mediana ocupa a posição central; com quantidade par, é a média dos dois valores centrais.'},{q:'Uma amostra é:',choices:['um subconjunto da população usado para análise','sempre toda a população','uma medida de dispersão','um gráfico obrigatório'],ok:0,why:'A amostra é parte da população selecionada para produzir informação sobre o conjunto.'}],flash:[['Mediana?','Centro da lista ordenada.'],['Amostra?','Subconjunto da população.']]},
 contabilidade:{name:'Noções de Contabilidade',color:'#80CBC4',icon:'🧾',minutes:25,summary:'Comece pela equação patrimonial e pela natureza das contas. Depois avance para lançamentos, demonstrações e efeitos das operações.',keywords:['ativo','passivo','patrimônio líquido','débito','crédito'],questions:[{q:'A equação patrimonial básica relaciona:',choices:['Ativo = Passivo + Patrimônio Líquido','Receita = Ativo + Caixa','Passivo = Receita - Despesa','Ativo = apenas Caixa'],ok:0,why:'A identidade fundamental expressa que os recursos do ativo têm origem em passivos e patrimônio líquido.'},{q:'O ativo representa, em termos gerais:',choices:['bens e direitos controlados capazes de gerar benefícios','somente dívidas','apenas capital social','somente despesas'],ok:0,why:'Ativo reúne recursos econômicos controlados pela entidade, decorrentes de eventos passados.'}],flash:[['Equação patrimonial?','Ativo = Passivo + Patrimônio Líquido.'],['Ativo?','Recursos/bens e direitos controlados.']]},
 arquivologia:{name:'Noções de Arquivologia',color:'#90CAF9',icon:'🗂️',minutes:25,summary:'Relacione documento, arquivo, ciclo de vida, classificação, avaliação, destinação e preservação. Atenção ao vocabulário técnico.',keywords:['arquivo','documento','classificação','temporalidade','destinação'],questions:[{q:'A gestão de documentos acompanha documentos principalmente ao longo de:',choices:['produção, uso, avaliação e destinação','apenas criação','somente guarda permanente','apenas digitalização'],ok:0,why:'Gestão documental envolve o ciclo dos documentos e sua destinação adequada.'},{q:'Tabela de temporalidade é usada para:',choices:['definir prazos de guarda e destinação documental','registrar ponto de servidor','calcular folha de pagamento','substituir classificação'],ok:0,why:'Ela estabelece prazos de retenção e a destinação dos documentos conforme critérios arquivísticos.'}],flash:[['Gestão documental?','Produção + uso + avaliação + destinação.'],['Tabela de temporalidade?','Prazos de guarda + destinação.']]}
};


const COURSE_ROLE_PROFILES={
 'fgv-2e84885794':{
  title:'Prefeitura Municipal do Salvador 2026 • Educação',banca:'FGV',source:'https://conhecimento.fgv.br/concursos/pms2026',questionFormat:'abcde',
  structure:'70 questões: Língua Portuguesa 10, Raciocínio Lógico 5, Atualidades 5, Conhecimentos Pedagógicos 12, Legislação Específica 8 e Conhecimentos Específicos 30; além de 2 questões discursivas de conhecimentos específicos.',
  roles:[
   ['coord-ped','Coordenador Pedagógico','Conhecimentos Específicos — Coordenador Pedagógico'],
   ['prof-infantil','Professor Municipal I — Educação Infantil ao 5º Ano','Conhecimentos Específicos — Educação Infantil ao 5º Ano'],
   ['prof-ciencias','Professor Municipal I — Ciências Físicas e Biológicas','Conhecimentos Específicos — Ciências Físicas e Biológicas'],
   ['prof-artes-plasticas','Professor Municipal I — Educação Artística — Artes Plásticas','Conhecimentos Específicos — Artes Plásticas'],
   ['prof-danca','Professor Municipal I — Educação Artística — Dança','Conhecimentos Específicos — Dança'],
   ['prof-musica','Professor Municipal I — Educação Artística — Música','Conhecimentos Específicos — Música'],
   ['prof-teatro','Professor Municipal I — Educação Artística — Teatro','Conhecimentos Específicos — Teatro'],
   ['prof-edfisica','Professor Municipal I — Educação Física','Conhecimentos Específicos — Educação Física'],
   ['prof-geografia','Professor Municipal I — Geografia','Conhecimentos Específicos — Geografia'],
   ['prof-historia','Professor Municipal I — História','Conhecimentos Específicos — História'],
   ['prof-ingles','Professor Municipal I — Língua Estrangeira — Inglês','Conhecimentos Específicos — Inglês'],
   ['prof-portugues','Professor Municipal I — Língua Portuguesa','Conhecimentos Específicos — Língua Portuguesa'],
   ['prof-matematica','Professor Municipal I — Matemática','Conhecimentos Específicos — Matemática']
  ].map(([id,label,specificLabel])=>({id,label,specificLabel,subjectWeights:{portugues:10,raciocinio:5,atualidades:5,pedagogia:12,legislacao:8,especificos:30},recommendedStart:'pedagogia'}))
 }
};
const DIRECT_COURSE_PROFILES={
 'fgv-c78302f30e':{role:'Guarda Civil Municipal',questionFormat:'abcde',subjectWeights:{portugues:10,raciocinio:10,informatica:8,constitucionalcivil:10,penalprocessual:7,administracaopoliticas:5,atuacao:10,legislacaoguarda:10},subjectLabels:{},recommendedStart:'atuacao',examStructure:'70 questões: Português 10, Raciocínio Lógico-Matemático 10, Informática 8, Noções de Direito Constitucional e Direito Civil 10, Noções de Direito Penal e Direito Processual Penal 7, Noções de Administração e Políticas Públicas 5, Conhecimentos na Área de Atuação 10 e Legislação 10.',examSource:'Edital nº 02/2026, item 9.4'},
 'pcba-2026-investigador':{role:'Investigador de Polícia Civil',questionFormat:'abcde',subjectWeights:{portugues:6,raciocinio:6,atualidades:5,informatica:5,igualdade:5,medicinalegal:6,legislacaogeral:7,administrativo:8,constitucional:8,penal:10,processopenal:10,legislacaopenal:9,estatistica:8,contabilidade:7},recommendedStart:'penal',examStructure:'100 questões objetivas: 40 de Conhecimentos Gerais e 60 de Conhecimentos Específicos. O edital não fixa, dentro desses blocos, uma quantidade por disciplina. Para Investigador, o conteúdo inclui Português, Raciocínio Lógico, Atualidades, Informática, Igualdade Racial e de Gênero, Medicina Legal, Legislação Geral, Direito Administrativo, Constitucional, Penal, Processo Penal, Legislação Penal/Processual Extravagante, Estatística e Contabilidade; além de 4 questões discursivas.',examSource:'Edital SAEB nº 02/2026'},
 'pcba-2026-escrivao':{role:'Escrivão de Polícia Civil',questionFormat:'abcde',subjectWeights:{portugues:6,raciocinio:6,atualidades:5,informatica:5,igualdade:5,medicinalegal:6,legislacaogeral:7,administrativo:8,constitucional:8,penal:10,processopenal:10,legislacaopenal:9,estatistica:8,arquivologia:7},recommendedStart:'penal',examStructure:'100 questões objetivas: 40 de Conhecimentos Gerais e 60 de Conhecimentos Específicos. O edital não fixa, dentro desses blocos, uma quantidade por disciplina. Para Escrivão, o conteúdo inclui Português, Raciocínio Lógico, Atualidades, Informática, Igualdade Racial e de Gênero, Medicina Legal, Legislação Geral, Direito Administrativo, Constitucional, Penal, Processo Penal, Legislação Penal/Processual Extravagante, Estatística e Arquivologia; além de 4 questões discursivas.',examSource:'Edital SAEB nº 02/2026'}
};
function isMunicipalUmbrella(hit){const t=String(hit?.title||'');return /Prefeitura|Munic[ií]pio/i.test(t)&&!/(Guarda|Professor|Coordenador|Procurador|M[eé]dico|Enfermeiro|Dentista|T[eé]cnico|Agente|Auditor|Fiscal)/i.test(t);}
function roleProfileForCourse(hit){return hit?COURSE_ROLE_PROFILES[hit.id]||null:null;}
function applyCourseProfile(hit,role=null){
 const direct=DIRECT_COURSE_PROFILES[hit?.id]||null, prof=role||direct;
 u.profile.subjectWeights=prof?.subjectWeights?{...prof.subjectWeights}:null;u.profile.subjectLabels=prof?.subjectLabels?{...prof.subjectLabels}:{};u.profile.recommendedStart=prof?.recommendedStart||'';u.profile.role=prof?.label||prof?.role||'';u.profile.roleId=prof?.id||'';u.profile.specificSubjectLabel=prof?.specificLabel||'';u.profile.examStructure=prof?.examStructure||roleProfileForCourse(hit)?.structure||'';u.profile.examStructureSource=prof?.examSource||roleProfileForCourse(hit)?.source||hit?.source_url||'';
}
function courseQuestionFormat(){return u?.profile?.questionFormat||'';}
function formattedTrainingQuestions(base){
 const fmt=courseQuestionFormat(),qs=Array.isArray(base?.questions)?base.questions:[];
 if(fmt==='ce')return qs.map((q,i)=>{const correct=Number(q.ok)||0,useCorrect=i%2===0,shown=useCorrect?correct:(correct===0?1:0),statement=(q.q||'').replace(/[?:\s]+$/,'');return {...q,q:`Julgue o item: ${statement} — ${q.choices[shown]}.`,choices:['Certo','Errado'],ok:useCorrect?0:1,why:useCorrect?q.why:`O item está errado. ${q.why}`};});
 if(fmt==='abcde')return qs.map(q=>q.choices?.length===4?{...q,choices:[...q.choices,'Todas as alternativas anteriores estão corretas.']}:q);
 if(fmt==='abcd')return qs.map(q=>q.choices?.length>4?{...q,choices:q.choices.slice(0,4),ok:Math.min(Number(q.ok)||0,3)}:q);
 return qs;
}
function subjectView(k){const base=SUBJECTS[k]||SUBJECTS.portugues,label=u?.profile?.subjectLabels?.[k]||(k==='especificos'&&u?.profile?.specificSubjectLabel)||base.name,questions=formattedTrainingQuestions(base);return {...base,name:label,questions};}

const PROFILES={
 police:{portugues:18,penal:18,processopenal:18,constitucional:12,administrativo:10,direitoshumanos:9,informatica:7,raciocinio:5,legislacao:14},
 tribunal:{portugues:20,constitucional:15,administrativo:15,raciocinio:10,informatica:10,legislacao:15,direitoshumanos:5},
 fiscal:{portugues:10,constitucional:10,administrativo:10,raciocinio:18,informatica:8,legislacao:20,atualidades:4},
 health:{portugues:8,raciocinio:6,informatica:5,legislacao:18,constitucional:5,administrativo:5,atualidades:8},
 education:{portugues:20,raciocinio:15,atualidades:10,legislacao:15,informatica:8,constitucional:5},
 legal:{constitucional:18,administrativo:15,portugues:12,legislacao:15,direitoshumanos:10,penal:10,processopenal:10},
 general:{portugues:18,constitucional:12,administrativo:12,raciocinio:12,informatica:10,legislacao:14,atualidades:8,direitoshumanos:6}
};

function inferKind(){const t=(u?.profile?.target||'').toLowerCase();if(/pol[ií]cia|investigador|escriv|delegad|guarda|agente/.test(t))return'police';if(/tribunal|trt|tre|trf|judici/.test(t))return'tribunal';if(/sefaz|fiscal|receita|auditor|controladoria|tce|cgu/.test(t))return'fiscal';if(/ebserh|sa[uú]de|enferm|medic|resid[eê]ncia/.test(t))return'health';if(/professor|educa|enem|vestibular/.test(t))return'education';if(/oab|magistr|promotor|defensor|procurador|enam|enac/.test(t))return'legal';return'general';}
function bancaBias(weights){const b=(u?.profile?.banca||'').toLowerCase(),w={...weights};if(b.includes('fgv')){w.portugues=(w.portugues||0)+5;w.constitucional=(w.constitucional||0)+2;}if(b.includes('cebraspe')){w.legislacao=(w.legislacao||0)+3;w.constitucional=(w.constitucional||0)+2;}if(b.includes('aocp')){w.portugues=(w.portugues||0)+3;w.informatica=(w.informatica||0)+2;}if(b.includes('quadrix')){w.portugues=(w.portugues||0)+2;w.legislacao=(w.legislacao||0)+3;}return w;}
function performanceBias(weights){const w={...weights};Object.keys(w).forEach(k=>{const p=ae.performance[k];if(!p)return;const rate=p.total?p.correct/p.total:1;if(rate<.5)w[k]+=8;else if(rate<.7)w[k]+=4;else if(rate>.9)w[k]=Math.max(1,w[k]-2);});return w;}
function weightsForUser(){const exact=u?.profile?.subjectWeights;if(exact&&Object.keys(exact).length)return performanceBias({...exact});return performanceBias(bancaBias(PROFILES[inferKind()]||PROFILES.general));}
function dailyBlocks(){if(!u?.trial?.paid||!u?.profile?.hoursConfigured)return 1;const hours=Number(u?.profile?.hours||2);return Math.max(1,Math.floor(hours*60/25));}
function weightedQueue(){const w=weightsForUser(),entries=Object.entries(w).filter(([k,v])=>SUBJECTS[k]&&v>0),scores={};entries.forEach(([k])=>scores[k]=0);const n=dailyBlocks(),out=[],total=entries.reduce((s,x)=>s+x[1],0);for(let i=0;i<n;i++){entries.forEach(([k,v])=>scores[k]+=v);entries.sort((a,b)=>scores[b[0]]-scores[a[0]]);const k=entries[0][0];out.push(k);scores[k]-=total;}return out;}
function engineDayKey(){return typeof localDateKey==='function'?localDateKey():new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());}
function ensureDay(){const today=engineDayKey();if(ae.day.date!==today||!Array.isArray(ae.day.queue)){ae.day={date:today,queue:weightedQueue(),index:0,stage:0,maxStageIndex:0,answer:null,learned:'',learnedScore:null,startedAt:Date.now(),startChosen:false,startSubjectKey:'',sessionStats:{correct:0,total:0,streak:0,bestStreak:0},sessionSeen:{}};aesave();}const seq=[0,1,3,4,5,6,7,8,9,10],idx=Math.max(0,seq.indexOf(ae.day.stage||0));if(!Number.isInteger(ae.day.maxStageIndex))ae.day.maxStageIndex=idx;else ae.day.maxStageIndex=Math.max(ae.day.maxStageIndex,idx);ae.day.answers=ae.day.answers||{};ae.day.results=ae.day.results||{};ae.day.sessionStats=ae.day.sessionStats||{correct:0,total:0,streak:0,bestStreak:0};ae.day.sessionSeen=ae.day.sessionSeen||{};return ae.day;}
function currentSubjectKey(){const d=ensureDay();return d.queue[Math.min(d.index,d.queue.length-1)]||'portugues';}
function currentSubject(){return subjectView(currentSubjectKey());}
function startChoiceKeys(){
 const d=ensureDay();
 if(!u?.trial?.paid&&d.index===0&&Number(d.stage||0)===0&&!d.startChosen){
  let ranked=Object.entries(weightsForUser()).filter(([k,v])=>SUBJECTS[k]&&v>0).sort((a,b)=>b[1]-a[1]).map(([k])=>k);
  const rec=u?.profile?.recommendedStart;if(rec&&ranked.includes(rec))ranked=[rec,...ranked.filter(k=>k!==rec)];
  const keys=ranked.filter(k=>k!=='portugues').slice(0,6);
  if(ranked.includes('portugues'))keys.push('portugues');
  return keys;
 }
 return [...new Set(d.queue.slice(d.index))].filter(k=>SUBJECTS[k]);
}
window.chooseStartSubject=function(k){
 const d=ensureDay();if(d.index!==0||Number(d.stage||0)!==0||!SUBJECTS[k])return;
 if(!u?.trial?.paid){d.queue=[k];d.index=0;}
 else{const pos=d.queue.indexOf(k,d.index);if(pos<0)return;const picked=d.queue.splice(pos,1)[0];d.queue.splice(d.index,0,picked);}
 d.startChosen=true;d.startSubjectKey=k;d.masterStage=0;d.answer=null;d.answers={};d.results={};d.reinforcementAnswers={};aesave();uRenderAll();window.scrollTo({top:0,behavior:'smooth'});
};
function startSubjectChooser(){
 const d=ensureDay();if(d.index!==0||Number(d.stage||0)!==0||d.startChosen)return'';const keys=startChoiceKeys();
 return `<div class="start-picker"><div class="start-picker-title"><span>1</span><div><b>Escolha a matéria para iniciar</b><small>Comece por uma matéria com a qual você tenha mais afinidade. Português continua disponível, mas não é selecionado automaticamente.</small></div></div><div class="start-choice-grid">${keys.map((k,i)=>{const x=subjectView(k),hint=k==='portugues'?'disponível se você preferir':i===0?'boa para começar':'escolha livre';return `<button class="start-choice" onclick="chooseStartSubject('${k}')"><span class="queue-dot" style="background:${x.color}"></span><span><b>${x.name}</b><small>${hint}</small></span><strong>INICIAR</strong></button>`}).join('')}</div></div>`;
}
function updatePerf(ok){const k=currentSubjectKey(),p=ae.performance[k]||{correct:0,total:0};p.total++;if(ok)p.correct++;ae.performance[k]=p;aesave();}
const LEGAL_Q_META={
 constitucional:[
  {basis:'Constituição Federal, art. 37, caput.',simple:'O caput do art. 37 traz expressamente Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência — o mnemônico LIMPE.',bank:'A banca costuma trocar um princípio expresso por um implícito, como razoabilidade, proporcionalidade, autotutela ou segurança jurídica.',trap:'Se aparecer “princípios expressos no caput”, procure exatamente LIMPE.'},
  {basis:'Constituição Federal, art. 5º, LXIX; Lei 12.016/2009, art. 1º.',simple:'O Mandado de Segurança protege direito líquido e certo, demonstrável de plano, quando não for hipótese de habeas corpus ou habeas data.',bank:'A banca costuma misturar MS com HC, HD ou situações que exigem produção de prova.',trap:'MS = direito líquido e certo + prova pré-constituída + ato de autoridade.'}
 ],
 administrativo:[
  {basis:'Constituição Federal, art. 37, § 6º.',simple:'A pessoa jurídica responde objetivamente pelo dano causado por seu agente nessa qualidade. O regresso contra o agente depende de dolo ou culpa.',bank:'A pegadinha é afirmar que a responsabilidade do Estado é subjetiva ou que o regresso independe de culpa/dolo.',trap:'Estado: objetiva. Agente no regresso: dolo ou culpa.'},
  {basis:'Lei 9.784/1999, art. 53; STF, Súmula 473.',simple:'Anulação combate ilegalidade. Revogação atinge ato válido por conveniência e oportunidade.',bank:'É comum inverter anulação e revogação ou dizer que ato ilegal é apenas inconveniente.',trap:'Ilegalidade = anula. Mérito válido = pode revogar.'}
 ],
 penal:[
  {basis:'Código Penal, art. 18, I.',simple:'Há dolo quando o agente quer o resultado ou assume o risco de produzi-lo.',bank:'A banca contrapõe dolo direto, dolo eventual e culpa, alterando vontade, previsão e aceitação do risco.',trap:'Quis ou assumiu o risco = dolo.'},
  {basis:'Código Penal, art. 14, II.',simple:'Tentativa exige início da execução e não consumação por circunstâncias alheias à vontade do agente.',bank:'A banca tenta confundir tentativa com cogitação, atos preparatórios ou desistência voluntária.',trap:'Começou a executar + não consumou por fator externo = tentativa.'}
 ],
 processopenal:[
  {basis:'Código de Processo Penal, art. 3º-A.',simple:'O processo penal tem estrutura acusatória: acusar e julgar são funções separadas.',bank:'A banca testa iniciativa probatória do juiz, separação de funções e limites do sistema acusatório.',trap:'Quem acusa não é quem julga.'},
  {basis:'Código de Processo Penal, arts. 158-A a 158-F, especialmente art. 158-A.',simple:'A cadeia de custódia documenta e preserva a história cronológica do vestígio desde o reconhecimento até o descarte.',bank:'A banca troca rastreabilidade por substituição da perícia, dispensa de documentação ou eliminação do contraditório.',trap:'Cadeia de custódia = rastreabilidade do vestígio.'}
 ],
 direitoshumanos:[
  {basis:'Constituição Federal, art. 1º, III.',simple:'A dignidade da pessoa humana é fundamento da República Federativa do Brasil.',bank:'A banca tenta deslocar a dignidade para objetivo, princípio setorial ou direito restrito a uma área.',trap:'Dignidade = fundamento da República.'},
  {basis:'Declaração Universal dos Direitos Humanos, arts. 1º e 2º; Declaração e Programa de Ação de Viena (1993), item 5.',simple:'Os direitos humanos são universais, indivisíveis, interdependentes e inter-relacionados.',bank:'Desconfie de alternativas que restrinjam direitos humanos a nacionalidade, guerra, região ou tratado específico.',trap:'Universalidade + interdependência são características centrais.'}
 ]
};
function isLegalSubjectKey(k=currentSubjectKey()){return ['constitucional','administrativo','penal','processopenal','direitoshumanos','legislacao'].includes(k);}
function legalQuestionMeta(k,idx){if(k==='legislacao')return {basis:'Use a lei específica indicada no edital. O artigo depende da norma cobrada na questão.',simple:'Em legislação específica, identifique competência, prazo, requisito, proibição e exceção diretamente no texto legal aplicável.',bank:'A banca costuma explorar palavras como “salvo”, “exceto”, “ressalvada”, “poderá” e “deverá”.',trap:'Não invente artigo: confirme sempre na lei específica do edital.'};return LEGAL_Q_META[k]?.[idx]||null;}
function recordQuestionPerformance(source,qidx,ok){const d=ensureDay(),key=`${d.index}:${currentSubjectKey()}:${source}:${qidx}`;if(d.sessionSeen[key])return false;d.sessionSeen[key]=1;updatePerf(ok);const st=d.sessionStats||(d.sessionStats={correct:0,total:0,streak:0,bestStreak:0});st.total++;if(ok){st.correct++;st.streak++;st.bestStreak=Math.max(st.bestStreak||0,st.streak);}else st.streak=0;aesave();return true;}
function performanceSnapshot(){const d=ensureDay(),k=currentSubjectKey(),p=ae.performance[k]||{correct:0,total:0},st=d.sessionStats||{correct:0,total:0,streak:0,bestStreak:0};return {subject:p.total?Math.round(p.correct/p.total*100):0,today:st.total?Math.round(st.correct/st.total*100):0,streak:st.streak||0,best:st.bestStreak||0,correct:p.correct,total:p.total};}
function encouragementText(ok,snap){if(!ok)return snap.today>=70?'Você está mantendo um bom aproveitamento. Corrija esta agora e siga o ritmo.':'Esse erro virou revisão imediatamente — é exatamente assim que o sistema fortalece sua memória.';if(snap.streak>=4)return `🔥 ${snap.streak} acertos seguidos! Você entrou em ritmo forte.`;if(snap.subject>=80)return '🚀 Excelente. Seu domínio desta matéria já está em nível alto nesta sessão.';if(snap.subject>=60)return '👏 Muito bom. Você está consolidando o assunto — continue a sequência.';return '🎉 Parabéns! Mais um acerto registrado. Continue enquanto a memória está ativa.';}
function buildQuestionFeedback(sub,idx,ok,compact=false){const q=sub.questions[idx],snap=performanceSnapshot(),k=currentSubjectKey(),legal=isLegalSubjectKey(k),meta=legalQuestionMeta(k,idx),heading=ok?'🎉 Parabéns! Você acertou.':'❌ Resposta incorreta — vamos fixar a correta.';const stats=`<div class="performance-strip"><div><strong>${snap.subject}%</strong><span>${sub.name}</span></div><div><strong>${snap.today}%</strong><span>hoje</span></div><div><strong>${snap.streak}</strong><span>sequência</span></div></div><div class="accuracy-bar"><i style="width:${snap.today}%"></i></div>`;let detail=`<div class="answer-feedback ${ok?'feedback-ok':'feedback-bad'}"><b>${ok?'Por que está certa':'Resposta correta'}:</b> ${ok?q.why:`${q.choices[q.ok]}<br><br>${q.why}`}</div>`;if(legal&&meta){detail+=`<div class="legal-feedback-grid"><div class="legal-box"><span>⚖️ FUNDAMENTO</span><b>${meta.basis}</b></div><div class="legal-box"><span>🧠 EM LINGUAGEM SIMPLES</span><p>${meta.simple}</p></div><div class="legal-box"><span>🎯 COMO A BANCA COBRA</span><p>${meta.bank}</p></div><div class="legal-box"><span>⚠️ PEGADINHA / GATILHO</span><p>${meta.trap}</p></div></div>`;}else{detail+=`<div class="nonlegal-feedback-grid"><div class="memory-tip"><span>🧠 COMO PENSAR</span><p>${q.why}</p></div><div class="memory-tip"><span>💡 GATILHO DE MEMÓRIA</span><p>${sub.flash?.[idx]?.[1]||sub.keywords?.slice(0,3).join(' • ')||'Explique a regra com suas próprias palavras antes de seguir.'}</p></div></div>`;}return `<div class="instant-result ${ok?'instant-ok':'instant-bad'}"><h3>${heading}</h3><p class="motivation-line">${encouragementText(ok,snap)}</p>${stats}${compact?'':detail}${compact&&ok?`<div class="mini-explain">${q.why}</div>`:compact&&!ok?detail:''}</div>`;}
window.buildQuestionFeedback=buildQuestionFeedback;
window.recordQuestionPerformance=recordQuestionPerformance;

const REINFORCEMENT_BANK={
 portugues:[
  {q:'Na expressão “os candidatos que estudaram”, o termo “que” retoma:',choices:['candidatos','estudaram','uma circunstância de tempo','uma conjunção sem antecedente'],ok:0,why:'O “que” retoma o substantivo “candidatos” e funciona como pronome relativo.'},
  {q:'Uma oração adjetiva sem vírgulas tende a ter valor:',choices:['restritivo','explicativo','conclusivo','causal'],ok:0,why:'Sem vírgulas, a oração adjetiva normalmente restringe o conjunto ao qual se refere.'},
  {q:'Uma oração adjetiva entre vírgulas tende a ser:',choices:['explicativa','restritiva','coordenada adversativa','substantiva objetiva'],ok:0,why:'As vírgulas costumam marcar valor explicativo, acrescentando uma informação sobre o antecedente.'},
  {q:'Ao comparar duas alternativas de pontuação, o primeiro passo é verificar:',choices:['se o sentido mudou','qual é a mais curta','qual tem mais vírgulas','qual evita verbos'],ok:0,why:'Em questões de pontuação, a banca frequentemente explora mudança de sentido antes da mera regra mecânica.'}
 ],
 constitucional:[
  {q:'Qual destes princípios NÃO está expresso no caput do art. 37 da CF?',choices:['Razoabilidade','Legalidade','Moralidade','Eficiência'],ok:0,why:'Razoabilidade é princípio reconhecido, mas não integra o rol expresso do caput do art. 37.',basis:'CF, art. 37, caput.',bank:'A banca mistura princípios expressos e implícitos.',trap:'LIMPE = Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.'},
  {q:'O mnemônico LIMPE corresponde a:',choices:['Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência','Legalidade, Interesse público, Motivação, Publicidade e Eficiência','Legalidade, Impessoalidade, Motivação, Proporcionalidade e Eficiência','Legalidade, Isonomia, Moralidade, Publicidade e Efetividade'],ok:0,why:'LIMPE resume os cinco princípios expressos no caput do art. 37.',basis:'CF, art. 37, caput.',bank:'FGV, AOCP e IDECAN cobram tanto o rol literal quanto a distinção entre expressos e implícitos.',trap:'Não troque impessoalidade por isonomia nem publicidade por proporcionalidade.'},
  {q:'Para Mandado de Segurança, a prova do direito deve ser, em regra:',choices:['pré-constituída','produzida apenas por perícia futura','dispensável','exclusivamente testemunhal'],ok:0,why:'O direito líquido e certo deve ser demonstrável de plano, razão pela qual a prova é pré-constituída.',basis:'CF, art. 5º, LXIX; Lei 12.016/2009, art. 1º.',bank:'A banca costuma colocar situações que exigem dilação probatória para afastar o MS.',trap:'MS não é via adequada quando a demonstração do direito depende de ampla produção de prova.'},
  {q:'Se a pretensão protege liberdade de locomoção, o remédio constitucional típico é:',choices:['Habeas Corpus','Mandado de Segurança','Habeas Data','Mandado de Injunção'],ok:0,why:'A liberdade de locomoção é protegida pelo Habeas Corpus.',basis:'CF, art. 5º, LXVIII.',bank:'A banca compara HC, HD, MS e MI para testar o objeto de cada remédio.',trap:'Locomoção = HC; dados pessoais = HD; direito líquido e certo = MS; omissão normativa = MI.'}
 ],
 administrativo:[
  {q:'A responsabilidade objetiva do Estado significa que, em regra, a vítima deve provar:',choices:['dano e nexo causal','dolo do agente','culpa administrativa específica','sentença penal condenatória'],ok:0,why:'Na responsabilidade objetiva, a vítima não precisa provar dolo ou culpa do agente para responsabilizar o Estado.',basis:'CF, art. 37, §6º.',bank:'A banca separa os requisitos da responsabilidade do Estado dos requisitos da ação regressiva.',trap:'Estado: objetiva. Regresso contra o agente: dolo ou culpa.'},
  {q:'A ação regressiva contra o agente público exige:',choices:['dolo ou culpa','apenas dano','responsabilidade objetiva automática','mera ilegalidade sem elemento subjetivo'],ok:0,why:'O direito de regresso contra o agente depende de dolo ou culpa.',basis:'CF, art. 37, §6º.',bank:'Pegadinha comum: transferir a objetividade do Estado para a responsabilidade pessoal do agente.',trap:'Objetiva para o Estado; subjetiva para o agente no regresso.'},
  {q:'A anulação de ato administrativo decorre de:',choices:['ilegalidade','conveniência','oportunidade','mera mudança de gestão'],ok:0,why:'Anulação retira ato ilegal; revogação recai sobre ato válido por razões de mérito.'},
  {q:'A revogação pressupõe, em regra, ato:',choices:['válido, mas inconveniente ou inoportuno','ilegal desde a origem','criminoso','judicial'],ok:0,why:'Revogação é juízo de mérito administrativo sobre ato válido.'}
 ],
 penal:[
  {q:'No dolo eventual, o agente:',choices:['prevê o resultado e assume o risco de produzi-lo','não prevê resultado previsível','quer apenas agir com negligência','atua sem qualquer consciência'],ok:0,why:'No dolo eventual há previsão e assunção do risco.',basis:'Código Penal, art. 18, I.',bank:'A banca contrasta dolo eventual e culpa consciente.',trap:'Dolo eventual = assume o risco; culpa consciente = prevê, mas acredita que evitará.'},
  {q:'Na culpa consciente, o agente:',choices:['prevê o resultado, mas acredita que ele não ocorrerá','assume o risco do resultado','quer diretamente o resultado','não pratica conduta'],ok:0,why:'Na culpa consciente o resultado é previsto, porém o agente confia que conseguirá evitá-lo.',basis:'Código Penal, art. 18, II.',bank:'Questões descrevem o estado mental do agente e pedem a classificação.',trap:'Se aceitou o risco, tende a dolo eventual; se confiou em evitar, culpa consciente.'},
  {q:'A tentativa começa quando há:',choices:['início da execução','mera cogitação','apenas preparação distante','resultado consumado'],ok:0,why:'A tentativa pressupõe início da execução e não consumação por circunstâncias alheias à vontade do agente.',basis:'Código Penal, art. 14, II.',bank:'A banca explora a fronteira entre atos preparatórios e executórios.',trap:'Cogitação e preparação, em regra, não bastam para tentativa.'},
  {q:'Se o crime se consuma, em regra:',choices:['não se fala em tentativa','há tentativa perfeita obrigatoriamente','a pena é sempre reduzida','o fato se torna atípico'],ok:0,why:'Consumação afasta a figura da tentativa para o mesmo resultado típico.',basis:'Código Penal, arts. 14, I e II.',bank:'A banca pode narrar todos os atos e perguntar se houve consumação ou tentativa.',trap:'Primeiro identifique se todos os elementos do tipo se realizaram.'}
 ],
 processopenal:[
  {q:'No sistema acusatório, quem acusa não deve exercer a função de:',choices:['julgar','investigar em nenhuma hipótese','defender o réu','legislar'],ok:0,why:'A separação entre acusar e julgar é característica essencial do sistema acusatório.',basis:'CPP, art. 3º-A.',bank:'A banca testa separação de funções e imparcialidade judicial.',trap:'Acusar ≠ julgar.'},
  {q:'A cadeia de custódia acompanha o vestígio:',choices:['desde o reconhecimento até o descarte','somente depois da perícia','apenas dentro do laboratório','apenas até a coleta'],ok:0,why:'A cadeia de custódia documenta a história cronológica do vestígio ao longo das etapas previstas em lei.',basis:'CPP, arts. 158-A e seguintes.',bank:'É comum cobrar etapas e finalidade da cadeia de custódia.',trap:'Pense em rastreabilidade contínua do vestígio.'},
  {q:'A principal finalidade da cadeia de custódia é preservar:',choices:['a rastreabilidade e integridade do vestígio','o sigilo absoluto do processo','a competência territorial','a iniciativa da ação penal'],ok:0,why:'Ela busca documentar e preservar o percurso do vestígio, reduzindo dúvidas sobre sua integridade.',basis:'CPP, art. 158-A.',bank:'A banca costuma trocar “rastreabilidade” por finalidades que pertencem a outros institutos.',trap:'Vestígio + percurso documentado = cadeia de custódia.'},
  {q:'A imparcialidade do julgador é reforçada pela:',choices:['separação entre acusação e julgamento','concentração de todas as funções no juiz','dispensa de contraditório','substituição da defesa'],ok:0,why:'A separação funcional reduz o risco de o julgador assumir papel de acusador.',basis:'CPP, art. 3º-A.',bank:'Questões conceituais ligam sistema acusatório à separação de funções.',trap:'Juiz julga; acusação acusa.'}
 ],
 informatica:[
  {q:'A autenticação multifator melhora a segurança porque:',choices:['exige mais de um fator de verificação','duplica a mesma senha','desativa atualizações','elimina a necessidade de autenticação'],ok:0,why:'MFA combina fatores independentes e reduz o impacto de uma senha comprometida.'},
  {q:'Um código recebido no celular usado junto da senha é exemplo de:',choices:['segundo fator de autenticação','backup incremental','firewall físico','phishing'],ok:0,why:'O código adiciona um fator além da senha.'},
  {q:'Phishing normalmente tenta:',choices:['enganar o usuário para obter dados ou induzir clique malicioso','melhorar a conexão','atualizar o antivírus','compactar arquivos'],ok:0,why:'Phishing explora engenharia social.'},
  {q:'Desconfiar de links inesperados ajuda principalmente contra:',choices:['phishing','fragmentação de disco','compressão de dados','backup local'],ok:0,why:'Links fraudulentos são vetor comum de phishing.'}
 ],
 raciocinio:[
  {q:'A negação de “Nenhum candidato faltou” é:',choices:['Pelo menos um candidato faltou','Todos os candidatos faltaram','Nenhum candidato compareceu','Alguns candidatos não faltaram'],ok:0,why:'A negação de “nenhum” é “existe pelo menos um”.'},
  {q:'A negação de “Existe candidato aprovado” é:',choices:['Nenhum candidato foi aprovado','Todos foram aprovados','Alguns foram reprovados','Existe candidato reprovado'],ok:0,why:'Negar uma existência significa afirmar que nenhum elemento satisfaz a condição.'},
  {q:'Uma conjunção P ∧ Q é verdadeira quando:',choices:['P e Q são verdadeiras','apenas P é verdadeira','apenas Q é verdadeira','pelo menos uma é falsa'],ok:0,why:'A conjunção exige verdade de ambas as proposições.'},
  {q:'Se P é falsa e Q é verdadeira, P ∧ Q é:',choices:['falsa','verdadeira','tautológica','indeterminada'],ok:0,why:'Basta uma parcela falsa para a conjunção ser falsa.'}
 ],
 direitoshumanos:[
  {q:'A dignidade da pessoa humana aparece na CF como:',choices:['fundamento da República','objetivo apenas econômico','competência municipal','norma transitória'],ok:0,why:'A dignidade da pessoa humana é fundamento da República.',basis:'CF, art. 1º, III.',bank:'A banca troca fundamento, objetivo e princípio das relações internacionais.',trap:'Dignidade = fundamento, art. 1º, III.'},
  {q:'Universalidade dos direitos humanos significa que eles:',choices:['se dirigem a todas as pessoas','dependem de nacionalidade específica','existem apenas em guerra','valem apenas por tratado regional'],ok:0,why:'A universalidade indica que os direitos humanos se destinam a todas as pessoas.'},
  {q:'Interdependência significa que os direitos humanos:',choices:['se relacionam e se reforçam mutuamente','são totalmente isolados','só valem de forma hierárquica','dependem de autorização administrativa'],ok:0,why:'Os direitos se conectam; a proteção de um frequentemente favorece outros.'},
  {q:'Ao cobrar características dos direitos humanos, uma alternativa absoluta e excludente deve ser:',choices:['analisada com cautela','sempre marcada como correta','aceita sem contexto','preferida à literalidade'],ok:0,why:'Bancas usam termos absolutos para criar pegadinhas em temas com nuances.'}
 ],
 legislacao:[
  {q:'Em legislação específica, palavras como “salvo” e “exceto” indicam:',choices:['exceção relevante','regra sem ressalva','mera pontuação','conceito sem efeito jurídico'],ok:0,why:'Esses termos costumam alterar a regra geral e são alvos frequentes de prova.'},
  {q:'Qual grupo merece marcação especial na lei seca?',choices:['prazos, competências, requisitos e exceções','somente títulos dos capítulos','apenas definições doutrinárias','somente exposições de motivos'],ok:0,why:'Prazos, competências, requisitos e exceções aparecem com frequência em questões objetivas.'},
  {q:'Se a questão troca “poderá” por “deverá”, você deve:',choices:['verificar a literalidade porque a obrigação pode ter mudado','ignorar a troca','considerar sinônimos absolutos','marcar sem consultar a regra'],ok:0,why:'Modalizadores normativos podem mudar completamente o comando legal.'},
  {q:'Para fixar legislação específica, o melhor complemento à leitura é:',choices:['resolver questões e registrar erros','evitar questões','decorar sem contexto','ler apenas resumos de terceiros'],ok:0,why:'Questões revelam quais detalhes a banca transforma em pegadinha.'}
 ],
 atualidades:[
  {q:'Uma informação de atualidades fica mais confiável quando possui:',choices:['fonte, data e contexto verificáveis','apenas muitas curtidas','título impactante','mensagem encaminhada várias vezes'],ok:0,why:'Confiabilidade depende de origem verificável, contexto e atualidade.'},
  {q:'Para memorizar um fato atual, associe:',choices:['fato, causa, consequência e instituição envolvida','apenas a manchete','somente a data','somente o nome de uma pessoa'],ok:0,why:'A banca tende a cobrar compreensão contextual, não uma manchete isolada.'},
  {q:'Duas fontes independentes concordando sobre um fato tendem a:',choices:['aumentar a confiabilidade da informação','provar automaticamente qualquer interpretação','eliminar a necessidade de contexto','tornar a data irrelevante'],ok:0,why:'Confirmação independente fortalece a verificação, embora contexto continue necessário.'},
  {q:'Ao estudar uma notícia para prova, a pergunta “qual consequência?” serve para:',choices:['construir compreensão contextual','decorar ortografia','substituir a fonte','evitar relação causal'],ok:0,why:'Causa e consequência ajudam a transformar notícia em conhecimento cobrável.'}
 ]
};
function reinforcementQuestions(k,group){const arr=REINFORCEMENT_BANK[k]||[];return arr.slice(group*2,group*2+2);}
function reinforcementKey(group,i){return `${group}:${i}`;}
function reinforcementDone(group){const d=ensureDay(),qs=reinforcementQuestions(currentSubjectKey(),group);return qs.length===0||qs.every((_,i)=>d.reinforcementAnswers?.[reinforcementKey(group,i)]!==undefined);}
function reinforcementPage(group){const d=ensureDay();d.reinforcementPage=d.reinforcementPage||{};const qs=reinforcementQuestions(currentSubjectKey(),group);let page=Number(d.reinforcementPage[group]||0);if(page<0)page=0;if(page>=qs.length)page=Math.max(0,qs.length-1);return page;}
window.goReinforcementQuestion=function(group,i){const d=ensureDay(),qs=reinforcementQuestions(currentSubjectKey(),group);if(!qs.length)return;d.reinforcementPage=d.reinforcementPage||{};d.reinforcementPage[group]=Math.max(0,Math.min(qs.length-1,Number(i)||0));aesave();if(typeof renderMasterAll==='function')renderMasterAll();else uRenderToday();};
window.answerReinforcement=function(group,i,choice){const d=ensureDay(),qs=reinforcementQuestions(currentSubjectKey(),group),q=qs[i];if(!q)return;d.reinforcementAnswers=d.reinforcementAnswers||{};const key=reinforcementKey(group,i);if(d.reinforcementAnswers[key]!==undefined)return;d.reinforcementAnswers[key]=choice;const ok=choice===q.ok;recordQuestionPerformance(`reinforce-${group}`,i,ok);aesave();if(typeof renderMasterAll==='function')renderMasterAll();else uRenderToday();};
function bankReadingCue(q){const bm=(typeof bancaMethod==='function'?bancaMethod():{name:'sua banca'}),text=String(q?.q||'').toLowerCase(),alerts=[];if(/não|exceto|incorreta|errada|salvo/.test(text))alerts.push('⚠️ Há palavra que inverte o comando: leia duas vezes antes de marcar.');if(/correta|certo|adequad/.test(text))alerts.push('✅ O comando pede a alternativa compatível com a regra.');if(!alerts.length)alerts.push('🔎 Leia primeiro o comando e só depois compare as alternativas.');return `<div class="bank-reading-cue"><span>👁️ APRENDA A LER A ${bm.name.toUpperCase()}</span><p>${alerts.join(' ')}</p><ol><li><b>Comando:</b> descubra exatamente o que a questão pede.</li><li><b>Palavra decisiva:</b> procure NÃO, EXCETO, SEMPRE, SOMENTE, PODERÁ ou DEVERÁ.</li><li><b>Regra:</b> pense na regra antes de olhar qual alternativa "parece" certa.</li></ol></div>`;}
function reinforcementFeedback(q,ok){const snap=performanceSnapshot(),legal=isLegalSubjectKey(currentSubjectKey());return `<div class="reinforce-result ${ok?'feedback-ok':'feedback-bad'}"><b>${ok?'🎉 Parabéns! Mais um acerto.':'❌ Correção imediata'}</b><p>${ok?q.why:`<strong>Correta:</strong> ${q.choices[q.ok]}. ${q.why}`}</p>${legal&&q.basis?`<small>⚖️ ${q.basis}</small>`:''}${q.bank?`<small>🎯 ${q.bank}</small>`:''}${q.trap?`<small>⚠️ ${q.trap}</small>`:''}<div class="reinforce-score"><span>${snap.subject}% na matéria</span><span>${snap.today}% hoje</span><span>${snap.streak} em sequência</span></div></div>`;}
function reinforcementBlock(group){const d=ensureDay(),qs=reinforcementQuestions(currentSubjectKey(),group);if(!qs.length)return'';d.reinforcementAnswers=d.reinforcementAnswers||{};const page=reinforcementPage(group),q=qs[page],key=reinforcementKey(group,page),sel=d.reinforcementAnswers[key],answered=sel!==undefined,ok=answered&&sel===q.ok,last=page===qs.length-1,done=reinforcementDone(group);return `<section class="reinforcement-block"><div class="reinforce-head"><span>🎯 COMO A BANCA COBRA</span><h3>Treino de leitura • questão ${page+1} de ${qs.length}</h3><p>Uma questão por vez. Aprenda primeiro a ler o comando, depois marque.</p></div>${bankReadingCue(q)}<div class="reinforce-question single"><h4>${page+1}. ${q.q}</h4><div class="choice-grid compact">${q.choices.map((c,a)=>`<button class="choice ${answered?(a===q.ok?'choice-correct':sel===a?'choice-wrong':'choice-locked'):''}" ${answered?'disabled':''} onclick="answerReinforcement(${group},${page},${a})">${c}</button>`).join('')}</div>${answered?reinforcementFeedback(q,ok):'<p class="muted center">Marque uma alternativa para receber a correção imediatamente.</p>'}</div>${answered&&!last?`<button class="btn good full reinforce-next" onclick="goReinforcementQuestion(${group},${page+1})">Ir para a questão ${page+2} →</button>`:''}${answered&&last&&done?'<div class="reinforce-complete">✅ Treino de leitura concluído. Pode avançar.</div>':''}${page>0?`<button class="text-btn full" onclick="goReinforcementQuestion(${group},${page-1})">← Rever questão ${page}</button>`:''}${!done&&answered&&last?'<div class="reinforce-pending">Volte e conclua a questão anterior para liberar a próxima etapa.</div>':''}</section>`;}
window.reinforcementBlock=reinforcementBlock;
window.reinforcementDone=reinforcementDone;

const ENGINE_STAGES=[0,1,3,4,5,6,7,8,9,10];
function engineStageIndex(stage){const i=ENGINE_STAGES.indexOf(stage);return i<0?0:i;}
function markEngineStageReached(stage){const d=ensureDay(),i=engineStageIndex(stage);d.maxStageIndex=Math.max(Number(d.maxStageIndex||0),i);}
function syncEngineAnswer(d,stage){if(stage===1)d.answer=d.answers?.[0]??null;else if(stage===4)d.answer=d.answers?.[1]??null;}
function setEngineStage(s){const d=ensureDay();d.stage=s;syncEngineAnswer(d,s);markEngineStageReached(s);aesave();uRenderToday();}
function answerEngine(i){const d=ensureDay(),qidx=d.stage===4?1:0,q=currentSubject().questions[qidx];d.results=d.results||{};if(d.results[qidx])return;d.answer=i;d.answers=d.answers||{};d.answers[qidx]=i;const ok=i===q.ok;recordQuestionPerformance('engine',qidx,ok);d.results[qidx]={ok,qidx,chosen:i};d.lastResult=d.results[qidx];aesave();uRenderToday();}
function finalizeQuestion(qidx){const d=ensureDay(),chosen=d.answers?.[qidx]??d.answer;if(chosen===null||chosen===undefined)return;d.stage=qidx===0?3:5;markEngineStageReached(d.stage);aesave();uRenderToday();}
function gradeLearned(){const d=ensureDay(),sub=currentSubject(),txt=(document.getElementById('learnedText')?.value||'').trim();if(txt.length<12)return alert('Escreva pelo menos uma frase com suas palavras.');const low=txt.toLowerCase(),hits=sub.keywords.filter(k=>low.includes(k.split(' ')[0]));const score=Math.min(100,35+hits.length*13+(txt.length>80?12:0));d.learned=txt;d.learnedScore=score;ae.notes.unshift({date:new Date().toLocaleDateString('pt-BR'),subject:sub.name,text:txt,score});d.stage=7;markEngineStageReached(7);aesave();uRenderToday();}
function analyticsLeadIdentity(){return {name:u.profile?.name||'',email:u.profile?.email||'',phone:u.profile?.phone||'',marketing_consent:!!u.profile?.marketingConsent};}
function midTrialOffer(){return '';}
function trackForCatalogHit(hit){const blob=String([hit?.title,hit?.category,...(hit?.tags||[])].join(' ')).toLowerCase();if(!/oab|exame de ordem/.test(blob))return'concurso';const status=String(hit?.status||'').toLowerCase();return /1ª fase|1a fase|prova objetiva/.test(status)?'oab1':'oab2';}
function exactCatalogCourseById(id){return ((typeof aprovaCatalog!=='undefined'&&aprovaCatalog.items)||[]).find(x=>x.id===id)||null;}
function exactCatalogCourseByTitle(title){const n=(typeof norm==='function'?norm(title):String(title||'').trim().toLowerCase());return ((typeof aprovaCatalog!=='undefined'&&aprovaCatalog.items)||[]).find(x=>(typeof norm==='function'?norm(x.title):String(x.title||'').trim().toLowerCase())===n)||null;}
window.ensureExactCourseProfile=function(){
 const p=u.profile||{},byId=p.catalogId?exactCatalogCourseById(p.catalogId):null,byTitle=p.target?exactCatalogCourseByTitle(p.target):null;let hit=byTitle||byId;if(!hit)return null;
 const nextTrack=trackForCatalogHit(hit);
 const roleProfile=roleProfileForCourse(hit),savedRole=roleProfile?.roles?.find(r=>r.id===p.roleId)||null;
 const exact={...p,target:hit.title,banca:hit.banca||'',catalogId:hit.id,track:nextTrack,examDate:hit.exam_date||null,examDateSource:hit.exam_date?'official':null};
 u.profile=exact;applyCourseProfile(hit,savedRole);
 universalExam=hit.exam_date?new Date(hit.exam_date+'T13:00:00-03:00'):null;
 const changed=p.target!==u.profile.target||p.banca!==u.profile.banca||p.catalogId!==u.profile.catalogId||p.examDate!==u.profile.examDate||p.track!==u.profile.track||p.roleId!==u.profile.roleId||p.examStructure!==u.profile.examStructure;
 if(changed)usave();
 return hit;
};
window.applyExactCourseSelection=function(hit,{trial=false}={}){
 if(!hit)return false;const old=u.profile||{},changing=!!old.catalogId&&old.catalogId!==hit.id,selectedTrack=trackForCatalogHit(hit);
 u.profile={...old,track:selectedTrack,target:hit.title,banca:hit.banca||'',catalogId:hit.id,examDate:hit.exam_date||null,examDateSource:hit.exam_date?'official':null};
 applyCourseProfile(hit,null);
 universalExam=hit.exam_date?new Date(hit.exam_date+'T13:00:00-03:00'):null;
 if(!u.trial?.paid){delete u.profile.hours;u.profile.hoursConfigured=false;}
 if(changing||trial){ae.day={};ae.performance={};ae.notes=[];if(typeof mastery!=='undefined'){mastery.contest={};if(mastery.oab){mastery.oab.stage=0;mastery.oab.answer={};}if(typeof msave==='function')msave();}}
 usave();aesave();return true;
};
function nextSubject(){const d=ensureDay();if(d.index===0&&!u.trial?.paid){const firstComplete=!u.trial.firstStageCompleted;u.trial.firstStageCompleted=true;usave();if(firstComplete){if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('FreeStageComplete',{content_name:'Aprova - primeira etapa gratuita'});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('free_stage_complete',analyticsLeadIdentity());}if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('paywall_view',analyticsLeadIdentity());const pw=document.getElementById('paywall');if(pw)pw.hidden=false;return;}d.index++;d.stage=0;d.maxStageIndex=0;d.answer=null;d.answers={};d.results={};d.reinforcementAnswers={};d.learned='';d.learnedScore=null;aesave();uRenderAll();window.scrollTo({top:0,behavior:'smooth'});}
function restartTodayPlan(){ae.day={};aesave();ensureDay();uRenderAll();}

window.populateTrialCourseOptions=function(){
 const dl=document.getElementById('trialCourseOptions'),quick=document.getElementById('courseQuickChoices');if(!dl)return;
 let items=[];try{items=(typeof publicCatalogItems==='function'?publicCatalogItems():((typeof aprovaCatalog!=='undefined'&&aprovaCatalog.items)||[])).slice();}catch(e){}
 const uniq=new Map();items.forEach(x=>{if(x?.title&&!uniq.has(x.title))uniq.set(x.title,x);});
 dl.innerHTML=[...uniq.values()].slice(0,180).map(x=>`<option value="${htmlEsc(x.title)}">${htmlEsc(x.banca||'')}</option>`).join('');
 if(quick){const preferred=[...uniq.values()].filter(x=>/PC-BA|Exame de Ordem|Guarda Municipal|Polícia Civil/i.test(x.title)).slice(0,6);quick.innerHTML=preferred.map(x=>`<button type="button" onclick="pickTrialCourse('${String(x.id).replace(/'/g,"\\'")}')">${htmlEsc(x.title)}</button>`).join('');}
};
window.openCourseChooser=function(){
 const gate=document.getElementById('courseGate');if(!gate)return startFreeTrial();
 const input=document.getElementById('trialCourseSearch');if(input){input.value='';input.dataset.courseId='';}
 populateTrialCourseOptions();gate.hidden=false;document.body.classList.add('modal-open');setTimeout(()=>input?.focus(),60);
};
window.closeCourseChooser=function(){const gate=document.getElementById('courseGate');if(gate)gate.hidden=true;document.body.classList.remove('modal-open');};
window.pickTrialCourse=function(id){const x=exactCatalogCourseById(id),input=document.getElementById('trialCourseSearch');if(x&&input){input.value=x.title;input.dataset.courseId=x.id;}};
window.openRoleChooser=function(hit,profile){const course=document.getElementById('courseGate'),gate=document.getElementById('roleGate'),box=document.getElementById('roleChoices'),title=document.getElementById('roleGateTitle'),sub=document.getElementById('roleGateSubtitle');if(!gate||!box)return false;u.trial=u.trial||{};u.trial.pendingCourseId=hit.id;if(title)title.textContent='Qual cargo você vai disputar?';if(sub)sub.textContent=`${hit.title} • ${hit.banca}. Escolha o cargo para carregar somente as matérias e a estrutura correspondentes.`;box.innerHTML=profile.roles.map(r=>`<button type="button" onclick="selectTrialRole('${hit.id}','${r.id}')"><b>${htmlEsc(r.label)}</b><small>Ver matérias deste cargo →</small></button>`).join('');if(course)course.hidden=true;gate.hidden=false;return true;};
window.backToCourseChooser=function(){const r=document.getElementById('roleGate'),c=document.getElementById('courseGate');if(r)r.hidden=true;if(c)c.hidden=false;};
window.selectTrialRole=function(courseId,roleId){const hit=((typeof aprovaCatalog!=='undefined'?aprovaCatalog.items:[])||[]).find(x=>x.id===courseId),profile=hit&&roleProfileForCourse(hit),role=profile?.roles?.find(r=>r.id===roleId);if(!hit||!role)return alert('Cargo não encontrado. Escolha novamente.');const selectedTrack=trackForCatalogHit(hit);u.profile={...(u.profile||{}),track:selectedTrack,target:hit.title,banca:hit.banca||'',catalogId:hit.id,examDate:hit.exam_date||null,examDateSource:hit.exam_date?'official':null};applyCourseProfile(hit,role);if(hit.exam_date)universalExam=new Date(hit.exam_date+'T13:00:00-03:00');else universalExam=null;u.trial=u.trial||{};u.trial.courseChosenAt=Date.now();u.trial.courseChosenTitle=hit.title;u.trial.firstStageCompleted=false;u.trial.leadCaptured=false;u.trial.previewStartedAt=0;u.trial.startedAt=0;ae.day={};aesave();usave();if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_course_selected',{target:hit.title,banca:hit.banca||'',track:u.profile.track,catalog_id:hit.id,role:role.label||''});const rg=document.getElementById('roleGate');if(rg)rg.hidden=true;closeCourseChooser();startFreeTrial();};

window.confirmTrialCourse=function(){
 const input=document.getElementById('trialCourseSearch'),raw=(input?.value||'').trim();if(!raw)return alert('Escolha a prova, órgão ou cargo para iniciar o teste.');
 const hit=(input?.dataset?.courseId?exactCatalogCourseById(input.dataset.courseId):null)||exactCatalogCourseByTitle(raw);
 if(!hit)return alert('Escolha uma opção exata do catálogo. Assim o Aprova carrega a banca, a estrutura e as questões corretas sem misturar concursos.');
 const roleProfile=roleProfileForCourse(hit);
 if(roleProfile?.roles?.length){applyExactCourseSelection(hit,{trial:true});usave();return openRoleChooser(hit,roleProfile);}
 if(isMunicipalUmbrella(hit))return alert('Os cargos deste concurso ainda estão em validação oficial. O Aprova não vai adivinhar matérias nem misturar conteúdos de outro cargo.');
 applyExactCourseSelection(hit,{trial:true});
 u.trial=u.trial||{};u.trial.courseChosenAt=Date.now();u.trial.courseChosenTitle=hit.title;if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_course_selected',{target:hit.title,banca:hit.banca||'',track:u.profile.track,catalog_id:hit.id,role:u.profile.role||''});u.trial.firstStageCompleted=false;u.trial.leadCaptured=false;u.trial.previewStartedAt=0;u.trial.startedAt=0;
 usave();closeCourseChooser();startFreeTrial();
};

window.startFreeTrial=function(){
 const params=new URLSearchParams(location.search);
 const requested=params.get('track');
 const allowed=new Set(['concurso','oab2','oab1','magistratura','saude','educacao','certificacao','outro']);
 const old=u.profile||{};
 if(!u.trial?.courseChosenAt||!old.target){openCourseChooser();return;}
 const track=old.track||((allowed.has(requested)&&requested)||'concurso');
 const firstPreview=!u.trial?.previewStartedAt;
 u.profile={...old,track,target:old.target,area:track==='oab2'?'constitucional':(old.area||'geral'),name:old.name||'',email:old.email||'',phone:old.phone||'',marketingConsent:!!old.marketingConsent,banca:old.banca||''};
 u.sessionLoggedOut=false;sessionStorage.setItem('aprova-trial-active','1');u.trial.startedAt=u.trial.startedAt||Date.now();u.trial.previewStartedAt=u.trial.previewStartedAt||Date.now();u.trial.mode='first-stage';
 if(firstPreview){u.trial.firstStageCompleted=false;u.trial.leadCaptured=!!old.phone;ae.day={};if(typeof mastery!=='undefined'&&mastery?.oab)mastery.oab.stage=0;if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('StartTrialPreview',{content_name:'Aprova - inicio do teste',content_category:track});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_preview_start',{track,target:u.profile.target});}
 usave();aesave();const gate=document.getElementById('trialGate');if(gate)gate.hidden=true;uRenderAll();if(typeof renderMasterAll==='function')renderMasterAll();const welcome=document.getElementById('trialWelcome');if(welcome)welcome.hidden=false;window.scrollTo({top:0,behavior:'smooth'});
};
window.continueTrialWelcome=function(){const welcome=document.getElementById('trialWelcome');if(welcome)welcome.hidden=true;if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_welcome_continue',{track:u.profile?.track||'',target:u.profile?.target||''});window.scrollTo({top:0,behavior:'smooth'});};

window.requireTrialLeadCapture=function(flow,nextStage){
 if(u.trial?.paid||u.trial?.leadCaptured)return false;
 u.trial.pendingLeadFlow=flow||'contest';u.trial.pendingLeadStage=Number(nextStage)||3;usave();
 const gate=document.getElementById('leadGate');if(!gate)return false;
 const p=document.getElementById('leadPhone');if(p)p.value=(u.profile?.phone||'').replace(/^\+55/,'');
 gate.hidden=false;
 if(!u.trial.leadGateTracked){u.trial.leadGateTracked=true;usave();if(typeof window.aprovaTrackCustom==='function')window.aprovaTrackCustom('LeadGateView',{content_name:'Aprova - tres etapas concluidas'});if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('lead_gate_view',{track:u.profile?.track||'',target:u.profile?.target||'',after_steps:3});}
 return true;
};
window.closeTrialLead=function(){const gate=document.getElementById('leadGate');if(gate)gate.hidden=true;};
window.captureTrialLead=function(){
 const phoneRaw=(document.getElementById('leadPhone')?.value||'').trim(),digits=phoneRaw.replace(/\D/g,''),national=digits.replace(/^55(?=\d{10,11}$)/,''),phone='+55'+national;
 if(national.length<10||national.length>11)return alert('Informe um WhatsApp válido com DDD.');
 u.profile={...(u.profile||{}),phone,email:u.profile?.email||'',marketingConsent:false};u.trial.leadCaptured=true;u.trial.leadCapturedAt=u.trial.leadCapturedAt||Date.now();
 const flow=u.trial.pendingLeadFlow||'contest',next=Number(u.trial.pendingLeadStage)||3;delete u.trial.pendingLeadFlow;delete u.trial.pendingLeadStage;
 if(!u.trial.leadEventTracked){u.trial.leadEventTracked=true;if(typeof window.aprovaTrack==='function'){window.aprovaTrack('Lead',{content_name:'Aprova - WhatsApp apos 3 etapas',content_category:u.profile?.track||''});window.aprovaTrack('CompleteRegistration',{content_name:'Aprova - teste continuado',content_category:u.profile?.track||'',status:true});}if(typeof window.aprovaAnalytics==='function')window.aprovaAnalytics('trial_lead',{...analyticsLeadIdentity(),track:u.profile?.track||'',target:u.profile?.target||'',after_steps:3});}
 usave();const gate=document.getElementById('leadGate');if(gate)gate.hidden=true;
 if(flow==='oab'&&typeof setOabStage==='function')setOabStage(next);else if(flow==='contest'&&typeof setContestStage==='function')setContestStage(next);else if(typeof setEngineStage==='function')setEngineStage(next);
};

function summaryStep(sub){return `<div class="do-now">BLOCO ${ensureDay().index+1} DE ${ensureDay().queue.length} • ${sub.icon} ${sub.name}</div><h2>Resumo de 30 segundos</h2><div class="micro-summary" style="border-left-color:${sub.color}">${sub.summary}</div><p class="muted">Leia uma vez. O objetivo agora é usar a informação numa questão.</p><button class="btn good nextbtn" onclick="setEngineStage(1)">Ir para a questão →</button>`;}
function questionStep(sub,idx){const d=ensureDay(),q=sub.questions[idx],selected=d.answers?.[idx]??d.answer,result=d.results?.[idx];return `<div class="do-now">QUESTÃO ${idx+1} DE 2 • ${sub.name}</div><h2>${q.q}</h2><div class="choice-grid">${q.choices.map((c,i)=>`<button class="choice ${selected===i?'selected':''} ${result?(i===q.ok?'choice-correct':selected===i?'choice-wrong':'choice-locked'):''}" ${result?'disabled':''} onclick="answerEngine(${i})">${c}</button>`).join('')}</div>${result?buildQuestionFeedback(sub,idx,result.ok,true):''}${result?`<button class="btn good nextbtn" onclick="finalizeQuestion(${idx})">Continuar →</button>`:'<p class="muted center">Toque em uma alternativa para receber a correção imediatamente.</p>'}`;}
function feedbackStep(sub,idx,next){const d=ensureDay(),result=d.results?.[idx]||d.lastResult,ok=!!result?.ok,offer=idx===0?midTrialOffer(d,next):'';return `<div class="do-now">CORREÇÃO + FIXAÇÃO</div>${buildQuestionFeedback(sub,idx,ok,false)}<p class="muted">A correção imediata evita consolidar uma resposta errada e transforma o erro em pista de memória.</p>${offer||`<button class="btn good nextbtn" onclick="setEngineStage(${next})">${idx===0?'Próxima questão':'Continuar'} →</button>`}`;}
function htmlEsc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function learnedStep(sub){const d=ensureDay();return `<div class="do-now">RECUPERAÇÃO ATIVA • ${sub.name}</div><h2>Escreva o que você aprendeu</h2><p class="muted">Sem copiar. Explique como se estivesse ensinando alguém em 2 ou 3 frases.</p><textarea id="learnedText" rows="5" placeholder="Hoje eu aprendi que...">${htmlEsc(d.learned||'')}</textarea><button class="btn good nextbtn" onclick="gradeLearned()">Corrigir meu entendimento →</button>`;}
function learnedFeedback(sub){const d=ensureDay(),score=d.learnedScore||0,missing=sub.keywords.filter(k=>!d.learned.toLowerCase().includes(k.split(' ')[0])).slice(0,3);return `<div class="do-now">CORREÇÃO DO QUE VOCÊ APRENDEU</div><h2>${score>=75?'✅ Boa explicação':score>=55?'🟡 Está no caminho':'🔁 Reforce antes de seguir'}</h2><div class="score-ring">${score}<small>/100</small></div><p><b>Sua explicação:</b> ${d.learned}</p>${missing.length?`<div class="callout"><b>Para ficar mais completa, revise:</b> ${missing.join(', ')}.</div>`:'<div class="callout"><b>Você cobriu os pontos-chave deste bloco.</b></div>'}<button class="btn good nextbtn" onclick="setEngineStage(8)">Fazer perguntas de memória →</button>`;}
function recallStep(sub){return `<div class="do-now">PERGUNTAS DE MEMÓRIA</div><h2>Responda mentalmente antes de abrir</h2>${sub.flash.map((f,i)=>`<details class="flash recall-card"><summary>${i+1}. ${f[0]}</summary><p><b>${f[1]}</b></p></details>`).join('')}<button class="btn good nextbtn" onclick="setEngineStage(9)">Gerar flashcards →</button>`;}
function coloredFlashStep(sub){return `<div class="do-now">FLASHCARDS COLORIDOS</div><h2>Fixação visual</h2><div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash" style="background:${i%2?sub.color:'#FFF59D'}"><small>${sub.icon} ${sub.name}</small><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div><p class="muted">As cores criam pistas visuais para facilitar a recuperação depois.</p><button class="btn good nextbtn" onclick="setEngineStage(10)">Finalizar matéria →</button>`;}
function finishStep(sub){const d=ensureDay(),done=d.index+1>=d.queue.length;return `<div class="donehero"><div class="checkbig">✓</div><h2>${sub.name} concluído</h2><p>${d.index===0&&!u.trial?.paid?'Sua primeira etapa gratuita foi concluída.':'A próxima matéria já foi escolhida automaticamente.'}</p><div class="finish-actions"><button class="btn secondary" onclick="speakStudySummary()">🔊 Ouvir resumo</button><button class="btn secondary" onclick="generateUniversalPDF()">📄 Gerar PDF</button>${done?'<button class="btn good" onclick="restartTodayPlan()">Recalcular novo ciclo</button>':'<button class="btn good" onclick="nextSubject()">Continuar para a próxima matéria →</button>'}</div></div>`;}
function engineCanAdvance(){const d=ensureDay(),s=d.stage||0;if(s===1)return d.answers?.[0]!==undefined;if(s===4)return d.answers?.[1]!==undefined;return true;}
function engineNav(){const d=ensureDay(),idx=engineStageIndex(d.stage||0),prev=idx>0,final=idx===ENGINE_STAGES.length-1,nextOk=engineCanAdvance();return `<div class="stage-nav"><button class="stage-arrow" ${prev?'onclick="enginePrevStage()"':'disabled'} aria-label="Voltar para a etapa anterior">← <span>Etapa anterior</span></button><div class="stage-position">${idx+1}/${ENGINE_STAGES.length}</div><button class="stage-arrow stage-arrow-next" ${nextOk?'onclick="engineNextStage()"':'disabled'} aria-label="Seguir para a próxima etapa"><span>${final?'Próxima matéria':'Próxima etapa'}</span> →</button></div>`;}
window.enginePrevStage=function(){const d=ensureDay(),idx=engineStageIndex(d.stage||0);if(idx<=0)return;d.stage=ENGINE_STAGES[idx-1];syncEngineAnswer(d,d.stage);aesave();uRenderToday();window.scrollTo({top:0,behavior:'smooth'});};
window.engineNextStage=function(){const d=ensureDay(),s=d.stage||0;if(s===0)return setEngineStage(1);if(s===1)return finalizeQuestion(0);if(s===3)return setEngineStage(4);if(s===4)return finalizeQuestion(1);if(s===5)return setEngineStage(6);if(s===6)return gradeLearned();if(s===7)return setEngineStage(8);if(s===8)return setEngineStage(9);if(s===9)return setEngineStage(10);return nextSubject();};
window.logoutAprova=function(){if(!confirm('Deseja sair? Seu progresso continuará salvo neste aparelho.'))return;if('speechSynthesis'in window)speechSynthesis.cancel();if(typeof window.hasAprovaPaidSession==='function'&&window.hasAprovaPaidSession()&&typeof window.logoutPaidAccount==='function')return window.logoutPaidAccount();u.sessionLoggedOut=true;sessionStorage.removeItem('aprova-trial-active');usave();const pw=document.getElementById('paywall');if(pw)pw.hidden=true;const lg=document.getElementById('leadGate');if(lg)lg.hidden=true;const gate=document.getElementById('trialGate');if(gate)gate.hidden=false;window.scrollTo({top:0,behavior:'smooth'});};
function guidedEngineStep(){const d=ensureDay(),sub=currentSubject(),s=d.stage||0;let body;if(s===0)body=summaryStep(sub);else if(s===1)body=questionStep(sub,0);else if(s===3)body=feedbackStep(sub,0,4);else if(s===4)body=questionStep(sub,1);else if(s===5)body=feedbackStep(sub,1,6);else if(s===6)body=learnedStep(sub);else if(s===7)body=learnedFeedback(sub);else if(s===8)body=recallStep(sub);else if(s===9)body=coloredFlashStep(sub);else body=finishStep(sub);return body+engineNav();}

window.speakStudySummary=function(){const sub=currentSubject(),notes=ae.notes.slice(0,4).map(n=>`${n.subject}: ${n.text}`).join('. '),txt=`Resumo de revisão. ${sub.name}. ${sub.summary}. ${sub.flash.map(f=>f[0]+': '+f[1]).join('. ')}. ${notes?'Suas anotações recentes: '+notes:''}`;if(!('speechSynthesis'in window))return alert('Seu navegador não oferece leitura em voz alta.');speechSynthesis.cancel();const ut=new SpeechSynthesisUtterance(txt);ut.lang='pt-BR';ut.rate=.95;speechSynthesis.speak(ut);};
window.stopStudyAudio=function(){if('speechSynthesis'in window)speechSynthesis.cancel();};

window.uRenderToday=function(){const d=ensureDay(),sub=currentSubject(),studyLabel=u.trial?.paid&&u.profile?.hoursConfigured?`${u.profile.hours}h/dia`:'Aula teste';document.getElementById('hoje').innerHTML=`<div class="study-day-head"><div><span class="pill">PLANO AUTOMÁTICO DE HOJE</span><h2>${studyLabel} • ${d.queue.length} bloco(s) programado(s)</h2><p class="muted">Banca: <b>${u.profile.banca||'perfil do cargo'}</b> • o sistema escolhe as matérias e você pode escolher por qual começar.</p></div><div class="kpi">${d.index+1}/${d.queue.length}<small>bloco atual</small></div></div><div class="guide-layout"><div class="card guide-main">${startSubjectChooser()}${guidedEngineStep()}</div><aside class="card guide-side"><h3>Matérias de hoje</h3>${d.queue.map((k,i)=>{const x=SUBJECTS[k];return `<div class="queue-item ${i===d.index?'queue-active':''} ${i<d.index?'queue-done':''}"><span class="queue-dot" style="background:${x.color}"></span><span><b>${x.name}</b><small>${x.minutes} min</small></span>${i<d.index?'✓':i===d.index?'AGORA':''}</div>`}).join('')}<hr><p class="muted">Você escolhe a primeira matéria. Depois, o sistema continua a sequência e adapta os próximos ciclos conforme seus erros e acertos.</p><button class="btn secondary full" onclick="speakStudySummary()">🔊 Ouvir revisão</button></aside></div>`;};

window.uRenderSchedule=function(){const left=udays(),w=weightsForUser(),sorted=Object.entries(w).filter(([k])=>SUBJECTS[k]).sort((a,b)=>b[1]-a[1]);const blocks=dailyBlocks();document.getElementById('cronograma').innerHTML=`<div class="card"><div class="auto-calendar-head"><div><h2>Seu calendário automático</h2><p class="muted">${u.profile.hours||2}h por dia • ${blocks} blocos/dia • recalculado conforme desempenho e dias restantes.</p></div><div class="kpi">${left}<small>dias até a prova</small></div></div><h3>Prioridade atual das matérias</h3>${sorted.map(([k,v],i)=>{const s=SUBJECTS[k],mx=sorted[0][1];return `<div class="priority-row"><span class="queue-dot" style="background:${s.color}"></span><b>${s.name}</b><div class="priority-bar"><i style="width:${Math.round(v/mx*100)}%;background:${s.color}"></i></div><span>${i<3?'alta':i<6?'média':'apoio'}</span></div>`}).join('')}<div class="calendar-note">A ordem não é fixa: erros aumentam a frequência da matéria; alto desempenho libera espaço para outras disciplinas.</div></div>`;};

window.uRenderQuestions=function(){const sub=currentSubject(),p=ae.performance;document.getElementById('questoes').innerHTML=`<div class="card"><h2>Questões guiadas pela prioridade</h2><p>Você não precisa escolher um filtro. O sistema entrega a próxima questão conforme cargo, banca e desempenho.</p><div class="qbox"><span class="pill">AGORA</span><h3>${sub.icon} ${sub.name}</h3><p>${sub.summary}</p><button class="btn good" onclick="document.querySelector('[data-tab=&quot;hoje&quot;]')?.click()">Continuar estudo guiado →</button></div><h3>Seu desempenho</h3>${Object.keys(p).length?Object.entries(p).map(([k,x])=>`<div class="priority-row"><span class="queue-dot" style="background:${SUBJECTS[k]?.color||'#ddd'}"></span><b>${SUBJECTS[k]?.name||k}</b><span>${x.correct}/${x.total} acertos</span></div>`).join(''):'<p class="muted">Resolva as primeiras questões para o sistema começar a se adaptar.</p>'}</div>`;};

window.uRenderReview=function(){const notes=ae.notes.slice(0,8),sub=currentSubject();document.getElementById('revisao').innerHTML=`<div class="grid"><div class="card span-8"><h2>Revisão inteligente</h2><p class="muted">Suas próprias explicações viram material de revisão.</p>${notes.length?notes.map(n=>`<div class="note-line"><b>${n.subject}</b> <span class="pill">${n.score}/100</span><br>${n.text}</div>`).join(''):'<div class="callout">Conclua um bloco para criar sua primeira revisão.</div>'}<h3 style="margin-top:18px">Flashcards coloridos do bloco atual</h3><div class="color-flash-grid">${sub.flash.map((f,i)=>`<article class="color-flash" style="background:${i%2?sub.color:'#FFF59D'}"><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join('')}</div></div><div class="card span-4"><h3>Leve a revisão com você</h3><button class="btn good full" onclick="generateUniversalPDF()">📄 Gerar resumo em PDF</button><button class="btn secondary full smallgap" onclick="speakStudySummary()">🔊 Ouvir resumo</button><button class="text-btn full" onclick="stopStudyAudio()">Parar áudio</button></div></div>`;};

window.generateUniversalPDF=function(){if(!(window.jspdf&&window.jspdf.jsPDF))return alert('Gerador carregando. Tente novamente em instantes.');const {jsPDF}=window.jspdf,doc=new jsPDF(),d=ensureDay();let y=16;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Resumo de revisão — Aprova',14,y);y+=9;doc.setFontSize(11);doc.text(`${u.profile.target||'Minha prova'} | ${u.profile.hours||2}h/dia`,14,y);y+=10;const used=[...new Set(d.queue.slice(0,Math.min(d.index+1,d.queue.length)))];used.forEach(k=>{const s=SUBJECTS[k];if(y>250){doc.addPage();y=16;}doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(s.name,15,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);const lines=doc.splitTextToSize(s.summary,178);doc.text(lines,15,y);y+=lines.length*4+4;s.flash.forEach(f=>{doc.setFont('helvetica','bold');doc.text('• '+f[0],15,y);y+=4;doc.setFont('helvetica','normal');const a=doc.splitTextToSize(f[1],174);doc.text(a,19,y);y+=a.length*4+3;});});if(ae.notes.length){if(y>230){doc.addPage();y=16;}doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('O que eu aprendi',14,y);y+=7;ae.notes.slice(0,6).forEach(n=>{const t=doc.splitTextToSize(`${n.subject}: ${n.text}`,180);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(t,15,y);y+=t.length*4+4;});}doc.save('aprova-resumo-revisao.pdf');};

const oldSelectCatalogItem=window.selectCatalogItem;
window.selectCatalogItem=function(id){const x=exactCatalogCourseById(id);if(!x)return oldSelectCatalogItem&&oldSelectCatalogItem(id);applyExactCourseSelection(x,{trial:false});u.trial=u.trial||{};u.trial.courseChosenAt=Date.now();u.trial.courseChosenTitle=x.title;usave();uRenderAll();document.querySelector('[data-tab="hoje"]')?.click();};

window.uRenderAll=function(){ensureExactCourseProfile();universalExam=u.profile.examDate?new Date(u.profile.examDate+'T13:00:00-03:00'):null;const title=document.getElementById('areaTitle'),eye=document.getElementById('examEyebrow');if(title)title.textContent=u.profile.target||'Sua próxima aprovação';if(eye)eye.textContent=`${u.profile.banca||trackLabels[u.profile.track]||'PLANO INTELIGENTE'} • ESTUDO GUIADO`;uRenderToday();uRenderSchedule();uRenderContent();uRenderMaterial();uRenderQuestions();uRenderSim();uRenderReview();uRenderErrors();uCountdown();const p=document.getElementById('progressText');if(p){const d=ensureDay();p.textContent=`Hoje: ${Math.min(d.index+1,d.queue.length)}/${d.queue.length} blocos`;}};
if(u?.profile?.name){ensureDay();uRenderAll();}
