const ULS='aprova-universal-v4';
let u=JSON.parse(localStorage.getItem(ULS)||'{}');
u.profile=u.profile||{};u.trial=u.trial||{};u.notes=u.notes||[];u.errors=u.errors||[];u.reviews=u.reviews||[];u.flashRatings=u.flashRatings||{};u.stage=u.stage||0;u.choice=u.choice||'';
const trackLabels={concurso:'Concurso público',oab2:'OAB — 2ª fase',oab1:'OAB — 1ª fase',magistratura:'ENAM / Carreiras Jurídicas',saude:'Residência / Saúde',educacao:'ENEM / Vestibular',certificacao:'Certificação / Exame profissional',outro:'Outra prova'};
const areaLabels={geral:'Plano geral do edital',constitucional:'Direito Constitucional',administrativo:'Direito Administrativo',civil:'Direito Civil',empresarial:'Direito Empresarial',penal:'Direito Penal',processopenal:'Processo Penal',trabalho:'Direito do Trabalho',tributario:'Direito Tributário',portugues:'Português',informatica:'Informática',raciocinio:'Raciocínio Lógico / Estatística'};
let universalExam=u.profile.examDate?new Date(u.profile.examDate+'T13:00:00-03:00'):null;
let trialTicker=null;
function usave(){localStorage.setItem(ULS,JSON.stringify(u));}
function targetName(){return u.profile.target||trackLabels[u.profile.track]||'Sua prova';}
function udays(){if(!universalExam||Number.isNaN(universalExam.getTime()))return null;return Math.max(0,Math.ceil((universalExam-new Date())/86400000));}
function updateTrackFields(){const t=document.getElementById('trialTrack')?.value,a=document.getElementById('trialArea');if(!a)return;if(t==='oab2')a.value='constitucional';else if(t==='concurso')a.value='geral';}
function findCatalogTarget(target){const n=typeof norm==='function'?norm(target):(target||'').toLowerCase();return window.aprovaCatalog?.items?.find(x=>{const vals=[x.title,...(x.tags||[])].map(v=>typeof norm==='function'?norm(v):(v||'').toLowerCase());return vals.includes(n)||vals.some(v=>n&&v.includes(n))||vals.some(v=>v&&n.includes(v));})||null;}
function applyOfficialExamMeta(target){const hit=findCatalogTarget(target);if(hit){u.profile.banca=hit.banca||u.profile.banca||'';u.profile.catalogId=hit.id;if(hit.exam_date){u.profile.examDate=hit.exam_date;u.profile.examDateSource='official';universalExam=new Date(hit.exam_date+'T13:00:00-03:00');const input=document.getElementById('trialExamDate');if(input)input.value=hit.exam_date;}}return hit;}
function syncOfficialExamDate(){if(!u.profile?.target)return false;const hit=applyOfficialExamMeta(u.profile.target);if(hit){usave();return true;}return false;}
function startFreeTrial(){const name=document.getElementById('trialName').value.trim(),email=document.getElementById('trialEmail').value.trim(),track=document.getElementById('trialTrack').value,target=document.getElementById('trialTarget').value.trim(),area=document.getElementById('trialArea').value,manualDate=document.getElementById('trialExamDate').value;if(!name||!email)return alert('Preencha nome e e-mail.');u.profile={name,email,track,target:target||trackLabels[track],area,examDate:manualDate||null};const hit=applyOfficialExamMeta(u.profile.target);if(!hit&&manualDate){u.profile.examDate=manualDate;u.profile.examDateSource='manual';universalExam=new Date(manualDate+'T13:00:00-03:00');}else if(!hit&&!manualDate){u.profile.examDate=null;u.profile.examDateSource='unknown';universalExam=null;}u.sessionLoggedOut=false;u.trial.startedAt=u.trial.startedAt||Date.now();u.trial.mode='first-stage';u.trial.firstStageCompleted=!!u.trial.firstStageCompleted;usave();document.getElementById('trialGate').hidden=true;uRenderAll();}
function startTrialClock(){}
function restoreTrialUniversal(){if(u.sessionLoggedOut)return;if(!u.trial.startedAt)return;document.getElementById('trialGate').hidden=true;}
const PAYMENT_API='https://aprova-payments-production.up.railway.app';
async function goToCheckout(mode='card'){
 try{
  const price=mode==='pix'?179.90:199.90;
  if(typeof window.aprovaTrack==='function')window.aprovaTrack('InitiateCheckout',{content_name:'Aprova - acesso completo',content_category:mode,value:price,currency:'BRL'});
  const res=await fetch(PAYMENT_API+'/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,email:u.profile?.email||'',name:u.profile?.name||''})});
  const data=await res.json().catch(()=>({}));
  if(!res.ok||!data.checkout_url)throw new Error(data.error||'Checkout indisponível.');
  localStorage.setItem('aprova-pending-order',data.order_id||'');
  localStorage.setItem('aprova-pending-mode',mode);
  window.location.href=data.checkout_url;
 }catch(err){alert((err&&err.message)||'Não foi possível abrir o Mercado Pago agora. Tente novamente em instantes.');}
}
async function verifyAprovaPayment(showPending=false){
 const orderId=localStorage.getItem('aprova-pending-order');
 if(!orderId)return false;
 try{
  const res=await fetch(PAYMENT_API+'/order?id='+encodeURIComponent(orderId),{cache:'no-store'});
  const data=await res.json().catch(()=>({}));
  if(data.approved){
   u.trial=u.trial||{};u.trial.paid=true;u.trial.paidAt=Date.now();u.trial.orderId=orderId;usave();
   localStorage.removeItem('aprova-pending-order');localStorage.removeItem('aprova-pending-mode');
   const pw=document.getElementById('paywall');if(pw)pw.hidden=true;
   if(typeof window.aprovaTrack==='function')window.aprovaTrack('Purchase',{content_name:'Aprova - acesso completo',value:Number(data.total_amount||0),currency:'BRL'});
   history.replaceState({},document.title,location.pathname);
   alert('Pagamento confirmado. Seu acesso completo foi liberado.');
   return true;
  }
  if(showPending)alert('Pagamento ainda não confirmado. Se você acabou de pagar por Pix, aguarde alguns segundos e tente novamente.');
 }catch(e){if(showPending)alert('Não foi possível confirmar o pagamento agora. Tente novamente em instantes.');}
 return false;
}
async function handleAprovaPaymentReturn(){
 const state=new URLSearchParams(location.search).get('mp');
 if(!state||u.trial?.paid)return;
 if(state==='failure'){alert('O pagamento não foi concluído. Você pode tentar novamente.');history.replaceState({},document.title,location.pathname);return;}
 for(let i=0;i<6;i++){
  if(await verifyAprovaPayment(false))return;
  if(i<5)await new Promise(r=>setTimeout(r,2500));
 }
 if(state==='pending'||state==='success')alert('Recebemos o retorno do Mercado Pago, mas a confirmação ainda está pendente. Seu progresso está salvo; tente verificar novamente em alguns instantes.');
}
window.verifyAprovaPayment=()=>verifyAprovaPayment(true);
function closePaywallPreview(){document.getElementById('paywall').hidden=true;}
const guides={
 geral:{title:'Diagnóstico guiado',q:'Antes de estudar teoria, qual é a melhor primeira ação para descobrir como sua prova cobra o conteúdo?',choices:['Resolver uma questão diagnóstica','Ler todo o edital de uma vez','Comprar vários cursos','Memorizar resumos sem questões'],ok:'Resolver uma questão diagnóstica',why:'O diagnóstico revela padrão da prova e lacunas antes de distribuir seu tempo.',steps:['Resolva sem consultar','Corrija imediatamente','Classifique o erro','Transforme o erro em flashcard'],note:'Questão → correção → fonte → anotação → flashcard → revisão.',flash:[['Qual é o ciclo-base?','Questão → correção → fonte → anotação → flashcard → revisão'],['O que fazer com um erro?','Entender a causa e agendar revisão']]},
 constitucional:{title:'Questão guiada — Constitucional',q:'Qual alternativa contém apenas princípios expressos no caput do art. 37 da Constituição?',choices:['Legalidade, impessoalidade, moralidade, publicidade e eficiência','Legalidade, razoabilidade, proporcionalidade, publicidade e eficiência','Moralidade, autotutela, publicidade, eficiência e supremacia','Legalidade, motivação, segurança jurídica, publicidade e eficiência'],ok:'Legalidade, impessoalidade, moralidade, publicidade e eficiência',why:'O art. 37, caput, traz os princípios LIMPE.',steps:['Abra a Constituição Federal','Localize o art. 37, caput','Leia os princípios expressos','Compare com as alternativas'],note:'LIMPE = Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.',flash:[['Quais são os princípios expressos do art. 37?','Legalidade, impessoalidade, moralidade, publicidade e eficiência'],['Qual mnemônico ajuda?','LIMPE']]},
 portugues:{title:'Questão guiada — Português',q:'Na frase “Os candidatos que estudam com constância evoluem”, o “que” introduz qual tipo de oração?',choices:['Subordinada adjetiva','Subordinada substantiva','Coordenada sindética','Oração reduzida'],ok:'Subordinada adjetiva',why:'O “que” retoma “candidatos” e introduz oração com valor adjetivo.',steps:['Revise pronomes relativos','Localize oração subordinada adjetiva','Compare restritiva x explicativa','Crie um exemplo próprio'],note:'Se “que” retoma substantivo anterior e o caracteriza, avalie oração adjetiva.',flash:[['O que caracteriza oração subordinada adjetiva?','Ela exerce função de adjetivo'],['O “que” pode funcionar como quê?','Pronome relativo']]},
 informatica:{title:'Questão guiada — Informática',q:'Qual prática reduz o impacto do comprometimento de uma única senha?',choices:['Autenticação multifator','Desativar atualizações','Reutilizar a mesma senha','Compartilhar credenciais'],ok:'Autenticação multifator',why:'A MFA exige mais de um fator de autenticação.',steps:['Revise autenticação x autorização','Leia sobre fatores de autenticação','Compare senha x MFA','Anote um exemplo de 2FA'],note:'MFA combina dois ou mais fatores independentes.',flash:[['O que significa MFA?','Autenticação multifator'],['Qual o principal ganho?','Reduzir o risco quando um fator é comprometido']]}
};
function currentGuide(){return guides[u.profile.area]||guides.geral;}
function scheduleReview(days,topic){const d=new Date();d.setDate(d.getDate()+days);const due=d.toISOString().slice(0,10);if(!u.reviews.some(r=>r.due===due&&r.topic===topic))u.reviews.push({topic,due,done:false});}
function flashHtml(f,i){const r=u.flashRatings[i]||'';return `<details class="flash"><summary>${f[0]}</summary><p><b>${f[1]}</b></p><div class="reviewchips"><button class="btn secondary" onclick="rateFlash(event,${i},'erro')">Errei</button><button class="btn secondary" onclick="rateFlash(event,${i},'duvida')">Tive dúvida</button><button class="btn good" onclick="rateFlash(event,${i},'facil')">Acertei fácil</button></div>${r?`<small class="muted">Classificação: ${r}</small>`:''}</details>`;}
function rateFlash(e,i,r){e.preventDefault();u.flashRatings[i]=r;scheduleReview(r==='erro'?1:r==='duvida'?3:7,`Flashcard ${i+1}: ${currentGuide().flash[i][0]}`);usave();uRenderToday();uRenderReview();}
function chooseUniversal(v){u.choice=decodeURIComponent(v);usave();uRenderToday();}
function nextUniversal(){u.stage=Math.min(5,u.stage+1);usave();uRenderToday();window.scrollTo({top:0,behavior:'smooth'});}
function saveUniversalNote(){const el=document.getElementById('uNote'),t=el?.value.trim();if(!t)return alert('Escreva ao menos uma frase com suas palavras.');u.notes.unshift({date:new Date().toLocaleDateString('pt-BR'),topic:targetName(),text:t});[1,3,7].forEach(d=>scheduleReview(d,'Revisão do bloco estudado'));u.stage=4;usave();uRenderToday();uRenderReview();}
function restartUniversal(){u.stage=0;u.choice='';usave();uRenderToday();}
function universalGuideStep(){const g=currentGuide(),s=Math.max(0,Math.min(5,u.stage));if(s===0)return `<div class="do-now">FAÇA AGORA • PASSO 1 DE 6</div><h2>${g.title}</h2><div class="casebox"><p>${g.q}</p></div><h3>Escolha uma resposta</h3><div class="choice-grid">${g.choices.map(c=>`<button class="choice ${u.choice===c?'selected':''}" onclick="chooseUniversal('${encodeURIComponent(c)}')">${c}</button>`).join('')}</div>${u.choice?'<button class="btn good nextbtn" onclick="nextUniversal()">Corrigir →</button>':''}`;
if(s===1){const ok=u.choice===g.ok;return `<div class="do-now">PASSO 2 DE 6 • CORREÇÃO</div><h2>${ok?'✅ Acertou':'❌ Vamos corrigir'}</h2><p><b>Resposta:</b> ${g.ok}</p><p>${g.why}</p><button class="btn good nextbtn" onclick="nextUniversal()">Abrir a fonte certa →</button>`;}
if(s===2)return `<div class="do-now">PASSO 3 DE 6 • FONTE</div><h2>Agora confira na fonte</h2>${g.steps.map((x,i)=>`<div class="task"><span class="stepnum">${i+1}</span><span>${x}</span></div>`).join('')}<button class="btn good nextbtn" onclick="nextUniversal()">Já conferi →</button>`;
if(s===3)return `<div class="do-now">PASSO 4 DE 6 • ANOTAÇÃO</div><h2>Guarde a regra essencial</h2><div class="callout"><b>${g.note}</b></div><textarea id="uNote" rows="4" placeholder="Explique com suas palavras o que aprendeu."></textarea><button class="btn good nextbtn" onclick="saveUniversalNote()">Salvar e gerar flashcards →</button>`;
if(s===4)return `<div class="do-now">PASSO 5 DE 6 • FLASHCARDS</div><h2>Recuperação ativa</h2><p class="muted">Responda mentalmente antes de abrir cada cartão.</p>${g.flash.map((f,i)=>flashHtml(f,i)).join('')}<button class="btn good nextbtn" onclick="nextUniversal()">Concluir bloco →</button>`;
return `<div class="donehero"><div class="checkbig">✓</div><h2>Bloco concluído</h2><p>O conteúdo entrou automaticamente no seu ciclo de revisão.</p><div class="reviewchips"><span>24h</span><span>3 dias</span><span>7 dias</span></div><button class="btn good" onclick="generateUniversalPDF()">Gerar mapa mental em PDF</button> <button class="btn secondary" onclick="restartUniversal()">Novo treino</button></div>`;}
function uRenderToday(){const first=u.profile.name?u.profile.name.split(' ')[0]:'';document.getElementById('hoje').innerHTML=`<div class="guide-layout"><div class="card guide-main">${universalGuideStep()}</div><aside class="card guide-side"><h3>Você não precisa decidir o que estudar${first?', '+first:''}</h3><p>O sistema libera uma ação por vez.</p><div class="mini-flow"><b>1.</b> Questão → <b>2.</b> Correção → <b>3.</b> Fonte → <b>4.</b> Anotação → <b>5.</b> Flashcards → <b>6.</b> Revisão</div><hr><h3>Seu objetivo</h3><p><b>${targetName()}</b></p><p class="muted">${areaLabels[u.profile.area]||'Plano personalizado'}</p><hr><button class="btn secondary full" onclick="generateUniversalPDF()">Gerar mapa mental em PDF</button></aside></div>`;}
const phases=[['Diagnóstico','Descobrir pontos fortes e fracos'],['Questões da banca','Entender o padrão de cobrança'],['Teoria essencial','Ler só o que aumenta acerto'],['Fonte primária','Conferir lei, norma ou manual'],['Caderno de erros','Transformar falhas em revisão'],['Flashcards','Recuperação ativa'],['Revisão 24h','Evitar esquecimento rápido'],['Revisão 3 dias','Consolidar'],['Revisão 7 dias','Memória de longo prazo'],['Simulado','Treinar pressão e tempo'],['Correção final','Eliminar erros recorrentes'],['Revisão pré-prova','Concentrar no que mais cai']];
function calendarRows(){const raw=udays();if(raw===null)return [];const total=Math.max(1,raw),visible=Math.min(total,21),rows=[];for(let i=0;i<visible;i++){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);const idx=Math.min(phases.length-1,Math.floor((i/Math.max(1,total-1))*(phases.length-1)));rows.push({date:d,p:phases[idx],today:i===0});}return rows;}
function uRenderSchedule(){const left=udays(),rows=calendarRows();if(left===null){document.getElementById('cronograma').innerHTML=`<div class="card"><h2>Calendário automático</h2><div class="callout"><b>Data da prova ainda não definida.</b><br>Assim que houver data oficial no edital ou retificação, a contagem e o cronograma serão recalculados automaticamente.</div></div>`;return;}document.getElementById('cronograma').innerHTML=`<div class="card"><div class="auto-calendar-head"><div><h2>Calendário automático</h2><p class="muted">Criado conforme os dias restantes para <b>${targetName()}</b>.</p></div><div class="kpi">${left}<small>dias restantes</small></div></div><div class="calendar-note">Perdeu um dia? Ao voltar, o sistema redistribui as próximas ações automaticamente.</div>${rows.map(r=>`<div class="day ${r.today?'auto-today':''}"><div class="date">${r.date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</div><div><b>${r.p[0]}</b><div class="muted">${r.p[1]}</div></div><span class="module-count">${r.today?'HOJE':''}</span></div>`).join('')}${left>21?'<p class="muted">Mostrando os próximos 21 dias; o restante continuará sendo recalculado.</p>':''}</div>`;}
function uRenderContent(){document.getElementById('pecas').innerHTML=`<div class="card"><h2>Mapa do conteúdo</h2><p class="muted">O edital vira uma sequência de ações, não uma lista solta de matérias.</p>${phases.map(p=>`<details class="piece"><summary>${p[0]}</summary><p>${p[1]}</p></details>`).join('')}</div>`;}
function uRenderMaterial(){const g=currentGuide(),isOab=u.profile.track==='oab2';document.getElementById('vade').innerHTML=`<div class="grid"><div class="card span-8"><h2>${isOab?'Vade Mecum guiado':'Fonte certa na hora certa'}</h2><p>${isOab?'A plataforma mostra onde localizar a base legal e o que observar, sem substituir a consulta permitida em prova.':'Cada bloco indica a fonte adequada: lei, norma, manual, edital ou material-base.'}</p>${g.steps.map((x,i)=>`<div class="task"><span class="stepnum">${i+1}</span><span>${x}</span></div>`).join('')}</div><div class="card span-4"><h3>Regra do método</h3><p>Uma ação por vez. Você não precisa montar sozinho a ordem do estudo.</p></div></div>`;}
function uRenderQuestions(){document.getElementById('questoes').innerHTML=`<div class="card"><h2>Questões por banca, prova e assunto</h2><p>O catálogo será organizado por <b>banca → órgão → cargo → edital → matéria → assunto</b>. Quando a prova oficial estiver disponível publicamente, a plataforma referencia a fonte original; questões próprias serão marcadas como autorais.</p><div class="qbox"><span class="pill">Seu alvo</span><h3>${targetName()}</h3><p>${areaLabels[u.profile.area]||'Plano geral'} • diagnóstico, treino, revisão e simulados.</p></div></div>`;}
function uRenderReview(){const today=new Date().toISOString().slice(0,10),due=u.reviews.filter(r=>!r.done&&r.due<=today),g=currentGuide();document.getElementById('revisao').innerHTML=`<div class="grid"><div class="card span-8"><h2>Revisão automática + flashcards</h2>${due.length?due.map((r,i)=>`<label class="task"><input type="checkbox" onchange="completeUniversalReview('${r.due}','${encodeURIComponent(r.topic)}')"><span><b>${r.topic}</b><br><span class="muted">Programada para ${new Date(r.due+'T12:00:00').toLocaleDateString('pt-BR')}</span></span></label>`).join(''):'<div class="callout"><b>Nenhuma revisão vencida agora.</b><br>Continue o estudo guiado para alimentar seu calendário.</div>'}<h3 style="margin-top:18px">Flashcards do bloco atual</h3>${g.flash.map((f,i)=>flashHtml(f,i)).join('')}</div><div class="card span-4"><h3>Memória de longo prazo</h3><p><b>Errou:</b> volta antes.<br><b>Dúvida:</b> intervalo curto.<br><b>Fácil:</b> intervalo maior.</p><button class="btn good full" onclick="generateUniversalPDF()">Mapa mental + revisão em PDF</button></div></div>`;}
function completeUniversalReview(due,topic){const t=decodeURIComponent(topic),r=u.reviews.find(x=>x.due===due&&x.topic===t&&!x.done);if(r)r.done=true;usave();uRenderReview();}
function uRenderErrors(){document.getElementById('erros').innerHTML=`<div class="card"><h2>Caderno de erros</h2><p class="muted">Erro registrado vira revisão futura.</p><div style="display:flex;gap:8px;margin-bottom:12px"><input id="uError" type="text" placeholder="O que fez você errar?"><button class="btn" onclick="addUniversalError()">Adicionar</button></div>${u.errors.length?u.errors.map((e,i)=>`<div class="task"><span>⚠️</span><span style="flex:1"><b>${e.text}</b><br><small class="muted">${e.at}</small></span><button class="btn secondary" onclick="solveUniversalError(${i})">Resolvido</button></div>`).join(''):'<p class="muted">Nenhum erro registrado ainda.</p>'}</div>`;}
function addUniversalError(){const el=document.getElementById('uError');if(!el.value.trim())return;u.errors.unshift({text:el.value.trim(),at:new Date().toLocaleString('pt-BR')});scheduleReview(1,'Caderno de erros');usave();uRenderErrors();uRenderReview();}
function solveUniversalError(i){u.errors.splice(i,1);usave();uRenderErrors();}
function uRenderSim(){document.getElementById('simulados').innerHTML=`<div class="grid"><div class="card span-8"><h2>Simulado inteligente</h2><p>O simulado será montado conforme a estrutura da prova escolhida, priorizando matérias e tipos de questão com maior necessidade de revisão.</p><div class="timer">02:00:00</div><button class="btn" onclick="alert('O modo completo de simulado será liberado na versão comercial.')">Iniciar simulado</button></div><div class="card span-4"><h3>Depois do simulado</h3><p>Os erros entram automaticamente no caderno e geram novos flashcards e revisões.</p></div></div>`;}
function generateUniversalPDF(){const g=currentGuide();if(!(window.jspdf&&window.jspdf.jsPDF))return alert('Gerador carregando. Tente novamente em alguns segundos.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape'}),W=297,H=210,cx=W/2,cy=92;doc.setFont('helvetica','bold');doc.setFontSize(18);doc.text('Mapa mental de revisão',12,14);doc.setFontSize(10);doc.text(targetName(),12,21);doc.roundedRect(cx-35,cy-12,70,24,5,5);doc.setFontSize(13);doc.text('CONTEÚDO ESTUDADO',cx,cy+1,{align:'center'});const branches=[['Regra-chave',g.note],['Fonte',g.steps.slice(0,2).join(' • ')],['Flashcards',g.flash.map(x=>x[0]).join(' • ')],['Erros',u.errors.slice(0,3).map(x=>x.text).join(' • ')||'Nenhum erro registrado'],['Minha anotação',u.notes[0]?.text||'Faça sua anotação no bloco guiado']];const pts=[[18,40],[18,135],[194,35],[194,120],[105,155]];branches.forEach((b,i)=>{const [x,y]=pts[i];doc.line(cx,cy,x+(i<2?55:0),y+16);doc.roundedRect(x,y,85,32,4,4);doc.setFontSize(10);doc.setFont('helvetica','bold');doc.text(b[0],x+4,y+6);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(doc.splitTextToSize(b[1],77).slice(0,4),x+4,y+12);});doc.setFontSize(7);doc.text('Revisão gerada pela plataforma de estudo guiado.',12,H-7);doc.save('mapa-mental-revisao.pdf');}
function uCountdown(){const e=document.getElementById('countdown'),d=udays();if(!e)return;const s=document.getElementById('smartStrip');if(d===null){e.innerHTML='DATA<br><small>A CONFIRMAR</small>';if(s)s.innerHTML=`<b>Plano automático:</b> ${targetName()} • aguardando data oficial da prova no edital.`;return;}const h=Math.max(0,Math.floor(((universalExam-new Date())%86400000)/3600000));e.innerHTML=d===0?'DIA DA PROVA':`${d} dias<br><small>${h}h restantes</small>`;if(s)s.innerHTML=`<b>Plano automático:</b> ${d} dias até ${targetName()} • data vinculada ao certame selecionado.`;}
function uRenderAll(){universalExam=u.profile.examDate?new Date(u.profile.examDate+'T13:00:00-03:00'):null;const title=document.getElementById('areaTitle'),eye=document.getElementById('examEyebrow');if(title)title.textContent=u.profile.target||'Sua próxima aprovação';if(eye)eye.textContent=`${trackLabels[u.profile.track]||'PLANO INTELIGENTE'} • ESTUDO GUIADO`;uRenderToday();uRenderSchedule();uRenderContent();uRenderMaterial();uRenderQuestions();uRenderSim();uRenderReview();uRenderErrors();uCountdown();const p=document.getElementById('progressText');if(p)p.textContent=`Bloco atual: ${Math.min(6,u.stage+1)}/6 etapas`;}
restoreTrialUniversal();uRenderAll();handleAprovaPaymentReturn();setInterval(uCountdown,60000);
