/* Perfis validados por leitura de edital. Questões deste arquivo são autorais e servem para treino do conteúdo do edital. */
(function(){
 const PALETTE=['#B3E5FC','#C8E6C9','#FFE0B2','#D1C4E9','#FFCDD2','#B2DFDB','#FFF9C4','#CFD8DC'];
 let ci=0;
 function add(k,name,summary,keywords,question,correct,wrong1,wrong2){
  if(SUBJECTS[k])return;
  const color=PALETTE[ci++%PALETTE.length],ks=keywords||[];
  SUBJECTS[k]={name,color,icon:'📘',minutes:25,summary,keywords:ks,questions:[
   {q:question,choices:[correct,wrong1,wrong2,'Nenhuma das anteriores'],ok:0,why:`${correct}. Este treino é autoral e foi alinhado ao tópico do edital.`},
   {q:`Ao revisar ${name}, qual abordagem é mais segura para uma prova do Cebraspe?`,choices:[`Dominar o conceito e testar sua aplicação em itens do mesmo assunto`,`Memorizar somente a ordem dos tópicos do edital`,`Ignorar exceções e palavras restritivas`,`Estudar apenas pelo nome da disciplina`],ok:0,why:'O Cebraspe costuma exigir compreensão e aplicação; o Aprova usa o edital para delimitar o assunto e separa questão oficial de treino autoral.'}
  ],flash:[[`${name}: foco inicial`,summary],[`Gatilhos`,ks.join(' • ')||'conceito • aplicação • exceções']]};
 }
 function weights(keys,priority=[]){const w={};keys.forEach(k=>w[k]=priority.includes(k)?10:6);return w;}

 // Núcleo fiscal, controle e tecnologia
 add('matematicafinanceira','Matemática Financeira','Porcentagens, juros, descontos, equivalência de taxas, amortização e avaliação financeira.',['juros','taxas','amortização'],'No regime de juros compostos, os juros de cada período incidem sobre:','o capital atualizado pelos juros acumulados','somente o capital inicial em todos os períodos','apenas a parcela de juros do primeiro período');
 add('contabilidadegeral','Contabilidade Geral','Patrimônio, fatos contábeis, lançamentos, demonstrações e análise básica das contas.',['patrimônio','lançamento','demonstrações'],'A equação patrimonial básica relaciona:','ativo, passivo e patrimônio líquido','receita, despesa e orçamento apenas','caixa e bancos exclusivamente');
 add('tributario','Direito Tributário','Sistema tributário, competências, limitações, obrigação, crédito e administração tributária.',['competência','obrigação','crédito tributário'],'Competência tributária corresponde, em regra, ao poder de:','instituir tributos nos limites constitucionais','arrecadar qualquer tributo independentemente de lei','dispensar sempre o lançamento');
 add('contabilidadepublica','Contabilidade Pública','Patrimônio público, execução orçamentária, registros e demonstrações do setor público.',['patrimônio público','orçamento','demonstrações'],'Na contabilidade aplicada ao setor público, o registro deve permitir acompanhar:','os efeitos orçamentários, patrimoniais e financeiros dos atos e fatos','somente o saldo bancário','apenas despesas de pessoal');
 add('economia','Economia','Microeconomia, macroeconomia, setor público, políticas econômicas e efeitos sobre alocação e renda.',['oferta','demanda','política econômica'],'Mantidos os demais fatores, uma elevação do preço tende a produzir, pela lei da demanda:','redução da quantidade demandada','aumento necessário da quantidade demandada','eliminação da escassez');
 add('financaspublicas','Finanças Públicas','Funções do Estado, política fiscal, dívida, orçamento e financiamento do gasto público.',['política fiscal','dívida','orçamento'],'Uma política fiscal expansionista pode envolver:','aumento de gastos ou redução de tributos, conforme o contexto','aumento obrigatório da taxa básica de juros','proibição de investimento público');
 add('legislacaotribestadual','Legislação Tributária Estadual','Normas tributárias estaduais previstas no edital, com atenção a fato gerador, base de cálculo, obrigações e fiscalização.',['ICMS','obrigações','fiscalização'],'Ao estudar legislação tributária estadual para prova, a fonte primária para prazos e hipóteses específicas é:','o texto legal indicado no edital','uma regra genérica de outro estado','somente jurisprudência sem conferir a lei');
 add('inteligenciaartificial','Inteligência Artificial','Fundamentos de IA, modelos, aprendizado de máquina, aplicações, riscos e governança.',['modelos','aprendizado','governança'],'Em aprendizado supervisionado, o treinamento utiliza tipicamente:','dados com exemplos de entrada e resultado esperado','somente dados sem qualquer variável-alvo','apenas regras escritas manualmente');
 add('desenvolvimentosistemas','Desenvolvimento de Sistemas','Engenharia de software, programação, APIs, testes, ciclo de desenvolvimento e práticas de entrega.',['software','API','testes'],'Testes automatizados ajudam principalmente a:','detectar regressões e validar comportamento esperado','eliminar a necessidade de requisitos','garantir que todo código esteja livre de falhas');
 add('infraestruturatic','Infraestrutura de TIC e Segurança da Informação','Redes, sistemas, nuvem, segurança, continuidade e operação de serviços de TI.',['redes','nuvem','segurança'],'Autenticação multifator reduz o risco porque:','exige evidência adicional além de uma única senha','torna desnecessária a gestão de identidade','substitui todo controle de acesso');
 add('reformatributaria','Reforma Tributária','Mudanças constitucionais e legais do sistema tributário indicadas no edital, transição e novos tributos.',['transição','IBS/CBS','sistema tributário'],'Em tema de reforma tributária, uma preparação segura deve:','separar regra vigente, regra de transição e marco temporal','misturar texto anterior e posterior sem data','usar somente material anterior à reforma');
 add('auditoriafiscal','Auditoria Fiscal','Procedimentos de fiscalização, evidências, cruzamentos, riscos e identificação de inconsistências fiscais.',['evidência','fiscalização','inconsistência'],'Em auditoria, evidência suficiente e apropriada serve para:','sustentar conclusões e achados','substituir qualquer procedimento de verificação','dispensar documentação do trabalho');
 add('cienciadados','Ciência de Dados','Coleta, tratamento, SQL, análise exploratória, mineração, aprendizado de máquina, Big Data e BI.',['dados','SQL','modelagem'],'Antes de modelar dados, uma etapa importante é:','entender, limpar e preparar os dados','ignorar valores ausentes','eliminar a análise exploratória');

 // CGU — blocos comuns e especialidades
 add('estadodemocracia','Estado, Democracia, Direitos e Ciência Política','Estado, democracia, direitos, cidadania e fundamentos de ciência política previstos no bloco básico da CGU.',['Estado','democracia','direitos'],'O Estado de Direito pressupõe que:','o exercício do poder se submeta à ordem jurídica','a Administração possa afastar a lei por conveniência','direitos fundamentais dependam sempre de autorização administrativa');
 add('sociedadebrasileira','Sociedade Brasileira, Desigualdades, Diversidade e Desenvolvimento','Formação social brasileira, desigualdades, diversidade e desenvolvimento.',['desigualdade','diversidade','desenvolvimento'],'Uma análise de desigualdade social deve distinguir:','diferenças sociais de mecanismos que produzem distribuição desigual de oportunidades e recursos','qualquer diversidade de uma violação jurídica automática','crescimento econômico de toda forma de desenvolvimento');
 add('eticapublica','Ética Pública e Responsabilidade Profissional','Ética, integridade, responsabilidade e deveres no exercício da função pública.',['ética','integridade','responsabilidade'],'Integridade pública busca principalmente:','alinhar conduta, controles e decisões ao interesse público e às normas','substituir controles internos por confiança pessoal','eliminar prestação de contas');
 add('administracaopoliticas','Administração Pública e Fundamentos de Políticas Públicas','Administração pública, políticas públicas, ciclo, implementação, monitoramento e avaliação.',['administração','políticas públicas','avaliação'],'Avaliar uma política pública significa:','examinar resultados, efeitos e relação com objetivos definidos','apenas confirmar que houve gasto','dispensar indicadores');
 add('governancariscos','Governança, Riscos e Integridade','Governança, gestão de riscos, controles e integridade pública e privada.',['governança','risco','integridade'],'Gestão de riscos procura:','identificar, avaliar e tratar eventos que podem afetar objetivos','garantir risco zero em toda atividade','substituir decisões gerenciais');
 add('transparenciaouvidoria','Transparência, Ouvidoria e Participação Social','Transparência, acesso à informação, ouvidoria, controle social e participação.',['transparência','ouvidoria','participação'],'Transparência ativa ocorre quando:','informações são divulgadas independentemente de pedido individual','todo dado público depende de requerimento','a administração não publica informações de interesse coletivo');
 add('direitopublicocontrole','Direito Público, Controle e Responsabilização','Fundamentos de direito público aplicados ao controle, responsabilização e atividade estatal.',['controle','responsabilização','direito público'],'No controle público, responsabilização exige:','base normativa e análise dos pressupostos aplicáveis ao caso','presunção automática de culpa em qualquer falha','dispensa de contraditório quando previsto em lei');
 add('evidenciasdadosia','Evidências, Dados e Inteligência Artificial','Uso de evidências, dados e IA para análise, decisão e controle, com atenção a qualidade e governança.',['evidência','dados','IA'],'Uma decisão orientada por evidências deve considerar:','qualidade, pertinência e limitações dos dados','apenas o volume de dados','qualquer correlação como causalidade');
 add('auditoriagovernamental','Auditoria Governamental e Atuação Integrada da CGU','Fundamentos de auditoria governamental e integração das funções de controle.',['auditoria','controle','CGU'],'Auditoria governamental de avaliação busca:','obter evidências e emitir conclusões sobre objeto avaliado','executar a gestão do órgão auditado','substituir o gestor nas decisões');
 add('auditoriaavaliacao','Auditoria: Avaliação, Consultoria e Apuração','Avaliação, consultoria e apuração no contexto da auditoria governamental.',['avaliação','consultoria','apuração'],'Atividade de consultoria em auditoria interna deve:','agregar valor sem assumir responsabilidade gerencial','assumir a decisão que cabe ao gestor','eliminar a independência da auditoria');
 add('financascontpublica','Finanças, Orçamento e Contabilidade Pública','Finanças públicas, orçamento e contabilidade aplicada ao setor público para a especialidade Auditoria.',['finanças','orçamento','contabilidade pública'],'A execução orçamentária deve ser analisada em conjunto com:','regras fiscais, programação e registros contábeis pertinentes','somente o saldo de caixa final','apenas a autorização inicial sem alterações');
 add('politicasavaliacao','Políticas Públicas e Métodos de Investigação e Avaliação','Métodos de investigação, desenho, monitoramento e avaliação de políticas públicas.',['métodos','avaliação','causalidade'],'Para inferir efeito causal de uma política, é importante:','comparar resultados com um contrafactual plausível','confundir correlação com causalidade','usar apenas opinião sem evidência');
 add('auditoriacontratacoes','Auditoria de Contratações e Transferências','Contratações, transferências e execução de recursos sob perspectiva de auditoria.',['contratações','transferências','recursos'],'Em auditoria de contratação pública, um ponto central é verificar:','aderência normativa, riscos, evidências e execução','somente o menor preço isoladamente','apenas a fase de pagamento');
 add('integridaderesponsabilizacao','Integridade, Transparência e Responsabilização','Integridade, transparência e mecanismos de responsabilização aplicados ao controle público.',['integridade','transparência','responsabilização'],'Um programa de integridade efetivo combina:','prevenção, detecção, resposta e monitoramento','somente código de ética sem implementação','sigilo absoluto sobre controles');
 add('estatisticaprogramacao','Estatística, Programação e Análise de Dados','Estatística, programação e análise de dados para Ciência de Dados.',['estatística','programação','análise'],'Uma análise reprodutível deve:','registrar dados, transformações e código de forma verificável','depender apenas de passos manuais não documentados','eliminar validações');
 add('engenhariadados','Engenharia, Arquitetura e Governança de Dados','Pipelines, arquitetura, qualidade, metadados e governança de dados.',['pipeline','arquitetura','governança'],'Governança de dados define, entre outros pontos:','responsabilidades, padrões, qualidade e uso dos dados','somente tamanho do banco de dados','apenas linguagem de programação');
 add('machinelearning','Aprendizado de Máquina e IA','Modelos de aprendizado, avaliação, generalização e aplicações de IA.',['modelo','treino','validação'],'Separar dados de treino e validação ajuda a:','avaliar generalização e reduzir conclusões enganosas sobre desempenho','garantir acerto de 100%','eliminar viés automaticamente');
 add('gestaodadosia','Operação e Gestão de Soluções de Dados e IA','Ciclo de vida, monitoramento, governança e operação de soluções de dados e IA.',['MLOps','monitoramento','governança'],'Depois de implantar um modelo, é importante:','monitorar desempenho, dados e mudanças de contexto','considerá-lo imutável','dispensar controle de versão');
 add('redessistemasdados','Redes, Sistemas e Plataformas de Dados','Redes, sistemas operacionais, armazenamento e plataformas de dados.',['redes','sistemas','plataformas'],'Segmentação de rede pode ajudar a:','reduzir propagação de incidentes e controlar fluxos','eliminar a necessidade de autenticação','tornar todos os serviços públicos');
 add('nuvemvirtualizacao','Nuvem, Virtualização e Automação','Computação em nuvem, virtualização, contêineres e automação de infraestrutura.',['nuvem','virtualização','automação'],'Infraestrutura como código favorece:','padronização, versionamento e automação de configuração','mudanças sem registro','dependência exclusiva de configuração manual');
 add('ciberseguranca','Cibersegurança, Privacidade e Continuidade','Segurança, privacidade, gestão de incidentes e continuidade de serviços.',['segurança','privacidade','continuidade'],'Princípio do menor privilégio recomenda:','conceder somente acessos necessários à função','dar acesso administrativo a todos','manter credenciais compartilhadas');
 add('gestaoservicosdigitais','Operação e Gestão de Serviços Digitais','Operação, disponibilidade, incidentes, mudanças e governança de serviços digitais.',['serviços','incidentes','mudanças'],'Gestão de incidentes busca:','restaurar o serviço e reduzir impacto com processo controlado','ocultar falhas do monitoramento','impedir qualquer mudança futura');
 add('engenhariasoftware','Engenharia de Software e Programação','Requisitos, design, programação, testes, qualidade e ciclo de software.',['requisitos','código','testes'],'Integração contínua ajuda a:','detectar problemas cedo por builds e testes frequentes','dispensar revisão de código','eliminar requisitos');
 add('arquiteturasistemas','Arquitetura e Integração de Sistemas','Arquiteturas, APIs, mensageria, integração e sistemas distribuídos.',['arquitetura','API','integração'],'Uma API bem definida deve explicitar:','contratos de entrada, saída e erros','somente a linguagem usada internamente','credenciais no código cliente');
 add('persistenciadados','Persistência, Integração e Proteção de Dados','Bancos, transações, integração, consistência e proteção de dados.',['bancos','transações','proteção'],'Uma transação de banco de dados busca preservar propriedades como:','atomicidade e consistência','ausência de controle de concorrência','eliminação de logs');
 add('desenvolvimentoseguro','Desenvolvimento Seguro, Qualidade e Entrega','Segurança no ciclo de desenvolvimento, qualidade, pipelines e entrega.',['DevSecOps','qualidade','entrega'],'Desenvolvimento seguro recomenda:','tratar segurança desde requisitos até operação','avaliar segurança apenas depois da produção','armazenar segredos no repositório');

 // Militar AL
 add('ingles','Língua Inglesa','Compreensão de textos e estruturas linguísticas previstas no edital.',['reading','vocabulary','grammar'],'Em questão de compreensão em inglês, uma estratégia segura é:','identificar ideia central e relações no texto antes de traduzir palavra por palavra','marcar pela palavra mais parecida com português','ignorar conectores');
 add('matematica','Matemática','Álgebra, funções, geometria, análise combinatória e demais tópicos previstos no edital do cargo.',['álgebra','funções','geometria'],'Se f(x)=2x+3, então f(2) é igual a:','7','5','10');
 add('fisica','Física','Mecânica, termodinâmica, eletricidade, ondas e demais tópicos definidos no edital do cargo.',['mecânica','energia','eletricidade'],'Pela segunda lei de Newton, a força resultante é igual a:','massa vezes aceleração','massa dividida pela velocidade','energia vezes tempo');
 add('quimica','Química','Estrutura atômica, ligações, reações, estequiometria e tópicos do edital do cargo.',['átomo','ligações','reações'],'Uma ligação iônica envolve tipicamente:','atração entre íons de cargas opostas após transferência de elétrons','compartilhamento obrigatório entre gases nobres','ausência de interação eletrostática');
 add('biologia','Biologia','Célula, fisiologia humana, evolução, ecologia e saúde conforme o edital.',['célula','fisiologia','ecologia'],'A membrana plasmática tem como função central:','controlar trocas entre a célula e o meio','produzir todo o DNA da célula','substituir o núcleo');
 add('mecanicageral','Mecânica Geral','Motores, transmissão, freios, suspensão, sistema elétrico, arrefecimento e alimentação.',['motor','freios','transmissão'],'O sistema de arrefecimento do motor tem como objetivo principal:','controlar a temperatura de funcionamento','aumentar permanentemente a temperatura','substituir o sistema de lubrificação');
 add('conhecimentosalagoas','Conhecimentos do Estado de Alagoas','História, geografia, organização político-administrativa, economia e cultura de Alagoas.',['Alagoas','história','geografia'],'O Quilombo dos Palmares integra o estudo de Alagoas principalmente por sua relação com:','resistência à escravidão no período colonial','industrialização automobilística','fundação de Brasília');
 add('legislacaocbmal','Legislação Pertinente ao CBM/AL','Estatuto, disciplina, carreira e legislação orgânica indicada no edital do CBM/AL.',['CBMAL','estatuto','disciplina'],'Em legislação institucional, a resposta sobre dever ou proibição deve ser conferida prioritariamente:','na norma expressamente indicada no edital','em regra de outro estado','em comentário sem consultar a lei');
 add('legislacaopmal','Legislação Pertinente à PM/AL','Estatuto, regulamento disciplinar, legislação orgânica e leis especiais indicadas para o cargo.',['PMAL','estatuto','leis especiais'],'Ao resolver item sobre legislação da PM/AL, deve-se distinguir:','norma estadual específica e lei federal indicada no edital','qualquer estatuto militar de outro estado','opinião doutrinária sem base normativa');
 add('cienciassociais','Ciências Sociais','Sociologia e Filosofia conforme o conteúdo específico do Oficial de Estado-Maior.',['sociologia','filosofia','sociedade'],'Nas ciências sociais, diferenciar senso comum de conhecimento científico exige considerar:','método, evidência e construção sistemática do conhecimento','apenas popularidade de uma opinião','somente tradição');
 add('cienciasnatureza','Ciências da Natureza','Biologia, Física e Química integradas conforme o conteúdo do Oficial da PM/AL.',['biologia','física','química'],'Uma preparação integrada em ciências da natureza deve:','identificar qual princípio físico, químico ou biológico explica o fenômeno','memorizar somente definições isoladas','ignorar unidades e relações causais');
 add('penalmilitar','Direito Penal Militar','Aplicação da lei penal militar, crime militar, penas e crimes militares em tempo de paz.',['crime militar','CPM','penas'],'A classificação de um fato como crime militar depende:','dos critérios e hipóteses previstos na legislação penal militar','apenas da profissão do acusado','somente do local do fato');
 add('processopenalmilitar','Direito Processual Penal Militar','Polícia judiciária militar, IPM, ação penal militar, prisões, processos e recursos.',['IPM','ação penal militar','prisão'],'O inquérito policial militar é instrumento destinado, em regra, a:','apurar fato e autoria no âmbito da polícia judiciária militar','proferir sentença condenatória','substituir a ação penal');

 // TCE/AC
 add('civil','Direito Civil','Pessoas, bens, obrigações, contratos, responsabilidade e demais pontos do edital.',['obrigações','contratos','responsabilidade'],'Responsabilidade civil pressupõe análise de elementos como:','conduta, dano e nexo causal, conforme o regime aplicável','somente intenção dolosa em todos os casos','apenas existência de contrato');
 add('processocontas','Direito Processual de Contas','Processo perante tribunais de contas, competências, sujeitos, decisões e recursos.',['processo de contas','TCE','recursos'],'No processo de contas, a competência do tribunal deve ser analisada a partir:','da Constituição e da legislação institucional aplicável','de regras do processo penal apenas','da vontade das partes');
 add('processocivil','Direito Processual Civil','Jurisdição, processo, sujeitos, atos, tutela, recursos e execução.',['processo','recursos','tutela'],'A tutela provisória pode se fundamentar, conforme o CPC, em:','urgência ou evidência','somente trânsito em julgado','apenas acordo entre as partes');
 add('financeiro','Direito Financeiro','Orçamento, receita, despesa, responsabilidade fiscal e finanças públicas.',['orçamento','LRF','receita'],'Crédito adicional relaciona-se à:','autorização orçamentária para despesas nas hipóteses legais','criação automática de tributo','dispensa de controle fiscal');
 add('empresarial','Direito Empresarial','Empresa, empresário, sociedades, títulos, recuperação e falência nos limites do edital.',['empresa','sociedades','falência'],'Sociedade empresária deve ser analisada considerando:','tipo societário, atividade e regime jurídico aplicável','somente o nome fantasia','apenas o valor do capital inicial');
 add('previdenciario','Direito Previdenciário','Seguridade, regimes previdenciários, benefícios e regras constitucionais/legais do edital.',['seguridade','RPPS','benefícios'],'A seguridade social compreende, constitucionalmente:','saúde, previdência e assistência social','apenas previdência contributiva','somente saúde e educação');
 add('controleexterno','Controle Externo e Legislação Institucional','Controle externo, competências dos tribunais de contas e legislação institucional do TCE/AC.',['controle externo','TCE','competência'],'O controle externo exercido com auxílio de tribunal de contas tem fundamento central:','na Constituição e nas competências legalmente atribuídas','em delegação privada','somente em ato interno do gestor');
 add('afo','Administração Financeira e Orçamentária','PPA, LDO, LOA, execução, créditos e instrumentos de gestão orçamentária.',['PPA','LDO','LOA'],'A LOA é o instrumento que:','estima receitas e fixa despesas para o exercício financeiro','define apenas metas de longo prazo sem orçamento','substitui a Constituição');
 add('administracaopublica','Administração Pública','Modelos de gestão, planejamento, processos, pessoas, governança e gestão pública.',['gestão','processos','governança'],'Gestão por processos procura:','entender e melhorar fluxos de trabalho orientados a resultados','organizar apenas cargos hierárquicos','eliminar indicadores');
 add('analisedemonstracoes','Contabilidade Geral e Análise das Demonstrações','Contabilidade geral, demonstrações e análise econômico-financeira.',['balanço','demonstrações','índices'],'Análise de demonstrações utiliza índices para:','interpretar relações entre contas e desempenho financeiro','substituir os registros contábeis','eliminar notas explicativas');
 add('economiasetorpublico','Economia do Setor Público e Regulação','Falhas de mercado, setor público, regulação e políticas econômicas.',['regulação','falhas de mercado','setor público'],'Uma justificativa econômica clássica para regulação é:','corrigir ou mitigar determinadas falhas de mercado','eliminar toda concorrência','garantir lucro privado');
 add('realidadeacre','Realidade do Acre','Aspectos étnicos, sociais, geográficos, culturais, políticos e econômicos do Acre.',['Acre','sociedade','geografia'],'Uma questão sobre realidade regional deve ser resolvida considerando:','dados, contexto histórico-geográfico e fatos específicos do Acre','características de qualquer estado como equivalentes','apenas conhecimentos nacionais genéricos');

 const CGU_COMMON=['estadodemocracia','sociedadebrasileira','eticapublica','administracaopoliticas','governancariscos','transparenciaouvidoria','direitopublicocontrole','evidenciasdadosia','auditoriagovernamental'];
 const cgu=(id,label,specific)=>({id,label,subjectWeights:weights([...CGU_COMMON,...specific],specific),recommendedStart:specific[0],questionFormat:'ce'});
 COURSE_ROLE_PROFILES['ceb-cgu26-affc']={title:'CGU 2026 — AFFC',banca:'Cebraspe',source:'https://www.cebraspe.org.br/concursos/cgu_26_affc',questionFormat:'ce',structure:'P1: 40 itens de conhecimentos básicos; P2: 40 itens de conhecimentos complementares; P3: 90 itens de conhecimentos específicos; P4: 2 questões discursivas. Objetivas no formato CERTO/ERRADO, com pontuação negativa por erro conforme o edital.',roles:[
  cgu('auditoria','AFFC — Auditoria',['auditoriaavaliacao','financascontpublica','politicasavaliacao','auditoriacontratacoes','integridaderesponsabilizacao']),
  cgu('ti-dados','AFFC — TI — Ciência de Dados',['estatisticaprogramacao','engenhariadados','machinelearning','gestaodadosia']),
  cgu('ti-infra','AFFC — TI — Infraestrutura de TI',['redessistemasdados','nuvemvirtualizacao','ciberseguranca','gestaoservicosdigitais']),
  cgu('ti-dev','AFFC — TI — Desenvolvimento de Sistemas',['engenhariasoftware','arquiteturasistemas','persistenciadados','desenvolvimentoseguro'])
 ]};

 DIRECT_COURSE_PROFILES['ceb-sefazal26-afte']={role:'Auditor Fiscal da Administração Tributária Estadual',subjectWeights:{matematicafinanceira:5,constitucional:5,administrativo:5,contabilidadegeral:5,tributario:10,estatistica:10,contabilidadepublica:10,economia:10,financaspublicas:10,legislacaotribestadual:10,inteligenciaartificial:10,desenvolvimentosistemas:10,infraestruturatic:10,reformatributaria:15,auditoriafiscal:15,cienciadados:20},recommendedStart:'tributario',questionFormat:'ce',examStructure:'P1: 60 itens — Matemática Financeira 5, Constitucional 5, Administrativo 5, Contabilidade Geral 5, Tributário 10, Estatística e Probabilidade 10, Contabilidade Pública 10 e Economia 10. P2: 100 itens — Finanças Públicas 10, Legislação Tributária Estadual 10, IA 10, Desenvolvimento de Sistemas 10, Infraestrutura de TIC/Segurança 10, Reforma Tributária 15, Auditoria Fiscal 15 e Ciência de Dados 20. P3: 4 discursivas de 10 pontos: Ciência de Dados, Auditoria Fiscal, Finanças Públicas e Reforma Tributária. Objetivas CERTO/ERRADO.',examSource:'https://www.cebraspe.org.br/concursos/SEFAZ_AL_26'};

 const cbmBasic=['portugues','ingles','informatica','matematica','raciocinio','legislacaocbmal','direitoshumanos','atualidades'];
 COURSE_ROLE_PROFILES['ceb-cbmal26']={title:'CBM/AL 2026',banca:'Cebraspe',source:'https://www.cebraspe.org.br/concursos/CBM_AL_26',questionFormat:'ce',structure:'P1: 50 itens de conhecimentos básicos; P2: 70 itens de conhecimentos específicos; P3: discursiva; depois TAF, saúde, psicológica, conduta/reputação/idoneidade e toxicológico. Objetivas CERTO/ERRADO. Provas em 24/01/2027.',roles:[
  {id:'oficial','label':'Oficial de Estado-Maior',subjectWeights:weights([...cbmBasic,'fisica','quimica','biologia','administrativo','constitucional'],['fisica','quimica','biologia','administrativo','constitucional']),recommendedStart:'fisica',questionFormat:'ce'},
  {id:'qpbm1','label':'Soldado QPBM/1',subjectWeights:weights([...cbmBasic,'fisica','quimica','biologia','mecanicageral'],['fisica','quimica','biologia','mecanicageral']),recommendedStart:'fisica',questionFormat:'ce'},
  {id:'qpbm2','label':'Soldado QPBM/2',subjectWeights:weights([...cbmBasic,'fisica','quimica','biologia','mecanicageral'],['fisica','quimica','biologia','mecanicageral']),recommendedStart:'mecanicageral',questionFormat:'ce'}
 ]};

 const pmBasicOf=['portugues','ingles','informatica','conhecimentosalagoas','atualidades'];
 const pmBasicSold=['portugues','matematica','informatica','conhecimentosalagoas','atualidades'];
 const pmOfSpec=['cienciassociais','cienciasnatureza','matematica','legislacaopmal','penal','direitoshumanos','processopenal','penalmilitar','processopenalmilitar','constitucional','administrativo'];
 const pmSoldSpec=['legislacaopmal','administrativo','constitucional','processopenal','penalmilitar','processopenalmilitar','direitoshumanos'];
 COURSE_ROLE_PROFILES['ceb-pmal26']={title:'PM/AL 2026',banca:'Cebraspe',source:'https://www.cebraspe.org.br/concursos/PM_AL_26',questionFormat:'ce',structure:'P1: 50 itens de conhecimentos básicos; P2: 70 itens de conhecimentos específicos; P3: discursiva; depois TAF, saúde, psicológica, comprovação documental/investigação social e toxicológico. Objetivas CERTO/ERRADO. Provas em 17/01/2027.',roles:[
  {id:'oficial','label':'Oficial de Estado-Maior',subjectWeights:weights([...pmBasicOf,...pmOfSpec],pmOfSpec),recommendedStart:'legislacaopmal',questionFormat:'ce'},
  {id:'soldado','label':'Soldado do Quadro de Praças',subjectWeights:weights([...pmBasicSold,...pmSoldSpec],pmSoldSpec),recommendedStart:'legislacaopmal',questionFormat:'ce'}
 ]};

 DIRECT_COURSE_PROFILES['ceb-tceac26-auditor']={role:'Auditor – Conselheiro Substituto',subjectWeights:weights(['constitucional','administrativo','civil','processocontas','processocivil','penal','financeiro','empresarial','tributario','previdenciario','controleexterno','auditoriagovernamental','afo','administracaopublica','analisedemonstracoes','contabilidadepublica','economiasetorpublico','realidadeacre'],['controleexterno','processocontas','contabilidadepublica','afo']),recommendedStart:'controleexterno',questionFormat:'abcde',examStructure:'P1: 100 questões objetivas de múltipla escolha A–E. P2: 3 questões discursivas de conhecimentos específicos (até 20 linhas cada) e 1 peça técnica (até 70 linhas). Depois: prova oral em Constitucional, Administrativo, Controle Externo/Legislação Institucional e AFO/Orçamento/Contabilidade Pública; e avaliação de títulos. Provas objetiva e discursiva em 17/01/2027.',examSource:'https://www.cebraspe.org.br/concursos/TCE_AC_26'};


 // OAB — cursos liberados somente com fase e estrutura identificadas.
 function addOab(k,name,summary,keywords,q,correct,wrong1,wrong2){
  if(SUBJECTS[k])return;
  const color=PALETTE[ci++%PALETTE.length],ks=keywords||[];
  SUBJECTS[k]={name,color,icon:'⚖️',minutes:25,summary,keywords:ks,questions:[
   {q,choices:[correct,wrong1,wrong2,'Nenhuma das anteriores'],ok:0,why:`${correct}. Treino autoral delimitado pelo conteúdo do Exame de Ordem.`},
   {q:`Em ${name}, qual estratégia reduz mais o risco de erro na FGV/OAB?`,choices:[`Ler o comando, identificar a regra jurídica e só então comparar as alternativas`,`Escolher pela alternativa mais longa`,`Ignorar exceções legais`,`Memorizar apenas palavras soltas`],ok:0,why:'Na OAB/FGV, o treino deve combinar leitura do comando, regra aplicável e comparação das alternativas, sempre distinguindo questão oficial de exercício autoral.'}
  ],flash:[[`${name}: foco`,summary],[`Gatilhos`,ks.join(' • ')||'regra • exceção • aplicação']]};
 }
 addOab('eticaoab','Ética Profissional e Estatuto da OAB','Estatuto da Advocacia, Regulamento Geral e Código de Ética e Disciplina, com foco em prerrogativas, incompatibilidades, honorários, publicidade, sociedade e processo disciplinar.',['prerrogativas','honorários','incompatibilidade'],'A publicidade profissional na advocacia deve observar, em regra:','caráter informativo e discrição, sem mercantilização indevida','promessa de resultado ao cliente','captação ostensiva de clientela');
 addOab('trabalho','Direito do Trabalho','Relação de emprego, contrato, jornada, remuneração, estabilidade, rescisão e direitos trabalhistas.',['emprego','jornada','rescisão'],'A relação de emprego exige, entre outros elementos:','pessoalidade, onerosidade, não eventualidade e subordinação','somente contrato escrito','exclusivamente remuneração variável');
 addOab('processotrabalho','Processo do Trabalho','Competência, partes, atos, audiência, provas, recursos e execução trabalhista.',['competência','audiência','recursos'],'Na Justiça do Trabalho, a competência material é definida principalmente:','pela natureza da relação jurídica e pelas hipóteses constitucionais','pelo valor da causa apenas','pela escolha unilateral do empregador');
 addOab('consumidor','Direito do Consumidor','Princípios do CDC, responsabilidade, práticas abusivas, contratos, proteção e tutela coletiva.',['CDC','responsabilidade','práticas abusivas'],'A responsabilidade objetiva do fornecedor, quando prevista no CDC, dispensa a prova de:','culpa','dano','nexo causal');
 addOab('eca','Estatuto da Criança e do Adolescente','Proteção integral, direitos fundamentais, medidas de proteção, ato infracional e competências.',['proteção integral','ato infracional','medidas'],'O ECA adota como eixo central:','a doutrina da proteção integral','a responsabilidade penal idêntica à do adulto','a ausência de prioridade absoluta');
 addOab('internacional','Direito Internacional','Fontes, tratados, nacionalidade, condição jurídica do estrangeiro, cooperação e direitos internacionais.',['tratados','nacionalidade','cooperação'],'Tratado internacional incorporado ao direito brasileiro depende:','do procedimento constitucional de celebração e incorporação aplicável','apenas de assinatura privada','sempre de lei complementar');
 addOab('filosofia','Filosofia do Direito','Teorias da justiça, positivismo, jusnaturalismo, interpretação, argumentação e fundamentos do direito.',['justiça','positivismo','interpretação'],'Uma questão de filosofia do direito deve ser resolvida identificando:','a tese do autor ou corrente e suas premissas','somente palavras de efeito','apenas a época histórica');
 addOab('ambiental','Direito Ambiental','Princípios, competências, licenciamento, responsabilidade ambiental e tutela constitucional.',['licenciamento','responsabilidade','princípios'],'A responsabilidade civil por dano ambiental é, em regra:','objetiva','sempre subjetiva','inexistente sem condenação penal');
 addOab('eleitoral','Direito Eleitoral','Direitos políticos, elegibilidade, inelegibilidades, partidos, propaganda e processo eleitoral.',['elegibilidade','inelegibilidade','propaganda'],'Inelegibilidade corresponde a:','impedimento jurídico à capacidade eleitoral passiva nas hipóteses previstas','perda automática da nacionalidade','suspensão de todo direito civil');

 DIRECT_COURSE_PROFILES['oab-47']={role:'2ª Fase — Direito Constitucional',subjectWeights:{constitucional:100},recommendedStart:'constitucional',questionFormat:'practical',examStructure:'Prova prático-profissional da 2ª fase em Direito Constitucional: 1 peça profissional (5,0 pontos) e 4 questões discursivas práticas (1,25 ponto cada), total de 10 pontos. Aprovação com nota igual ou superior a 6,0. Data oficial: 18/10/2026.',examSource:'https://examedeordem.oab.org.br/Calendario'};
 DIRECT_COURSE_PROFILES['oab-48']={role:'1ª Fase — Prova Objetiva',subjectWeights:{eticaoab:8,constitucional:6,civil:6,processocivil:6,penal:6,processopenal:6,administrativo:5,tributario:5,trabalho:5,processotrabalho:5,empresarial:4,filosofia:2,direitoshumanos:2,eleitoral:2,internacional:2,financeiro:2,ambiental:2,consumidor:2,eca:2,previdenciario:2},recommendedStart:'eticaoab',questionFormat:'abcd',examStructure:'Prova objetiva da 1ª fase: 80 questões de múltipla escolha, com quatro alternativas e uma única resposta correta, em 5 horas. Aprovação com 40 pontos. O edital abrange as disciplinas técnico-jurídicas do curso de Direito e também Estatuto/Ética da OAB, Direitos Humanos, Consumidor, ECA, Ambiental, Internacional, Filosofia, Financeiro, Previdenciário e Eleitoral. O plano usa a incidência histórica recente apenas para priorizar o cronograma; o edital garante no mínimo 15% para Estatuto/Regulamento/Código de Ética, Direitos Humanos e Filosofia. Data oficial: 10/01/2027.',examSource:'https://examedeordem.oab.org.br/EditaisProvas?NumeroExame=18617'};

 // Copia também o formato da questão para a sessão, evitando usar um caderno histórico C/E em curso A–E (ou vice-versa).
 const oldApply=applyCourseProfile;
 applyCourseProfile=function(hit,role=null){oldApply(hit,role);const direct=DIRECT_COURSE_PROFILES[hit?.id]||null,parent=COURSE_ROLE_PROFILES[hit?.id]||null,prof=role||direct;u.profile.questionFormat=prof?.questionFormat||parent?.questionFormat||'';u.profile.validation='edital-lido';};
})();
