/* Concursos validados manualmente em edital oficial. Novos itens do robô continuam ocultos até entrarem aqui. */
window.APROVA_CURATED_COURSES=[
 {id:'ceb-cgu26-affc',title:'CGU 2026 — Auditor Federal de Finanças e Controle',banca:'Cebraspe',status:'Edital publicado • inscrições 10/10 a 04/11/2026 • prova 13/12/2026',category:'Concurso público',source_url:'https://www.cebraspe.org.br/concursos/cgu_26_affc',official:true,exam_date:'2026-12-13',tags:['CGU','AFFC','Cebraspe','Auditoria','Tecnologia da Informação'],last_seen:'2026-10-09',validation:'edital-lido'},
 {id:'ceb-sefazal26-afte',title:'SEFAZ/AL 2026 — Auditor Fiscal da Administração Tributária Estadual',banca:'Cebraspe',status:'Inscrições até 21/10/2026 • objetiva 20/12/2026 • discursiva 10/01/2027',category:'Concurso público',source_url:'https://www.cebraspe.org.br/concursos/SEFAZ_AL_26',official:true,exam_date:'2026-12-20',tags:['SEFAZ/AL','AFTE','Cebraspe','Fiscal','Tributária'],last_seen:'2026-10-09',validation:'edital-lido'},
 {id:'ceb-cbmal26',title:'CBM/AL 2026 — Oficiais e Praças',banca:'Cebraspe',status:'Inscrições reabertas até 26/10/2026 • prova 24/01/2027',category:'Concurso público',source_url:'https://www.cebraspe.org.br/concursos/CBM_AL_26',official:true,exam_date:'2027-01-24',tags:['CBM/AL','Bombeiros','Cebraspe','Oficial','Soldado'],last_seen:'2026-10-09',validation:'edital-lido'},
 {id:'ceb-pmal26',title:'PM/AL 2026 — Oficiais e Praças',banca:'Cebraspe',status:'Inscrições reabertas até 16/10/2026 • prova 17/01/2027',category:'Concurso público',source_url:'https://www.cebraspe.org.br/concursos/PM_AL_26',official:true,exam_date:'2027-01-17',tags:['PM/AL','Polícia Militar','Cebraspe','Oficial','Soldado'],last_seen:'2026-10-09',validation:'edital-lido'},
 {id:'ceb-tceac26-auditor',title:'TCE/AC 2026 — Auditor – Conselheiro Substituto',banca:'Cebraspe',status:'Inscrições reabertas 05/10 a 26/10/2026 • provas 17/01/2027',category:'Concurso público',source_url:'https://www.cebraspe.org.br/concursos/TCE_AC_26',official:true,exam_date:'2027-01-17',tags:['TCE/AC','Auditor','Conselheiro Substituto','Cebraspe','Controle'],last_seen:'2026-10-09',validation:'edital-lido'}
];
window.APROVA_VALIDATED_COURSE_IDS=new Set(window.APROVA_CURATED_COURSES.map(x=>x.id));
